### ISSUE TITLE
test_send_update_notice_message_template_el7 is failing

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1082]
I seem to have merged a commit that caused a test to fail:

```
======================================================================
ERROR: Ensure update message template reflects EL <= 7 when it should
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/vagrant/bodhi/tests/server/models/test_models.py", line 855, in test_send_update_notice_message_template_el7
    get_template.assert_called_with(update, u'fedora_epel_errata_legacy_template')
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 928, in _error_message
    msg = self._format_mock_failure_message(args, kwargs)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 860, in _format_mock_failure_message
    expected_string = self._format_mock_call_signature(args, kwargs)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 855, in _format_mock_call_signature
    return _format_call_signature(name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 2067, in _format_call_signature
    args_string = ', '.join([repr(arg) for arg in args])
  File "/vagrant/bodhi/server/models/models.py", line 83, in __repr__
    return '<{0} {1}>'.format(self.__class__.__name__, self.__json__())
  File "/vagrant/bodhi/server/models/models.py", line 1926, in __json__
    result['submitter'] = result['user']['name']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by bowlofeggs** [comment]
This shameful commit of mine broke it: https://github.com/fedora-infra/bodhi/commit/afa75f655bc4f9380c19258e26013da0c0777f22
