### ISSUE TITLE
Crash on aborting a push

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#1107]
bodhi-server-2.3.1-1.fc24
python2-bodhi-2.3.1-1.fc24

<pre>
Push these 86 updates? (y/n) n

Aborting push
Traceback (most recent call last):
  File "/bin/bodhi-push", line 9, in <module>
    load_entry_point('bodhi-server==2.3.1', 'console_scripts', 'bodhi-push')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bodhi/server/push.py", line 146, in push
    raise Exception('Aborting push')
Exception: Aborting push
</pre>

**Comment by bowlofeggs** [comment]
Haha, looks like we probably should have raised a Click Exception instead of just `Exception`.
