### ISSUE TITLE
bodhi-push crashes when trying to get help

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#1120]
When trying to get assistance as to what the command like options are for bodhi-push it crashes:

<pre>
[PROD]$ bodhi-push --help
Traceback (most recent call last):
  File "/usr/bin/bodhi-push", line 9, in <module>
    load_entry_point('bodhi-server==2.3.1', 'console_scripts', 'bodhi-push')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/bodhi/server/push.py", line 32, in <module>
    from bodhi.server.models import Update, Base, UpdateRequest, Build, Release, ReleaseState
  File "/usr/lib/python2.7/site-packages/bodhi/server/models/__init__.py", line 15, in <module>
    from models import *
  File "/usr/lib/python2.7/site-packages/bodhi/server/models/models.py", line 57, in <module>
    from bodhi.server.bugs import bugtracker
  File "/usr/lib/python2.7/site-packages/bodhi/server/bugs.py", line 178, in <module>
    if config.get('bugtracker') == 'bugzilla':
  File "/usr/lib/python2.7/site-packages/bodhi/server/config.py", line 51, in get
    self.load_config()
  File "/usr/lib/python2.7/site-packages/bodhi/server/config.py", line 56, in load_config
    self.update(get_appsettings(configfile))
  File "/usr/lib/python2.7/site-packages/pyramid/paster.py", line 53, in get_appsettings
    global_conf=options)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 261, in appconfig
    global_conf=global_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
    loader = ConfigLoader(path)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
    with open(filename) as f:
IOError: [Errno 13] Permission denied: '/etc/bodhi/production.ini'
[PROD]$ bodhi-push
Traceback (most recent call last):
  File "/usr/bin/bodhi-push", line 9, in <module>
    load_entry_point('bodhi-server==2.3.1', 'console_scripts', 'bodhi-push')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/bodhi/server/push.py", line 32, in <module>
    from bodhi.server.models import Update, Base, UpdateRequest, Build, Release, ReleaseState
  File "/usr/lib/python2.7/site-packages/bodhi/server/models/__init__.py", line 15, in <module>
    from models import *
  File "/usr/lib/python2.7/site-packages/bodhi/server/models/models.py", line 57, in <module>
    from bodhi.server.bugs import bugtracker
  File "/usr/lib/python2.7/site-packages/bodhi/server/bugs.py", line 178, in <module>
    if config.get('bugtracker') == 'bugzilla':
  File "/usr/lib/python2.7/site-packages/bodhi/server/config.py", line 51, in get
    self.load_config()
  File "/usr/lib/python2.7/site-packages/bodhi/server/config.py", line 56, in load_config
    self.update(get_appsettings(configfile))
  File "/usr/lib/python2.7/site-packages/pyramid/paster.py", line 53, in get_appsettings
    global_conf=options)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 261, in appconfig
    global_conf=global_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
    loader = ConfigLoader(path)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
    with open(filename) as f:
IOError: [Errno 13] Permission denied: '/etc/bodhi/production.ini'
</pre>

**Comment by puiterwijk** [comment]
Right. It currently tries to load the configuration file immediately. As such, you should currently use sudo bodhi-push --help.

I'm reasonably sure we can fix this, but it'll be tricky given that it's the bugtracker code that does this..

**Comment by nullr0ute** [comment]
Yup, I worked that out, but it's non intuitive and not what you would expect and putting in tokens etc just to get help is a little painful hence the bug report.

**Comment by puiterwijk** [comment]
Not saying I disagree, just tried to get you running.

As said, while I agree it would be nice to get this fixed, I'm not sure it'll be easy.
