### ISSUE TITLE
Problem promoting stuff

### ISSUE THREAD

**Issue by Fale** [fedora-infra/bodhi#1178]
```
fale@redhat:~ $ bodhi -R testing python-lxml-3.7.0-1.fc23
No handlers could be found for logger "fedora.client.bodhi"
Password: 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 273, in main
    log.info(data['tg_flash'])
KeyError: 'tg_flash'
```

**Comment by bowlofeggs** [comment]
Let's use the downstream Bugzilla issue to track this, since it's a problem with bodhi-0.9:

https://bugzilla.redhat.com/show_bug.cgi?id=1279313

Thanks for the report!
