### ISSUE TITLE
Ensure the masher's Koji interactions are fault-tolerant

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/bodhi#1201]
This is an expansion on https://github.com/fedora-infra/bodhi/issues/1143.

The masher is a long-running task that needs to handle failures gracefully. The masher's interactions with Koji need to work despite intermittent network problems. This includes authentication, which involves the Kerberos server.

- [x] Ensure calls to Koji are retried in the event of network problems

- [ ]  Ensure that if there is an authentication problem, it is retried

**Comment by bowlofeggs** [comment]
I think we can use ```backoff``` in ```bodhi.server.buildsys.koji_login()``` to help with Koji auth errors. I get tracebacks like this one from time to time, and it would be wonderful to eliminate them:

```
2019-06-07 00:13:24,087 ERROR [bodhi][f29-updates] ComposerThread failed. Transaction rolled back.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/composer.py", line 316, in run
    self.work()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/composer.py", line 386, in work
    self._compose_updates()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/composer.py", line 923, in _compose_updates
    uinfo = self._generate_updateinfo()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/composer.py", line 992, in _generate_updateinfo
    self.db, self.compose_dir)
  File "/usr/lib/python3.7/site-packages/bodhi/server/metadata.py", line 148, in __init__
    self.add_update(update)
  File "/usr/lib/python3.7/site-packages/bodhi/server/metadata.py", line 234, in add_update
    koji = get_session()
  File "/usr/lib/python3.7/site-packages/bodhi/server/buildsys.py", line 578, in get_session
    return _buildsystem()
  File "/usr/lib/python3.7/site-packages/bodhi/server/buildsys.py", line 610, in get_koji_login
    return koji_login(config=settings, authenticate=authenticate)
  File "/usr/lib/python3.7/site-packages/bodhi/server/buildsys.py", line 535, in koji_login
    if authenticate and not koji_client.krb_login(**get_krb_conf(config)):
  File "/usr/lib/python3.7/site-packages/koji/__init__.py", line 2161, in krb_login
    if self.gssapi_login(principal, keytab, ccache, proxyuser=proxyuser):
  File "/usr/lib/python3.7/site-packages/koji/__init__.py", line 2315, in gssapi_login
    raise AuthError('unable to obtain a session')
koji.AuthError: unable to obtain a session
```
