### ISSUE TITLE
Port from yum to dnf

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#121]
We should port from the `yum` module to `dnf`.

It's currently used in a couple of different places (along with the unit tests):
https://github.com/fedora-infra/bodhi/blob/pyramid/bodhi/util.py#L231
https://github.com/fedora-infra/bodhi/blob/pyramid/bodhi/metadata.py

**Comment by ignatenkobrain** [comment]
will do ;)

**Comment by ignatenkobrain** [comment]
This is what I have in mind:
```patch
From 197b2e49abeaf7fb92755c3dc5aa0a6fff87e55e Mon Sep 17 00:00:00 2001
From: Igor Gnatenko <i.gnatenko.brain@gmail.com>
Date: Fri, 30 Jan 2015 18:31:24 +0300
Subject: [PATCH] replace yum with librepo

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
---
 bodhi/util.py | 50 +++++++++++---------------------------------------
 1 file changed, 11 insertions(+), 39 deletions(-)

diff --git a/bodhi/util.py b/bodhi/util.py
index aa037f0..4bdc1c0 100644
--- a/bodhi/util.py
+++ b/bodhi/util.py
@@ -49,13 +49,6 @@ try:
 except ImportError:
     log.warning("Could not import 'rpm'")
 
-try:
-    import yum
-    import yum.misc
-except ImportError:
-    log.warning("Could not import 'yum'")
-
-
 _ = TranslationStringFactory('bodhi')
 
 ## Display a given message as a heading
@@ -231,12 +224,14 @@ class Singleton(object):
 def sanity_check_repodata(myurl):
     """
     Sanity check the repodata for a given repository.
-    Initial implementation by Seth Vidal.
     """
 
-    import urlgrabber
+    import librepo
+    h = librepo.Handle()
+    r = librepo.Result()
+    h.setopt(librepo.LRO_REPOTYPE, librepo.LR_YUMREPO)
+    h.setopt(librepo.LRO_DESTDIR, tempfile.mkdtemp())
 
-    tempdir = tempfile.mkdtemp()
     errorstrings = []
     if myurl[-1] != '/':
         myurl += '/'
@@ -246,36 +241,13 @@ def sanity_check_repodata(myurl):
     else:
         baseurl = baseurl.replace('repodata/', '/')
 
-    rf = myurl + 'repomd.xml'
+    h.setopt(librepo.LRO_URLS, [myurl])
+    h.setopt(librepo.LRO_CHECKSUM, True)
     try:
-        rm = urlgrabber.urlopen(rf)
-        repomd = yum.repoMDObject.RepoMD('foo', rm)
-        for t in repomd.fileTypes():
-            data = repomd.getData(t)
-            base, href = data.location
-            if base:
-                loc = base + '/' + href
-            else:
-                loc = baseurl + href
-
-            destfn = tempdir + '/' + os.path.basename(href)
-            dest = urlgrabber.urlgrab(loc, destfn)
-            ctype, known_csum = data.checksum
-            csum = yum.misc.checksum(ctype, dest)
-            if csum != known_csum:
-                errorstrings.append("checksum: %s" % t)
-
-            if href.find('xml') != -1:
-                retcode = subprocess.call(
-                    ['/usr/bin/xmllint', '--noout', dest])
-                if retcode != 0:
-                    errorstrings.append("failed xml read: %s" % t)
-
-    except urlgrabber.grabber.URLGrabError, e:
-        errorstrings.append('Error accessing repository %s' % e)
-
-    if errorstrings:
-        raise RepodataException(','.join(errorstrings))
+        h.perform()
+    except librepo.LibrepoException as e:
+        rc, msg, general_msg = e
+        raise RepodataException(msg)
 
     updateinfo = os.path.join(myurl, 'updateinfo.xml.gz')
     if os.path.exists(updateinfo):
-- 
2.2.2
```

I not tested it and not sure if it's correctly ;)

**Comment by ignatenkobrain** [comment]
btw this issue about switching to librepo instead of dnf I think.

**Comment by lmacken** [comment]
Nice, looks good so far. We've got a unit test for this method, and it's currently exploding when trying to fetch the local repodata.

```
ERROR: test_sanity_check (bodhi.tests.test_masher.TestMasher)                                                   
----------------------------------------------------------------------                                          
Traceback (most recent call last):                                                                              
  File "/home/lmacken/code/github.com/bodhi/bodhi/tests/test_masher.py", line 348, in test_sanity_check         
    t.sanity_check_repo()                                                                                       
  File "/home/lmacken/code/github.com/bodhi/bodhi/masher.py", line 545, in sanity_check_repo                    
    sanity_check_repodata(repodata)                                                                             
  File "/home/lmacken/code/github.com/bodhi/bodhi/util.py", line 252, in sanity_check_repodata                  
    raise RepodataException(msg)                                                                                
RepodataException: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried 
```

I tried prepending `file://` to the path, to no avail.

**Comment by lmacken** [comment]
I just submitted a pull request that removes the final dependency on the yum python module from bodhi: https://github.com/fedora-infra/bodhi/pull/127

**Comment by ignatenkobrain** [comment]
@lmacken great. Thank you! I think we should close this issue ;)

**Comment by lmacken** [comment]
Done! Thanks for your help @ignatenkobrain! :beers:
