### ISSUE TITLE
The ```date_testing``` field became ```NULL``` when an update was in testing

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1259]
Somehow the date_testing field on an Update became ```NULL``` in this update, and now the page is an HTTP 500:

https://bodhi.fedoraproject.org/updates/python-paramiko-2.1.1-2.fc24

I do not know how the field became ```NULL```, but we should either figure out what made it so and fix that, or guard against it being so.

Here is the traceback:

```
500 Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "master_html", line 239, in render_body
  File "/usr/lib/python2.7/site-packages/bodhi/server/templates/update.html", line 490, in render_body
    % if update.days_to_stable and update.status.description == 'testing':
  File "/usr/lib/python2.7/site-packages/bodhi/server/models/models.py", line 1839, in days_to_stable
    (datetime.utcnow() - self.date_testing).days)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

**Comment by bowlofeggs** [comment]
I have not observed this problem since then, so I will close this.
