### ISSUE TITLE
Bodhi is not compatible with pillow 4.0

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1262]
When attempting to build a Bodhi 2.4.0 beta today, I found that the Bodhi tests fail on Rawhide due to an incompatibility with the new pillow library version that Rawhide has. To reproduce, you can install the Rawhide version of pillow in the Vagrant development environment and run the tests:

```
$ sudo dnf install fedora-repos-rawhide
$ sudo dnf upgrade python2-pillow --enablerepo rawhide
$ btest | grep bowlofgrepsthatjustshowtheerrrosforthisbugreport
======================================================================
ERROR: Test the jpeg_generator with default settings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/bodhi/bodhi/tests/server/test_captcha.py", line 30, in test_with_defaults
    img = captcha.jpeg_generator('42 + 7', {})
  File "/home/vagrant/bodhi/bodhi/server/captcha.py", line 65, in jpeg_generator
    img.paste(background_color)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1319, in paste
    "cannot determine region size; use 4-item box"
ValueError: cannot determine region size; use 4-item box

======================================================================
ERROR: Test the generator with heavy mocking so we can make sure all the right calls were made.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/vagrant/bodhi/bodhi/tests/server/test_captcha.py", line 53, in test_with_heavy_mocking
    img = captcha.jpeg_generator('42 + 7', settings)
  File "/home/vagrant/bodhi/bodhi/server/captcha.py", line 65, in jpeg_generator
    img.paste(background_color)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1319, in paste
    "cannot determine region size; use 4-item box"
ValueError: cannot determine region size; use 4-item box

======================================================================
ERROR: Test the generator with specified dimensions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/bodhi/bodhi/tests/server/test_captcha.py", line 73, in test_with_specified_parameters
    img = captcha.jpeg_generator('42 + 7', settings)
  File "/home/vagrant/bodhi/bodhi/server/captcha.py", line 65, in jpeg_generator
    img.paste(background_color)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1319, in paste
    "cannot determine region size; use 4-item box"
ValueError: cannot determine region size; use 4-item box
```

**Comment by bowlofeggs** [comment]
Here is the changelog: https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst

**Comment by bowlofeggs** [comment]
This changelog entry sounds relevant: "Changed behaviour of default box argument for paste method to match docs #2211 [radarhere]":

https://github.com/python-pillow/Pillow/pull/2211
