### ISSUE TITLE
Some unit tests fail in EL 7 due to the way ```file``` is mocked

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1268]
Some of our tests fail while building Bodhi for EPEL 7 due to the way ```file``` is mocked:

```
======================================================================
ERROR: Test correct operation when there are some locked updates.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'bodhi.server.push' from '/builddir/build/BUILD/bodhi-6a0a0ff8eafda220ae4d1fc4a560ffe1de2889d8/bodhi/server/push.py'> does not have the attribute 'file'
-------------------- >> begin captured logging << --------------------
bodhi.server: DEBUG: Creating all models for Engine(sqlite://)
txn.139783895865152: DEBUG: new transaction
bodhi.server: DEBUG: Setting alias for bodhi-2.0-1.fc17 to FEDORA-2017-a3bbe1a8f2
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Test correct operation when there are some locked updates that aren't in a push.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'bodhi.server.push' from '/builddir/build/BUILD/bodhi-6a0a0ff8eafda220ae4d1fc4a560ffe1de2889d8/bodhi/server/push.py'> does not have the attribute 'file'
-------------------- >> begin captured logging << --------------------
bodhi.server: DEBUG: Creating all models for Engine(sqlite://)
txn.139783895865152: DEBUG: new transaction
bodhi.server: DEBUG: Setting alias for bodhi-2.0-1.fc17 to FEDORA-2017-a3bbe1a8f2
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Test correct operation when the --resume flag is given.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'bodhi.server.push' from '/builddir/build/BUILD/bodhi-6a0a0ff8eafda220ae4d1fc4a560ffe1de2889d8/bodhi/server/push.py'> does not have the attribute 'file'
-------------------- >> begin captured logging << --------------------
bodhi.server: DEBUG: Creating all models for Engine(sqlite://)
txn.139783895865152: DEBUG: new transaction
bodhi.server: DEBUG: Setting alias for bodhi-2.0-1.fc17 to FEDORA-2017-a3bbe1a8f2
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Test correct operation when the --resume flag is given but the human says they don't want to
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'bodhi.server.push' from '/builddir/build/BUILD/bodhi-6a0a0ff8eafda220ae4d1fc4a560ffe1de2889d8/bodhi/server/push.py'> does not have the attribute 'file'
-------------------- >> begin captured logging << --------------------
bodhi.server: DEBUG: Creating all models for Engine(sqlite://)
txn.139783895865152: DEBUG: new transaction
bodhi.server: DEBUG: Setting alias for bodhi-2.0-1.fc17 to FEDORA-2017-a3bbe1a8f2
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Test correct operation when the --staging flag is given. The main thing that matters is that
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'bodhi.server.push' from '/builddir/build/BUILD/bodhi-6a0a0ff8eafda220ae4d1fc4a560ffe1de2889d8/bodhi/server/push.py'> does not have the attribute 'file'
```

**Comment by jeremycline** [comment]
I neglected to add the ``fixes #1268`` to my commit message :(

This was fixed by https://github.com/fedora-infra/bodhi/pull/1275
