### ISSUE TITLE
A heavily mocked test on PIL is upset on EPEL 7

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1271]
This test is failing when we run it during the EPEL 7 build downstream:

```
======================================================================
FAIL: Test the generator with heavy mocking so we can make sure all the right calls were made.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/builddir/build/BUILD/bodhi-6a0a0ff8eafda220ae4d1fc4a560ffe1de2889d8/bodhi/tests/server/test_captcha.py", line 57, in test_with_heavy_mocking
    Draw.assert_called_once_with(img)
  File "/usr/lib/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: Draw(<PIL.Image.Image image mode=RGB size=1920x1080 at 0x7D150B00>)
Actual call: Draw(<PIL.Image.Image image mode=RGB size=1920x1080 at 0x54E0C560>)
```

**Comment by jeremycline** [comment]
My suspicion is that this has to do with the dropped call to ``paste`` in #1265, but I'm not certain because it passes in F25
