### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'req_params'

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/bodhi#1300]
I ran this command and get the following error

```
$ bodhi -u cqi --my-overrides
No handlers could be found for logger "fedora.client.bodhi"
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 451, in main
    }, auth=True)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 240, in send_request
    output = func(method, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 78, in _decorator
    output = func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 195, in _authed_post
    response = self._session.post(url, params=params, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
TypeError: request() got an unexpected keyword argument 'req_params'
```

``bodhi-client-0.9.12.2-5.fc24.noarch``

**Comment by bowlofeggs** [comment]
Thank you for the bug report @tkdchen!

Unfortunately, I am not able to support the bodhi 0.9 codebase as I am not familiar with it and am spread a bit thin just with maintaining Bodhi 2. Bodhi 2 is a complete rewrite of the Bodhi client so the code is not similar. Therefore I am sorry to say that I will close this bug.

There is a downstream bug report about this issue where I offered a few options. You can follow that discussion here:

https://bugzilla.redhat.com/show_bug.cgi?id=1278742#c8

**Comment by tkdchen** [comment]
Oh, thank you for this update. :)
