### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u010d' in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by srakitnican** [fedora-infra/bodhi#1332]
Typing unicode character into search box gives "500 Server Error".

    Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode as_unicode=True) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render **_kwargs_for_callable(callable_, data)) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 239, in render_body File "/usr/lib/python2.7/site-packages/bodhi/server/templates/updates.html", line 24, in render_body ${self.pager.render(page, pages)} File "pager_html", line 83, in render_render File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 499, in page_url return request.path_url + "?" + urllib.urlencode(params) File "/usr/lib64/python2.7/urllib.py", line 1326, in urlencode v = quote_plus(str(v)) UnicodeEncodeError: 'ascii' codec can't encode character u'\u010d' in position 5: ordinal not in range(128)

**Comment by bowlofeggs** [comment]
hahah that's great. I can confirm this problem - you can't search for ☺.

**Comment by sebwoj** [comment]
How to reproduce it?

**Comment by bowlofeggs** [comment]
Actually, this might be fixed since we switched to Python 3:

https://bodhi.fedoraproject.org/updates/?search=%E2%98%BA seems to work now.
