### ISSUE TITLE
Bodhi polls wrong master repo URL for alternative arches during mash

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1343]
Last night's Fedora 26 mash failed with this traceback:

```
[2017-03-10 09:54:58][    fedmsg    INFO]f26-updates-testing Polling http://download01.phx2.fedoraproject.org/pub/fedora/linux/updates/testing/26/aarch64/repodata/r

[2017-03-10 09:54:58][    fedmsg   ERROR]f26-updates-testing Error fetching repomd.xml
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 772, in wait_for_sync
    masterrepomd = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) 
HTTPError: HTTP Error 404: Not Found
```

The issue is that Bodhi is polling the wrong URL to find out when the ```repomd.xml``` file has been synchronized to the master mirror for ```aarch64```, so the URL listed in the above log is a 404. It should be looking here instead:

http://download01.phx2.fedoraproject.org/pub/fedora-secondary/updates/testing/26/aarch64/repodata/repomd.xml

Bodhi doesn't have any concept of primary and alternative architectures currently, but it's going to need to have some way to express which architectures are primary and alternative per release. Starting with Fedora 26, there are quite a few alternative architectures that are now handled by Bodhi, and ```i386``` has been switched from primary to alternative in this release as well.

We will need to add settings to production.ini for alternative arch mirror locations, and we will need to provide some way to express which architectures are primary vs. alternative.

**Comment by bowlofeggs** [comment]
The [following patch](http://pkgs.fedoraproject.org/cgit/rpms/bodhi.git/commit/?id=badf506c5efc381c2f47ddc1ddc9401da1649a7b) has been applied to production to workaround this issue:

```
From 72b062de6687502a9cd9498e70d2cd6c084527d0 Mon Sep 17 00:00:00 2001
From: Randy Barlow <randy@electronsweatshop.com>
Date: Fri, 10 Mar 2017 15:11:10 -0500
Subject: [PATCH] Hard code wait_for_sync() to look for x86_64.

---
 bodhi/server/consumers/masher.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/bodhi/server/consumers/masher.py b/bodhi/server/consumers/masher.py
index 38e1eec3..978963fb 100644
--- a/bodhi/server/consumers/masher.py
+++ b/bodhi/server/consumers/masher.py
@@ -750,7 +750,7 @@ class MasherThread(threading.Thread):
             force=True,
         )
         mash_path = os.path.join(self.path, self.id)
-        arch = os.listdir(mash_path)[0]
+        arch = 'x86_64'
 
         release = self.release.id_prefix.lower().replace('-', '_')
         request = self.request.value
-- 
2.12.0
```
