### ISSUE TITLE
tracefrom from --list-overrides

### ISSUE THREAD

**Issue by kaie** [fedora-infra/bodhi#1389]
$ bodhi --list-overrides
No handlers could be found for logger "fedora.client.bodhi"
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 451, in main
    }, auth=True)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 240, in send_request
    output = func(method, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 78, in _decorator
    output = func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 195, in _authed_post
    response = self._session.post(url, params=params, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
TypeError: request() got an unexpected keyword argument 'req_params'

**Comment by bowlofeggs** [comment]
Hello @kaie, and thanks for the bug report!

It looks like you are using bodhi-0.9. Unfortunately, I am unable to put much time into maintaining bodhi-0.9 because I've actually never seen the codebase and Bodhi 2 is enough work to keep me busy. Thus, I tend to use GitHub issues to track the current upstream versions of Bodhi (2.4 and 2.5), and I use Bugzilla to track problems with the older versions of Bodhi that I am not familiar with. I know this is confusing, but with very limited time it's the best I can do.

This issue has been reported in Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1278742

As I mentioned in a comment there, it is possible to get the newer version of Bodhi for Fedora 24 and 25 from Copr if you so choose, but beware that it is not backwards compatible, and is actually not quite feature equivalent yet either.
