### ISSUE TITLE
Malformed update files cause a traceback in the Bodhi CLI

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1415]
The bodhi CLI accepts a template file that can be used to specify all the arguments for an update. This is how ```fedpkg update``` works. If the template doesn't properly parse due to a syntax error, the bodhi CLI will blow up with a traceback instead of a nice error message:

```

Traceback (most recent call last):
  File "/usr/bin/bodhi", line 11, in <module>
    load_entry_point('bodhi-client==2.5.0', 'console_scripts', 'bodhi')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 108, in new
    updates = client.parse_file(os.path.abspath(kwargs['file']))
  File "/usr/lib/python2.7/site-packages/bodhi/client/bindings.py", line 336, in parse_file
    read = config.read(input_file)
  File "/usr/lib64/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: /home/vondruch/fedora-scm/others/rubygem-pcaprub/bodhi.template
```

We should handle that error better so the user gets a nice informative error message.

Vít Ondruch originally [reported this issue](https://bugzilla.redhat.com/show_bug.cgi?id=1315360).

**Comment by voxik** [comment]
BTW if the template was improved to provide some example of multiline notes, that would reduce the parsing issues (at least on my side ;) )

**Comment by bowlofeggs** [comment]
@voxik The template is coming from fedpkg:

https://pagure.io/fedpkg/blob/1.28/f/fedpkg/cli.py#_98

The template is an INI file, and as far as I know there is not a way to express newlines in INI files. We could modify Bodhi so that it can accept a new format (perhaps [toml](https://github.com/toml-lang/toml)) in addition to INI that does accept new lines. If you are interested in that as a feature, please feel free to file a new Bodhi issue about it. We would also need fedpkg to change its template once Bodhi can do it, of course.

**Comment by voxik** [comment]
https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

> Values can also span multiple lines, as long as they are indented deeper than the first line of the value. Depending on the parser’s mode, blank lines may be treated as parts of multiline values or ignored.

~~~
[Multiline Values]
chorus: I'm a lumberjack, and I'm okay
    I sleep all night and I work all day
~~~

**Comment by bowlofeggs** [comment]
@voxik I stand corrected! I tried it and it works too.

I suggest filing an RFE (or a pull request!) with fedpkg to add that example:

https://pagure.io/fedpkg

**Comment by voxik** [comment]
Good suggestion. Did that:

https://pagure.io/fedpkg/issue/123
