### ISSUE TITLE
Bodhi sometimes puts too much text in the Bugzilla Fixed in Version field

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1430]
bodhi-backend01 emitted an error e-mail yesterday due to putting too much text into the Fixed in Version field in Bugzilla:

```
Message
-------
[2017-04-10 21:20:21][     bodhi   ERROR]
python
Unable to close bug #1246113
```

Process Details
---------------
- host:     bodhi-backend01.phx2.fedoraproject.org
- PID:      64964
- name:     fedmsg-hub
- command:  /usr/bin/python /usr/bin/fedmsg-hub
- msg_id:   

Callstack that lead to the logging statement
--------------------------------------------
```
python
  File "/usr/lib64/python2.7/threading.py", line 777 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 804 in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 260 in run
    self.work()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 351 in work
    self.modify_bugs()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 57 in wrapper
    retval = method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 811 in modify_bugs
    update.modify_bugs()
  File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 1373 in modify_bugs
    bug.close_bug(self)
  File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 2232 in close_bug
    bugs.bugtracker.close(self.bug_id, versions=versions, comment=self.default_message(update))
  File "/usr/lib/python2.7/site-packages/bodhi/server/bugs.py", line 145 in close
    log.exception("Unable to close bug #%d" % bug_id)

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/server/bugs.py", line 143, in close
    bug.close('ERRATA', **args)
  File "/usr/lib/python2.7/site-packages/bugzilla/bug.py", line 219, in close
    return self.bugzilla.update_bugs(self.bug_id, vals)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1264, in update_bugs
    return self._proxy.Bug.update(tmp)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 259, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 245, in _request_helper
    raise sys.exc_info()[1]
Fault: <Fault 104: 'The text you entered in the Fixed In Version field is too long (259 characters, above the maximum length allowed of 255 characters).'>
```

We should check for this max length, and probably should just leave off some NVRs if we are exceeding the length.

**Comment by jwnx** [comment]
Hey @bowlofeggs ! Should this verification be made in the Masher or in Models? (:

**Comment by bowlofeggs** [comment]
Hi @jwnx,

I think this is probably the right place to fix it, so it will be fixed no matter what part of Bodhi uses it:

https://github.com/fedora-infra/bodhi/blob/2.8.1/bodhi/server/bugs.py#L133-L147

**Comment by jwnx** [comment]
I see. Thanks, @bowlofeggs !

Since you suggested to leave some NVRs, my first thought was to check if the adittion of a new version would break the 255 character mark and leave it off if it would. But there is a statement in the code for how this field should be formatted, so maybe there is a preference for inclusion of some NVRs.

Do you think we need a more speciffic rule or the 'over 255' is sufficient? (:

**Comment by bowlofeggs** [comment]
@jwnx I think just putting as many complete NVRs as we can fit while staying under 256 chars will do.
