### ISSUE TITLE
The bodhi CLI is unable to comment on updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1503]
```
[vagrant@bodhi-dev bodhi]$ bodhi updates comment bodhi-2.6.1-1.fc26 text1 --user bowlofeggs
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib64/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/paste': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/moksha': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/repoze': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
Password: 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 9, in <module>
    load_entry_point('bodhi-client', 'console_scripts', 'bodhi')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/bodhi/bodhi/client/__init__.py", line 334, in comment
    resp = client.comment(update, text, karma)
  File "/home/vagrant/bodhi/bodhi/client/bindings.py", line 80, in wrapper
    raise BodhiClientException(problems)
bodhi.client.bindings.BodhiClientException: You must provide a captcha_key.
```

This problem was also reported with the bodhi-0.9 client, so it may be a server-side issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1445703

**Comment by cverna** [comment]
Just tested this with bodhi 2.7.0 client in my local dev environment and it worked correctly. Can give it another try ?

**Comment by bowlofeggs** [comment]
@cverna Odd, it also seems to work for me now too. I guess we can close this issue. The downstream report should probably also be investigated, but we can track that there. Thanks for testing!
