### ISSUE TITLE
clicking on expire buildroot override when not logged in gives poor messaging

### ISSUE THREAD

**Issue by ausil** [fedora-infra/bodhi#1541]
if you try to expire a buildroot override when not logged in you end up with a message
"Override : Unable to save buildroot override: 'NoneType' object has no attribute 'name'" which is really confusing and gives no hint that its just that you are not logged in.  instread you should be redirected to login, or at the least be given a message that you are not logged in and to do so first

**Comment by bowlofeggs** [comment]
Agreed. For the record, this is the traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/server/services/overrides.py", line 186, in save_override
    submitter = User.get(request.user.name, request.db)
AttributeError: 'NoneType' object has no attribute 'name'
2017-05-22 18:15:10,726 INFO  [requests.packages.urllib3.connectionpool][Dummy-3] Starting new HTTPS connection (1): koji.fedoraproject.org
2017-05-22 18:15:11,179 ERROR [bodhi.server][Dummy-3] 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/server/services/overrides.py", line 186, in save_override
    submitter = User.get(request.user.name, request.db)
AttributeError: 'NoneType' object has no attribute 'name'
```
