### ISSUE TITLE
default vagrant env crashes with OOM during test suite

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1588]
After recent changes, it seems that 4G RAM is not enough for the vagrant VM:
```
======================================================================
ERROR: Enforce a linear alembic history.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/bodhi/bodhi/tests/server/test_alembic.py", line 40, in test_alembic_history
    cwd=REPO_PATH, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by bowlofeggs** [comment]
Cool, I'll just bump up the RAM by another GB for now. One of these days we really need to figure out why the tests use so much memory.
