### ISSUE TITLE
Test failures on Fedora 26

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1615]
Several tests fail when run on Fedora 26 with tracebacks like this:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 99, in tm_tween
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 75, in tm_tween
    t.setUser(userid, '')
  File "/usr/lib/python2.7/site-packages/transaction/_transaction.py", line 549, in setUser
    raise TypeError("User name must be text (unicode)")
TypeError: User name must be text (unicode)
```

I first discovered this when trying to build Bodhi in Koji. Curiously, the tests pass on Rawhide. It is possible to reproduce this with the Vagrant environment by setting these values in your Vagrantfile:

```
config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/development/26/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-26-20170614.n.1.x86_64.vagrant-libvirt.box"
config.vm.box = "f26-cloud-libvirt"
```

You will also have to remove python3-diff-cover from the dev playbook because that package was apparently retired in Fedora 26. I plan to pick it up when I get some air to breathe.

**Comment by bowlofeggs** [comment]
It seems that somewhere in the dependency stack, some code started disallowing text to be ```str``` objects, now requiring ```unicode``` objects.

**Comment by bowlofeggs** [comment]
Ah, we are hitting this bug:

https://github.com/Pylons/pyramid_tm/issues/49

**Comment by bowlofeggs** [comment]
I am fixing this in Fedora's python-pyramid-tm:

https://bugzilla.redhat.com/show_bug.cgi?id=1462252

However, we probably also don't need pyramid-tm in Bodhi since we don't use transaction anymore. I have filed #1616 about looking into that further. I will close this ticket once Fedora 26 is fixed.

**Comment by bowlofeggs** [comment]
This has been resolved by https://bodhi.fedoraproject.org/updates/FEDORA-2017-051fec84db
