### ISSUE TITLE
The new scm_url is experiencing uniqueness clashes

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1636]
Message
-------
[2017-06-21 06:28:28][    fedmsg   ERROR]
```python
{'body': {u'username': u'bodhi', u'certificate': u'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVUakNDQTdlZ0F3SUJBZ0lDQWdnd0RRWUpL\nb1pJaHZjTkFRRUZCUUF3Z2FBeEN6QUpCZ05WQkFZVEFsVlQKTVFzd0NRWURWUVFJRXdKT1F6RVFN\nQTRHQTFVRUJ4TUhVbUZzWldsbmFERVhNQlVHQTFVRUNoTU9SbVZrYjNKaApJRkJ5YjJwbFkzUXhE\nekFOQmdOVkJBc1RCbVpsWkcxelp6RVBNQTBHQTFVRUF4TUdabVZrYlhObk1ROHdEUVlEClZRUXBF\nd1ptWldSdGMyY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1UUdabFpHOXlZWEJ5YjJwbFkz\nUXUKYjNKbk1CNFhEVEUxTURjeU1URTVNVE15TTFvWERUSTFNRGN4T0RFNU1UTXlNMW93Z2R3eEN6\nQUpCZ05WQkFZVApBbFZUTVFzd0NRWURWUVFJRXdKT1F6RVFNQTRHQTFVRUJ4TUhVbUZzWldsbmFE\nRVhNQlVHQTFVRUNoTU9SbVZrCmIzSmhJRkJ5YjJwbFkzUXhEekFOQmdOVkJBc1RCbVpsWkcxelp6\nRXRNQ3NHQTFVRUF4TWtZbTlrYUdrdFltOWsKYUdrd015NXdhSGd5TG1abFpHOXlZWEJ5YjJwbFkz\nUXViM0puTVMwd0t3WURWUVFwRXlSaWIyUm9hUzFpYjJSbwphVEF6TG5Cb2VESXVabVZrYjNKaGNI\nSnZhbVZqZEM1dmNtY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1ClFHWmxaRzl5WVhCeWIy\ncGxZM1F1YjNKbk1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdRQ28KcjF1MmE3\nU20vcGhMMG5
 lZG9FZXNyUUZDRGZVYmMwdGt1bUowQlBiRHcxdzdtblp0MERVSjhrNkVXVFNwL25E\nNwpoK0NNMmRucG5lRm5XVllycDlXSGpSUVZEbzBCemE3MnJQRjEwcjhPb3phN3k3VTBFUlhmMkNy\nZnBxZTJzREpNCkFyWThZZnZVWnluemIwVUVzOFlmNkgrQ2h5S1JldGNXaWF1TTBZQU5zUUlEQVFB\nQm80SUJWekNDQVZNd0NRWUQKVlIwVEJBSXdBREF0QmdsZ2hrZ0JodmhDQVEwRUlCWWVSV0Z6ZVMx\nU1UwRWdSMlZ1WlhKaGRHVmtJRU5sY25ScApabWxqWVhSbE1CMEdBMVVkRGdRV0JCUmQyMWNBdnZJ\ncFlrQWlIR05nUmRpdHdMODZLVENCMVFZRFZSMGpCSUhOCk1JSEtnQlJyUUZyNUVnaUpXZWRaNVFY\nMUFoMEtUbjhVQUtHQnBxU0JvekNCb0RFTE1Ba0dBMVVFQmhNQ1ZWTXgKQ3pBSkJnTlZCQWdUQWs1\nRE1SQXdEZ1lEVlFRSEV3ZFNZV3hsYVdkb01SY3dGUVlEVlFRS0V3NUdaV1J2Y21FZwpVSEp2YW1W\namRERVBNQTBHQTFVRUN4TUdabVZrYlhObk1ROHdEUVlEVlFRREV3Wm1aV1J0YzJjeER6QU5CZ05W\nCkJDa1RCbVpsWkcxelp6RW1NQ1FHQ1NxR1NJYjNEUUVKQVJZWFlXUnRhVzVBWm1Wa2IzSmhjSEp2\nYW1WamRDNXYKY21lQ0NRRGpVQjVIVHhjZVJUQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFM\nQmdOVkhROEVCQU1DQjRBdwpEUVlKS29aSWh2Y05BUUVGQlFBRGdZRUFieTE3QVExbGhzckxuamZk\nWEhaWG9Kd2pWcVdTNHRudWZvVzFLK3pLCnZiTkdMNlBmQVZHa3Q5RzlENENpQzV6amlPNzdi
 Y2lX\nTkYzeWdUUjZqcmdoUnJOZmZnQ1MzSWFpT3JNemVnaHYKeWRqcXJqdDBDY3VoRXM3WFRndVlHcWoz\ndThxS3J6ZGVtNGxETm9wNENoZ0ZtS1ZUdk1pc3R4UVdIMEhCdDZkcApZYXM9Ci0tLS0tRU5EIENF\nUlRJRklDQVRFLS0tLS0K\n', u'i': 2, u'timestamp': 1498026496, u'msg_id': u'2017-474a26db-66cd-4ead-a471-4b17ad785d7f', u'crypto': u'x509', u'topic': u'org.fedoraproject.prod.bodhi.update.request.testing', u'signature': u'n1cNkpIcZWuO204fKM5L6garpVfH2NC9u5D/ckBxEm6bzm+XGpAsKy+hb3vBajP+C9ceaFjhC36D\npKk0wnhRepT6+CUcEHBZZ5PuMzrQYuWDu+uqVShUVt6fGeRpMwP4+OJBF3lDgkJG8I6KWY15stKq\nIQY1LeL+vXObZtj7eb4=\n', u'msg': {u'update': {u'date_testing': None, u'old_updateid': None, u'pushed': False, u'require_testcases': False, u'date_stable': None, u'critpath': False, u'date_approved': None, u'stable_karma': 3, u'date_pushed': None, u'requirements': u'', u'severity': u'low', u'autokarma': True, u'title': u'rpmdeplint-1.3-2.el7', u'suggest': u'unspecified', u'require_bugs': True, u'comments': [{u'bug_feedback': [], u'user_id': 91, u'timestamp'
 : u'2017-06-21 06:28:09', u'text': u'This update has been submitted for testing by dcallagh. ', u'karma_critpath': 0, u'update_id': 90541, u'karma': 0, u'anonymous': False, u'testcase_feedback': [], u'id': 625073, u'user': {u'openid': None, u'name': u'bodhi', u'show_popups': True, u'email': None, u'avatar': None, u'groups': [], u'id': 91}}], u'updateid': u'FEDORA-EPEL-2017-a16b07515f', u'test_cases': [], u'close_bugs': True, u'meets_testing_requirements': False, u'date_locked': None, u'date_submitted': u'2017-06-21 06:28:09', u'unstable_karma': -3, u'submitter': u'dcallagh', u'user': {u'openid': None, u'name': u'dcallagh', u'show_popups': True, u'email': u'dcallagh@redhat.com', u'avatar': None, u'groups': [{u'name': u'packager'}], u'id': 560}, u'content_type': u'rpm', u'locked': False, u'builds': [{u'nvr': u'rpmdeplint-1.3-2.el7', u'scm_url': None, u'epoch': 0, u'ci_url': None, u'signed': False, u'ci_status': None, u'type': u'rpm'}], u'date_modified': None, u'url': u'https://bodhi.f
 edoraproject.org/updates/FEDORA-EPEL-2017-a16b07515f', u'type': u'bugfix', u'notes': u'The main rpmdeplint package now has a versioned requirement on its python3-rpmdeplint package, to ensure they stay in sync (RHBZ#1462047)', u'request': u'testing', u'bugs': [{u'bug_id': 1462047, u'security': False, u'feedback': [], u'parent': False, u'title': None}], u'alias': u'FEDORA-EPEL-2017-a16b07515f', u'status': u'pending', u'karma': 0, u'release': {u'dist_tag': u'epel7', u'name': u'EPEL-7', u'testing_tag': u'epel7-testing', u'pending_stable_tag': u'epel7-pending', u'pending_signing_tag': u'epel7-signing-pending', u'long_name': u'Fedora EPEL 7', u'state': u'current', u'version': u'7', u'override_tag': u'epel7-override', u'branch': u'epel7', u'id_prefix': u'FEDORA-EPEL', u'pending_testing_tag': u'epel7-testing-pending', u'stable_tag': u'epel7', u'candidate_tag': u'epel7-testing-candidate'}}, u'agent': u'dcallagh'}}, 'topic': u'org.fedoraproject.prod.bodhi.update.request.testing'}
```

Process Details
---------------
- host:     bodhi-backend02.phx2.fedoraproject.org
- PID:      30534
- name:     fedmsg-hub
- command:  /usr/bin/python /usr/bin/fedmsg-hub
- msg_id:   

Callstack that lead to the logging statement
--------------------------------------------
```python
  File "/usr/lib64/python2.7/threading.py", line 784 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 167 in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118 in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81 in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 193 in _work
    self.log.exception(message)
```
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
    self.consume(message)
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/updates.py", line 131, in consume
    bugs = update.bugs
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 591, in get
    value = self.callable_(state, passive)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 534, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 603, in _emit_lazyload
    result = q.all()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2320, in all
    return list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    mapper, table, update)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 518, in _emit_update_statements
    execute(statement, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) duplicate key value violates unique constraint "uq_scm_url"
DETAIL:  Key (scm_url)=(git://pkgs.fedoraproject.org/rpms/rpmdeplint?#1576eda55ad974bb2557e357871acf7400e652da) already exists.
 'UPDATE builds SET scm_url=%(scm_url)s WHERE builds.id = %(builds_id)s' {'builds_id': 124253, 'scm_url': 'git://pkgs.fedoraproject.org/rpms/rpmdeplint?#1576eda55ad974bb2557e357871acf7400e652da'}
```

**Comment by bowlofeggs** [comment]
This hasn't happened in a while now. I'm not sure why it happened, but I'm going to close it for now. I'll reopen it if it returns.

**Comment by bowlofeggs** [comment]
This is still happening, and it's because the scm_url is not unique in Koji.
