### ISSUE TITLE
500 Server Error when enabling CI

### ISSUE THREAD

**Issue by matt8754** [fedora-infra/bodhi#1682]
If ci.required is set True, visiting one of the existing update will occur 500 Server Error

500 Server Error

Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode as_unicode=True) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render **_kwargs_for_callable(callable_, data)) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template callable_(context, *args, **kwargs) File "/home/vagrant/bodhi/bodhi/server/templates/master.html", line 185, in render_body ${self.body()} File "/home/vagrant/bodhi/bodhi/server/templates/update.html", line 700, in render_body ${self.util.ci_status2html(update.ci_status.description) | n} AttributeError: 'NoneType' object has no attribute 'description'

This is because the ci_status could be None and this case is not covered on the UI.

**Comment by pypingou** [comment]
I got the patch for this

**Comment by matt8754** [comment]
@pypingou , you are so quick, I was about to write a patch for this, :-)

**Comment by pypingou** [comment]
I had it from before, it was just laying on my git repo and I was reminding myself for a few days that I should submit it, you're just the trigger I needed :)

**Comment by matt8754** [comment]
Nice, 👍

**Comment by bowlofeggs** [comment]
In https://github.com/fedora-infra/bodhi/pull/1733 I am removing the ```ci.enabled``` setting. Thus, I believe we can close this and the associated PR.
