### ISSUE TITLE
bodhi-manage-releases should handle authentication errors instead of printing tracebacks

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1734]
Similar to the recent work done for the CLI in #1709, the ```bodhi-manage-releases``` tool should also catch authentication errors and print nice error messages for the user:

```
$ bodhi-manage-releases edit --name F24 --state archived
Password: 
Traceback (most recent call last):
  File "/usr/bin/bodhi-manage-releases", line 9, in <module>
    load_entry_point('bodhi-server==2.9.0', 'console_scripts', 'bodhi-manage-releases')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bodhi/server/scripts/manage_releases.py", line 134, in edit
    save(client, **data)
  File "/usr/lib/python2.7/site-packages/bodhi/server/scripts/manage_releases.py", line 163, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 246, in send_request
    raise AuthError()
fedora.client.AuthError
```

**Comment by sebwoj** [comment]
@bowlofeggs since implementation changed( #2424 ), and script is deprecated, can we close this?

**Comment by bowlofeggs** [comment]
@sebwoj Indeed, thanks!
