### ISSUE TITLE
Karma submissions trigger the error message "Comment : Unable to create comment" and then after a delay the comment is posted anyway

### ISSUE THREAD

**Issue by dhgutteridge** [fedora-infra/bodhi#1739]
This may be related to #717, but the behaviour is a bit different. I've submitted karma with a comment, received the notification "Comment : Unable to create comment" and then after a delay, my submission is actually posted anyway. This confusing message and lag in posting leads to double submissions, e.g. [https://bodhi.fedoraproject.org/updates/FEDORA-2017-401c8792f5](https://bodhi.fedoraproject.org/updates/FEDORA-2017-401c8792f5). (In that example, i received the "Comment : Unable to create comment" error message on both attempted posts.)

**Comment by dhgutteridge** [comment]
Further issues with the same sample update: no emails were sent by Bodhi concerning the karma I'd submitted. More surprisingly, it has reached the +3 karma threshold and has autopush enabled, but it's been twelve hours and it still hasn't submitted the update to stable.

(On reflection, I think this is probably unrelated to #717, as it's rather different. There isn't a delay because an update is locked here. And with this issue, comments are posted within about two minutes of submission, not after significant delay.)

**Comment by dhgutteridge** [comment]
Another follow-up: the example update required +3 karma, but it didn't submit to stable at +3. It did so at +4, after another user added feedback. Something got very out of sync there.

**Comment by bowlofeggs** [comment]
I believe this was due to a hiccup in communicating with Koji:

```
[Thu Aug 10 01:08:16.150984 2017] [:error] [pid 2365] 2017-08-10 01:08:16,150 ERROR [bodhi.server][MainThread] Unhandled exception raised:  <HTTPFound at 0x7fc137d55f50 302 Found>
[Thu Aug 10 01:08:16.151017 2017] [:error] [pid 2365] None
[Thu Aug 10 01:14:54.204194 2017] [:error] [pid 2364] 2017-08-10 01:14:54,203 DEBUG [bodhi.server][Dummy-1] Ignoring duplicate 1 karma from dhgutteridge on hplip-3.17.6-1.fc26
[Thu Aug 10 01:14:54.204500 2017] [:error] [pid 2364] 2017-08-10 01:14:54,204 INFO  [bodhi.server][Dummy-1] Updated hplip-3.17.6-1.fc26 karma to 3
[Thu Aug 10 01:14:54.204909 2017] [:error] [pid 2364] 2017-08-10 01:14:54,204 INFO  [bodhi.server][Dummy-1] Automatically marking hplip-3.17.6-1.fc26 as stable
[Thu Aug 10 01:14:54.205056 2017] [:error] [pid 2364] 2017-08-10 01:14:54,204 DEBUG [bodhi.server][Dummy-1] Attempting to set request <stable>
[Thu Aug 10 01:14:54.205312 2017] [:error] [pid 2364] 2017-08-10 01:14:54,205 DEBUG [bodhi.server][Dummy-1] hplip-3.17.6-1.fc26 meets stable karma requirements
[Thu Aug 10 01:14:54.205472 2017] [:error] [pid 2364] 2017-08-10 01:14:54,205 DEBUG [bodhi.server][Dummy-1] Adding tag f26-updates-pending to hplip-3.17.6-1.fc26
[Thu Aug 10 01:15:02.327818 2017] [:error] [pid 2364] 2017-08-10 01:15:02,215 ERROR [bodhi.server][Dummy-1] (11, 'Resource temporarily unavailable')
[Thu Aug 10 01:15:02.329717 2017] [:error] [pid 2364] Traceback (most recent call last):
[Thu Aug 10 01:15:02.336598 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/services/comments.py", line 223, in new_comment
[Thu Aug 10 01:15:02.336620 2017] [:error] [pid 2364]     session=request.db, author=author, anonymous=anonymous, **data)
[Thu Aug 10 01:15:02.340905 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 2134, in comment
[Thu Aug 10 01:15:02.340940 2017] [:error] [pid 2364]     self.check_karma_thresholds(session, u'bodhi')
[Thu Aug 10 01:15:02.340945 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 2377, in check_karma_thresholds
[Thu Aug 10 01:15:02.341568 2017] [:error] [pid 2364]     self.set_request(db, UpdateRequest.stable, agent)
[Thu Aug 10 01:15:02.341583 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 1805, in set_request
[Thu Aug 10 01:15:02.341631 2017] [:error] [pid 2364]     self.add_tag(self.release.pending_stable_tag)
[Thu Aug 10 01:15:02.342868 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 1833, in add_tag
[Thu Aug 10 01:15:02.352573 2017] [:error] [pid 2364]     koji = buildsys.get_session()
[Thu Aug 10 01:15:02.352597 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/buildsys.py", line 416, in get_session
[Thu Aug 10 01:15:02.364647 2017] [:error] [pid 2364]     return _buildsystem()
[Thu Aug 10 01:15:02.364702 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/buildsys.py", line 439, in get_koji_login
[Thu Aug 10 01:15:02.364708 2017] [:error] [pid 2364]     return koji_login(config=settings)
[Thu Aug 10 01:15:02.364711 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/bodhi/server/buildsys.py", line 390, in koji_login
[Thu Aug 10 01:15:02.365416 2017] [:error] [pid 2364]     if not koji_client.krb_login(**get_krb_conf(config)):
[Thu Aug 10 01:15:02.365425 2017] [:error] [pid 2364]   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2124, in krb_login
[Thu Aug 10 01:15:02.365429 2017] [:error] [pid 2364]     ccache.init_creds_keytab(principal=cprinc, keytab=keytab)
[Thu Aug 10 01:15:02.369782 2017] [:error] [pid 2364] Krb5Error: (11, 'Resource temporarily unavailable')
```

There's not much we could do about that other than to improve error handling and messaging when things like this happen. I'm going to keep this open as a reliability improvement issue.

Thanks for the report!
