### ISSUE TITLE
bodhi.client.bindings.BodhiClientException: You must provide a captcha_key.

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1787]
I hit this traceback today:

```
bodhi updates comment --karma 1 vim-8.0.1030-1.fc26 "LGTM"
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 11, in <module>
    load_entry_point('bodhi-client==2.8.1', 'console_scripts', 'bodhi')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 336, in comment
    resp = client.comment(update, text, karma)
  File "/usr/lib/python2.7/site-packages/bodhi/client/bindings.py", line 97, in wrapper
    raise BodhiClientException(problems)
bodhi.client.bindings.BodhiClientException: You must provide a captcha_key.
```

We need [```bodhi.client.bindings.errorhandled```](https://github.com/fedora-infra/bodhi/blob/2.10.1/bodhi/client/bindings.py#L70-L102) to catch this problem and retry when it is present, similarly to how it does for ```AuthError```.

**Comment by bowlofeggs** [comment]
This patch is included in the bodhi-3.1.0-0.1.beta, which is deployed to [staging](https://bodhi.stg.fedoraproject.org/) and is also available via [Copr](https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/).
