### ISSUE TITLE
Demonstrate modular bodhi in staging

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#1795]
Emergency item from [the FESCo meeting today](https://meetbot.fedoraproject.org/fedora-meeting/2017-09-08/fesco.2017-09-08-16.00.html).  We need to demonstrate Bodhi working with modules in staging or risk slipping modular server from the f27 release.

I'm going to use this ticket to track work items.

- [x] Email infra list to raise awareness about this work.  [done](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/M2VVVO3CVLECU7CWRS6UBAHLZ23LTC6M/).
- [x] See if I can get unmodified bodhi to do a mash in staging.  I hear this is hard.  **Update** this works!  See comment below for a paste of the mash log.
  - [x] OK, first problem is that the prod vol doesn't have signed rpms in the place where they're expected... and there are a lot.  I may try to create a "Fedora 2000" release in bodhi and set up some tags with a single rpm in them.  Something simple to mash.  I'll still need even that one rpm signed.  Maybe I can find one that's already in another tag.  Done at https://bodhi.stg.fedoraproject.org/updates/python-libcloud-2.0.0-1.fc24
  - [X] Arg!  Switching to using python-libcloud-2.0.0-1.fc26 because the other build is *deleted* in the prod volume.  Done at https://bodhi.stg.fedoraproject.org/updates/python-libcloud-2.0.0-1.fc26
- [X] @bowlofeggs needs to fix #1793, see #1801.
- [ ] @mcurlej needs to fix the updateinfo.xml bug.
- [ ] Rebase the patches from #1697 and #1793 onto a release/hotfix branch and cut an rpm.
- [ ] Try upgrading in staging.
- [ ] Try downgrading in staging.
- [ ] See if the unmodified bodhi can still mash.
- [ ] Try upgrading again.
- [ ] Demonstrate a *modular* mash as well as is possible in staging.  Failing this, if upgrade/downgrade works.
- ~~Email infra list asking for generic FBR for prod.~~
  - We no longer need to do this with an FBR since server sig has scaled back the modular release in [this meeting](https://meetbot.fedoraproject.org/fedora-meeting-1/2017-09-12/serversig.2017-09-12-20.00.html).

**Comment by bowlofeggs** [comment]
Don't forget https://github.com/fedora-infra/bodhi/issues/1793. I suspect that Martin's patch alone might not be enough to mash modules. I still volunteer to fix #1793 - it's high on my task warrior list.

**Comment by ralphbean** [comment]
OK - I got a basic mash of "fedora 2000" with a single python-libcloud build in:

```python
Sep 11 19:25:02 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:02][    fedmsg    INFO]f2000-updates-testing Running post-request actions on updates
Sep 11 19:25:02 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:02][    fedmsg    INFO]f2000-updates-testing Generating testing digest for F2000
Sep 11 19:25:03 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:03][    fedmsg    INFO]f2000-updates-testing Mashing f2000-updates-testing
Sep 11 19:25:03 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:03][bodhi.server    INFO]f2000-updates-testing Running ['mash', '-o', '/var/cache/bodhi/mashing/f2000-updates-testing-170911.1922', '-c', '/etc/bodhi/mash.conf', '-f', '/var/cache/bodhi/comps/comps-f2000.xml', 'f2000-updates-testing']
Sep 11 19:25:03 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:03][bodhi.server    INFO]f2000-updates-testing Asking <koji.ClientSession object at 0x7fe724439c50> about rpm headers for u'python-libcloud-2.0.0-1.fc26.src' ['name', 'summary', 'version', 'release', 'url', 'description', 'changelogtime', 'changelogname', 'changelogtext']
Sep 11 19:25:04 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:04][    fedmsg    INFO]f2000-updates-testing Testing digest generation for F2000 complete
Sep 11 19:25:04 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:04][    fedmsg    INFO]f2000-updates-testing Generating updateinfo for F2000
Sep 11 19:25:05 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:05][bodhi.server.metadata    INFO]f2000-updates-testing Generating new updateinfo.xml
Sep 11 19:25:06 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:06][    fedmsg    INFO]f2000-updates-testing Updateinfo generation for F2000 complete
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg    INFO]f2000-updates-testing Took 7.07723593712 seconds to mash f2000-updates-testing
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg    INFO]f2000-updates-testing Masher lock saved: /var/cache/bodhi/mashing/MASHING-f2000-updates-testing
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/armhfp/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/SRPMS/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/i386/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/ppc64/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/ppc64le/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/x86_64/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing Inserting /tmp/tmpgYmqlx into /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/aarch64/repodata
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][bodhi.server.metadata    INFO]f2000-updates-testing /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing/armhfp/repodata cached to /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/../f2000-updates-testing.repocache/repodata/
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg    INFO]f2000-updates-testing Running sanity checks on /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922/f2000-updates-testing
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg    INFO]f2000-updates-testing Creating symlink: /var/cache/bodhi/mashing/f2000-updates-testing-170911.1922 => /var/cache/bodhi/mashed/f2000-updates-testing
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg    INFO]f2000-updates-testing Waiting for updates to hit the master mirror
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg    INFO]f2000-updates-testing Polling http://download01.phx2.fedoraproject.org/pub/fedora/linux/updates/testing/2000/armhfp/repodata/repomd.xml
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: [2017-09-11 19:25:10][    fedmsg   ERROR]f2000-updates-testing Error fetching repomd.xml
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: Traceback (most recent call last):
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 767, in wait_for_sync
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     self.log.info('Polling %s' % master_repomd_url)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     return opener.open(url, data, timeout)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib64/python2.7/urllib2.py", line 435, in open
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     response = meth(req, response)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     'http', request, response, code, msg, hdrs)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib64/python2.7/urllib2.py", line 473, in error
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     return self._call_chain(*args)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     result = func(*args)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:   File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Sep 11 19:25:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[9092]: HTTPError: HTTP Error 404: Not Found
```

The traceback at the end is expected.  There should be no mirror syncing in stg.

**Comment by ralphbean** [comment]
Done with https://bodhi.stg.fedoraproject.org/updates/FEDORA-2017-b32d96e2db
