### ISSUE TITLE
The metrics page is an HTTP 500 right now

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1981]
https://bodhi.fedoraproject.org/metrics simply says "500 Server Error
'NoneType' object has no attribute 'groups'" right now. Here is the traceback from the server logs:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 99, in tm_tween
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 80, in tm_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/usr/lib/python2.7/site-packages/bodhi/server/views/metrics.py", line 85, in metrics
    data, ticks = compute_ticks_and_data(db, releases, update_types)
  File "/usr/lib/python2.7/site-packages/bodhi/server/views/metrics.py", line 42, in compute_ticks_and_data
    releases = sorted(releases, cmp=lambda x, y:
  File "/usr/lib/python2.7/site-packages/bodhi/server/views/metrics.py", line 43, in <lambda>
    cmp(int(x.version_int), int(y.version_int)))
  File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 486, in version_int
    return int(regex.match(self.name).groups()[0])
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by sebwoj** [comment]
@bowlofeggs could you try to open https://bodhi.fedoraproject.org/metrics once again?

**Comment by bowlofeggs** [comment]
Hmm, it does seem to work. Thanks for checking!
