### ISSUE TITLE
Client crash when submitting multiple BuildrootOverrides in one call

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2031]
Mamoru TASAKA [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1513836) to Red Hat Bugzilla that the Bodhi client crashes when a list of BuildrootOverrides are created in one call.

> Description of problem:
> Submitting override with multiple packages at once causes bodhi crash
> (although the override seems to be registered anyway)
> 
> 
> Version-Release number of selected component (if applicable):
> bodhi-client-2.12.2-2.fc27
> 
> How reproducible:
> 100%
> 
> Steps to Reproduce:
> 1. See below
> 2.
> 3.
> 
> Actual results:
> [mtasaka@localhost fedora-specific]$ bodhi overrides save --user mtasaka --duration 4 --notes "ruby-gnome2 3.2.0 suite stage 2" "rubygem-gobject-introspection-3.2.0-1.fc27 rubygem-cairo-gobject-3.2.0-1.fc27"
> mtasaka's rubygem-gobject-introspection-3.2.0-1.fc27 override (expires 2017-11-20 04:53:57)
> mtasaka's rubygem-cairo-gobject-3.2.0-1.fc27 override (expires 2017-11-20 04:53:57)
> Traceback (most recent call last):
>   File "/bin/bodhi", line 11, in <module>
>     load_entry_point('bodhi-client==2.12.2', 'console_scripts', 'bodhi')()
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 111, in wrapper
>     method(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 600, in save_buildroot_overrides
>     _save_override(url=url, user=user, password=password, staging=staging, **kwargs)
>   File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 141, in _save_override
>     print_resp(resp, client)
>   File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 658, in print_resp
>     '%s overrides found (%d shown)' % (resp.total, len(resp.overrides)))
>   File "/usr/lib/python2.7/site-packages/munch/__init__.py", line 103, in __getattr__
>     raise AttributeError(k)
> AttributeError: total

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in Bodhi 3.13: #2917.

**Comment by bowlofeggs** [comment]
This fix is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Comment by bowlofeggs** [comment]
Bodhi 3.13.0 has been released:

https://github.com/fedora-infra/bodhi/releases/tag/3.13.0

Fedora Infrastructure plans to deploy it to production on Monday.
