### ISSUE TITLE
can't submit updates to epel7 repo

### ISSUE THREAD

**Issue by NiceandGently** [fedora-infra/bodhi#218]
I can't submit mate-polkit-1.10.0-2.el7 to epel7 repo.
I see the notification 'mate-polkit-1.10.0-2.el7 will be submitted', but i don't see the sucess notification. And the site stays there after the logo stops rotating.

**Comment by NiceandGently** [comment]
another example from command line:
```
[rave@mother mate-themes]$ fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  mate-themes-1.10.2-1.el7 
Password for raveit65: 
Creating a new update for  mate-themes-1.10.2-1.el7 
ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 96, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 170, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 374, in send_request
    {'url': to_bytes(method), 'err': to_bytes(e)})
ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Could not generate update request: Command 'bodhi --new --release epel7 --file bodhi.template mate-themes-1.10.2-1.el7 --username raveit65' returned non-zero exit status 255

[rave@mother mate-themes]$ rpm -qa python-fedora
python-fedora-0.5.5-1.fc22.noarch
```

**Comment by lmacken** [comment]
Can you please try again? Thanks

**Comment by NiceandGently** [comment]
command line works now , thanks
```
Creating a new update for  mate-themes-1.10.2-1.el7 
================================================================================
     mate-themes-1.10.2-1.el7
================================================================================
  Update ID: FEDORA-EPEL-2015-7714
    Release: Fedora EPEL 7
     Status: pending
       Type: enhancement
      Karma: 0
    Request: testing
      Notes: update to 1.10.2 release
  Submitter: raveit65
  Submitted: 2015-08-20 13:25:17
   Comments: bodhi - 2015-08-20 13:25:17 (karma 0)
             This update has been submitted for testing by
             raveit65.

  https://bodhi.fedoraproject.org/EPEL-7/FEDORA-EPEL-2015-7714
```
the other one i will test at website

**Comment by lmacken** [comment]
Great! Thanks for testing, and sorry for the inconvenience.

**Comment by NiceandGently** [comment]
works too at website :)
https://bodhi.fedoraproject.org/updates/mate-polkit-1.10.0-2.el7
