### ISSUE TITLE
CLI authentication failure cause traceback when there isn't a ticket cache

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2223]
Jaroslav Škarvada [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1505326) a traceback upon authentication failures in Bodhi. I was not able to reproduce it at first, but I discovered that if I remove ```~/.fedora/openidbaseclient-sessions.cache``` I am then able to reproduce the traceback:

```
$ bodhi updates new sdfkjsdf
Username: fjsdf
Password: 
Traceback (most recent call last):
  File "/home/vagrant/bodhi/bodhi/client/__init__.py", line 239, in new
    resp = client.save(**update)
  File "/home/vagrant/bodhi/bodhi/client/bindings.py", line 114, in wrapper
    result = method(*args, **kwargs)
  File "/home/vagrant/bodhi/bodhi/client/bindings.py", line 216, in save
    kwargs['csrf_token'] = self.csrf()
  File "/home/vagrant/bodhi/bodhi/client/bindings.py", line 114, in wrapper
    result = method(*args, **kwargs)
  File "/home/vagrant/bodhi/bodhi/client/bindings.py", line 453, in csrf
    self.login(self.username, self.password)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 293, in login
    openid_insecure=self.openid_insecure)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidproxyclient.py", line 138, in openid_login
    raise AuthError(output['message'])
AuthError: Authentication failed
```

We should make new releases for the 2.11 and 2.12 series for this bug, so we can fix it on EPEL 7, F26, and F27.

**Comment by sebwoj** [comment]
@bowlofeggs I am not able to reproduce it on F29. Ticket was closed in bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1505326#c7

What more can we do in this topic?

**Comment by bowlofeggs** [comment]
Yeah I suppose we should close it then. Thanks @sebwoj!
