### ISSUE TITLE
404 error when submitting an update using cli/fedpkg

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#228]
When trying to submit an update with "fedpkg update" or the cli I get the following error. 

bodhi-client-0.9.12.2-3.fc23

$ bodhi --new --release f23 --file bodhi.template iw-4.1-1.fc23 --username pbrobinson
Creating a new update for  iw-4.1-1.fc23 
ServerError(https://admin.fedoraproject.org/updates/save, 404, Not Found)
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 111, in save
    'bugs': bugs,
  File "/usr/lib/python2.7/site-packages/fedora/client/baseclient.py", line 379, in send_request
    auth_params=auth_params, retries=retries, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/fedora/client/proxyclient.py", line 505, in send_request
    raise ServerError(url, http_status, msg)
ServerError: ServerError(https://admin.fedoraproject.org/updates/save, 404, Not Found)

**Comment by nullr0ute** [comment]
Ah, also had to update to python-fedora-0.5.5-1.fc23
