### ISSUE TITLE
500 Error: KeyError: 'No such route named compose' 

### ISSUE THREAD

**Issue by sjenning** [fedora-infra/bodhi#2287]
```
 Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode as_unicode=True) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render **_kwargs_for_callable(callable_, data)) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 176, in render_body File "/usr/lib/python2.7/site-packages/bodhi/server/templates/update.html", line 514, in render_body File "/usr/lib/python2.7/site-packages/pyramid/url.py", line 265, in route_url raise KeyError('No such route named %s' % route_name) KeyError: 'No such route named compose' 
```

Happen going to https://bodhi.fedoraproject.org/updates/FEDORA-2018-b4fb4d0b97 while logged in.

Update is currently Request: testing and Status: Pending

**Comment by bowlofeggs** [comment]
Thanks @sjenning!

This was fixed in https://github.com/fedora-infra/bodhi/pull/2288
