### ISSUE TITLE
PDC timeouts do not print a popup on the new update form

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2312]
While testing a bodhi-3.6.1 beta on staging today, there was an issue that prevented Bodhi from talking to PDC in staging. The backend logged this traceback:

```
[Mon Apr 23 18:38:47.617503 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972] 2018-04-23 18:38:47,615 ERROR [bodhi.server][MainThread] Failed to create update, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617531 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972] Traceback (most recent call last):, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617534 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/services/updates.py", line 514, in new_update, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617536 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     result, _caveats = Update.new(request, _data), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617538 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 1981, in new, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617550 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     data['builds'], data['release'].name), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617553 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/models.py", line 1902, in contains_critpath_component, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617555 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     if get_critpath_components(relname, ptype, frozenset(components[ptype])):, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617557 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 194, in __call__, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617559 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     value = self.func(*args), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617561 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 248, in get_critpath_components, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617563 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     collection, component_type, components), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617565 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 1202, in get_critpath_components_from_pdc, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617567 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     pdc_request_json = pdc_api_get(pdc_api_url_with_args), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617569 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 1314, in pdc_api_get, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617570 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     return call_api(pdc_api_url, service_name='PDC', retries=3), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617572 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 1259, in call_api, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617574 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     rv = http_session.get(api_url, timeout=60), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617576 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617578 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     return self.request('GET', url, **kwargs), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617580 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617581 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     resp = self.send(prep, **send_kwargs), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617583 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617585 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     r = adapter.send(request, **kwargs), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617587 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 496, in send, referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617591 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972]     raise ConnectTimeout(e, request=request), referer: https://bodhi.stg.fedoraproject.org/updates/new
[Mon Apr 23 18:38:47.617594 2018] [wsgi:error] [pid 13] [client 10.128.2.1:57972] ConnectTimeout: HTTPSConnectionPool(host='pdc.stg.fedoraproject.org', port=443): Max retries exceeded with url: /rest_api/v1/component-branches/?active=true&critical_path=true&fields=global_component&name=f27&page_size=100&type=rpm&global_component=python-rpdb (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f786a7c90>, 'Connection to pdc.stg.fedoraproject.org timed out. (connect timeout=60)')), referer: https://bodhi.stg.fedoraproject.org/updates/new
```

Errors in Bodhi should be shown to the user, but all that happened was the Submit button stopped "spinning" and returned to the unsubmitted state.

**Comment by mattiaverga** [comment]
PDC has been dropped, see #5431
