### ISSUE TITLE
Properly handle BodhiExceptions from set_request 

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#236]
From production:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/services/comments.py", line 186, in new_comment
    com = update.comment(author=author, anonymous=anonymous, **data)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1355, in comment
    self.check_karma_thresholds(author)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1531, in check_karma_thresholds
    self.set_request(UpdateRequest.stable, username)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1002, in set_request
    raise BodhiException('. '.join(notes))
BodhiException: This critical path update has not yet been approved for pushing to the stable repository.  It must first reach a karma of 2, consisting of 0 positive karma from proventesters, along with 2 additional karma from the communit
y. Or, it must spend 14 days in testing without any negative feedback
```

**Comment by lmacken** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/services/comments.py", line 186, in new_comment
    com = update.comment(author=author, anonymous=anonymous, **data)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1355, in comment
    self.check_karma_thresholds(author)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1531, in check_karma_thresholds
    self.set_request(UpdateRequest.stable, username)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1026, in set_request
    raise BodhiException(flash_notes)
BodhiException: This update has not yet met the minimum testing requirements defined in the <a href="https://fedoraproject.org/wiki/Package_update_acceptance_criteria">Package Update Acceptance Criteria</a>

```

**Comment by ralphbean** [comment]
So, this works now and shows up in a messenger.js bubble.

In the api, it is returned in a ``caveats`` field.
