### ISSUE TITLE
The masher fails to send e-mails

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2522]
It seems that the new e-mail templates do not get installed by setup.py, which causes a traceback when the masher tries to send e-mails:

```
Jul 31 19:02:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]: [2018-07-31 19:02:10][fedmsg.consumers    INFO]f27-updates-testing Generating testing digest for F27
Jul 31 19:02:10 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]: [2018-07-31 19:02:10][bodhi.server   ERROR]f27-updates-testing Path does not exist: /usr/lib/python2.7/site-packages/bodhi/server/email/templates/maillist_templates/maillist_template.tpl
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]: [2018-07-31 19:02:11][fedmsg.consumers   ERROR]f27-updates-testing Exception in ComposerThread(f27-updates-testing)
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]: Traceback (most recent call last):
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 409, in work
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:     self._compose_updates()
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 933, in _compose_updates
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:     self.generate_testing_digest()
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 701, in generate_testing_digest
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:     self.add_to_digest(update)
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 693, in add_to_digest
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:     update, use_template='maillist_template')):
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:   File "/usr/lib/python2.7/site-packages/bodhi/server/mail.py", line 362, in get_template
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]:     templates.append((info['subject'], use_template % info))
Jul 31 19:02:11 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub[4383]: TypeError: unsupported operand type(s) for %: 'NoneType' and 'dict'
```

Ideally setup.py would include the templates when installing the package.

Additionally, a missing template should probably result in a cleaner error message instead of this traceback.

**Comment by ghost** [comment]
@bowlofeggs: Are the config variables set appropriately? In the following error line

```Path does not exist: /usr/lib/python2.7/site-packages/bodhi/server/email/templates/maillist_templates/maillist_template.tpl```

there is one extra maillist_template in the path. 

It might be because the ```config['mail.templates_basepath']``` is set to ```bodhi:server/email/templates/maillist_templates/``` instead of ```bodhi:server/email/templates/```.

**Comment by bowlofeggs** [comment]
The problem seems to be that the ```bodhi/server/email``` folder is not packaged by ```setup.py``` and thus is not present on installed systems.
