### ISSUE TITLE
RepodataException: Required part not in repomd.xml

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2572]
While testing a compose in staging, the new repo sanity check code was not satisfied with the repository that was generated by Pungi. At this time I am not sure what exactly was unsatisfactory, but this is the traceback I saw:

```
[2018-09-04 21:41:38][fedmsg.consumers   ERROR]f28-updates-testing ComposerThread failed. Transaction rolled back. 
Traceback (most recent call last): 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 339, in run 
    self.work() 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 410, in work 
    self._compose_updates() 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 950, in _compose_updates 
    self._sanity_check_repo() 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 1154, in _sanity_check_repo 
    sanity_check_repodata(repodata) 
  File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 287, in sanity_check_repodata 
    raise RepodataException('Required part not in repomd.xml') 
RepodataException: Required part not in repomd.xml
```

**Comment by bowlofeggs** [comment]
OK, this is strange. Despite this error, if I open a shell and run [```sanity_check_repodata()```](https://github.com/fedora-infra/bodhi/blob/eff7c339baef188deb63035bc90d394659ef866d/bodhi/server/util.py#L284-L342) by hand with the path of the repo that failed above, it passes just fine.

This leads me to suspect that something is not finished writing the files into the repo before ```sanity_check_repodata()``` gets called, but does finish writing it at some point.

**Comment by bowlofeggs** [comment]
I attempted to add a ```gc.collect()``` call before the sanity check runs in the hopes that the garbage collector would clean up the open files, but it did not work around the problem.

It's late in the work day, but my next workaround idea is to find out what open files my process has in the compose directory (```/mnt/koji```) and close them explicitly before running the sanity check.

**Comment by bowlofeggs** [comment]
I met with @puiterwijk this morning to talk about this issue, and he noticed that the issue stems from checking the source repos which do not have all the same files as the RPM repos. For example, source repos do not have ```prestodelta``` data.

The fix will be to adjust the sanity check algorithm so that it doesn't expect some of the data to be present when it is checking a source repo.
