### ISSUE TITLE
TypeError: __init__() takes exactly 3 arguments upon 400 request for unknown release

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2588]
@nirik let me know about a traceback he saw in production today, which turns out to be easily reproducible in the dev environment as well. Simply visit http://localhost:6543/updates/?release=F20&type=security and you will see this in the logs:

```
2018-09-13 22:56:34,961 DEBUG [bodhi.server][waitress] route matched for url http://localhost:6543/updates/?release=F20&type=security; route_name: 'updates', path_info: u'/updates/', pat
2018-09-13 22:56:34,964 DEBUG [bodhi.server][waitress] debug_authorization of url http://localhost:6543/updates/?release=F20&type=security (view name u'' against context <bodhi.server.se
: Allowed (no permission registered)
/usr/lib/python2.7/site-packages/cornice/validators/_colander.py:62: DeprecationWarning: Setting schema to a class is deprecated.  Set schema to an instance instead.
  class_attrs[location] = _ensure_instantiated(schema)
2018-09-13 22:56:34,969 ERROR [bodhi.server][waitress] Error caught.  Handling HTML response.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 352, in authdebug_view
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/usr/lib/python2.7/site-packages/cornice/service.py", line 507, in wrapper
    return args['error_handler'](request)
TypeError: __init__() takes exactly 3 arguments (2 given)
```

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
