### ISSUE TITLE
Bodhi is not compatible with markdown-3.0.0

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2618]
The pip container tests have started to [fail](https://ci.centos.org/job/bodhi-bodhi-docs-pip/46/console) with the recent release of markdown-3.0.0:

```
Traceback (most recent call last):
  File "./generate_db_schema", line 7, in <module>
    from bodhi.server import models
  File "/bodhi/bodhi/server/__init__.py", line 42, in <module>
    ffmarkdown.inject()
  File "/bodhi/bodhi/server/ffmarkdown.py", line 108, in inject
    original_pattern_builder = markdown.build_inlinepatterns
AttributeError: 'module' object has no attribute 'build_inlinepatterns'
```

The [release notes](https://python-markdown.github.io/change_log/release-3.0/) do not seem to reference this change at a quick glance, so more thorough analysis will be necessary.

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
