### ISSUE TITLE
sanity_check_repodata() fails on modular repos

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2631]
Production has been failing on modular repos with this exception:

```
[2018-10-01 23:26:36][fedmsg.consumers   ERROR]f29-modular-updates-testing ComposerThread failed. Transaction rolled back.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 339, in run 
    self.work()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 410, in work
    self._compose_updates()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 950, in _compose_updates
    self._sanity_check_repo()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 1155, in _sanity_check_repo
    sanity_check_repodata(repodata, source=False)
  File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 290, in sanity_check_repodata
    raise RepodataException('Required part not in repomd.xml')
RepodataException: Required part not in repomd.xml
[2018-10-01 23:26:36][fedmsg.consumers    INFO]f29-modular-updates-testing Released semaphore
[2018-10-01 23:26:36][fedmsg.consumers    INFO]PoolThread-twisted.internet.reactor-1 Push complete!  Summary follows:
[2018-10-01 23:26:36][fedmsg.consumers    INFO]PoolThread-twisted.internet.reactor-1   name:  f29-modular-updates-testing  success:  False
```

I don't think this code was intended to be run on modular repos, so we should probably just fix it by making sure it only runs on yum repos.

**Comment by bowlofeggs** [comment]
I will hotfix production by adding this method to ```ModuleComposerThread```:

```
def _sanity_check_repo(self):
    pass
```

This will prevent the sanity check code from running on modular repos and will at least let the process finish. Then we can take out time to decide how/if we want to properly sanity check module repos.

**Comment by puiterwijk** [comment]
@bowlofeggs it *IS* intended to run on modular repos, they just need a slightly different set of required elements.

**Comment by puiterwijk** [comment]
The set of fields modular repos need in their repomd:

- primary
- filelists
- other
- modules
- updateinfo

**Comment by bowlofeggs** [comment]
I have now hotfixed production with the current contents of https://github.com/fedora-infra/bodhi/pull/2632. If it works, I will make a 3.10.1 release with it.
