### ISSUE TITLE
'bodhi -R obsolete' tracebacks

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#273]
It worked fine, but printed out a traceback in the end:

```
$ bodhi -R obsolete latexila-3.16.2-1.fc23
Password for kalev: 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 273, in main
    log.info(data['tg_flash'])
KeyError: 'tg_flash'
```

**Comment by bowlofeggs** [comment]
I believe this issue is resolved by the ```bodhi-2.4.0``` client.
