### ISSUE TITLE
Bodhi does not select the correct pull URL for containers and flatpaks

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2742]
While testing bodhi-3.11.0b7 today in stg, I found that the flatpak and container composes both failed due to using the wrong URLs for the containers:

```
Nov 13 22:57:12 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub-3[3981]: [2018-11-13 22:57:12][bodhi.server   ERROR]f29-flatpak-updates-testing /usr/bin/bodhi-skopeo-lite copy docker://candidate-registry.s
tg.fedoraproject.org/eog@sha256:master-2920181113043343.1 docker://registry.stg.fedoraproject.org/eog@sha256:master-2920181113043343.1 returned a non-0 exit code: 1                                              
Nov 13 22:57:12 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub-3[3981]: [2018-11-13 22:57:12][bodhi.server   ERROR]f28-container-updates-testing /usr/bin/bodhi-skopeo-lite copy docker://candidate-registry
.stg.fedoraproject.org/f28/origin-base@sha256:3.9-1 docker://registry.stg.fedoraproject.org/f28/origin-base@sha256:3.9-1 returned a non-0 exit code: 1
Nov 13 22:57:12 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub-3[3981]: [2018-11-13 22:57:12][bodhi.server   ERROR]f29-flatpak-updates-testing b''                                                         
Nov 13 22:57:12 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub-3[3981]: b'Traceback (most recent call last):\n  File "/usr/bin/bodhi-skopeo-lite", line 11, in <module>\n    load_entry_point(\'bodhi-server
==3.11.0b7\', \'console_scripts\', \'bodhi-skopeo-lite\')()\n  File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__\n    return self.main(*args, **kwargs)\n  File "/usr/lib/python3.7/site
-packages/click/core.py", line 696, in main\n    rv = self.invoke(ctx)\n  File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\
n  File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke\n 
  return callback(*args, **kwargs)\n  File "/usr/lib/python3.7/site-packages/bodhi/server/scripts/skopeo_lite.py", line 769, in copy\n    Copier(src.get_endpoint(), tmp).copy()\n  File "/usr/lib/python3.7/site-p
ackages/bodhi/server/scripts/skopeo_lite.py", line 726, in copy\n    info = self.src.get_manifest()\n  File "/usr/lib/python3.7/site-packages/bodhi/server/scripts/skopeo_lite.py", line 633, in get_manifest\n   
return get_manifest(self.session, self.repo, self.tag)\n  File "/usr/lib/python3.7/site-packages/bodhi/server/scripts/skopeo_lite.py", line 345, in get_manifest\n    response.raise_for_status()\n  File "/usr/lib
/python3.7/site-packages/requests/models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://candidate-registry.stg.fedoraproject.org/v2/eog@sha256/manifests/master-2920181113043343.1\n'                                                                                                                           
Nov 13 22:57:12 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub-3[3981]: [2018-11-13 22:57:12][bodhi.server   ERROR]f28-container-updates-testing b''                                                       
Nov 13 22:57:12 bodhi-backend01.stg.phx2.fedoraproject.org fedmsg-hub-3[3981]: b'Traceback (most recent call last):\n  File "/usr/bin/bodhi-skopeo-lite", line 11, in <module>\n    load_entry_point(\'bodhi-server==3.11.0b7\', \'console_scripts\', \'bodhi-skopeo-lite\')()\n  File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__\n    return self.main(*args, **kwargs)\n  File "/usr/lib/python3.7/site
-packages/click/core.py", line 696, in main\n    rv = self.invoke(ctx)\n  File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\
n  File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke\n 
  return callback(*args, **kwargs)\n  File "/usr/lib/python3.7/site-packages/bodhi/server/scripts/skopeo_lite.py", line 769, in copy\n    Copier(src.get_endpoint(), tmp).copy()\n  File "/usr/lib/python3.7/site-p
ackages/bodhi/server/scripts/skopeo_lite.py", line 726, in copy\n    info = self.src.get_manifest()\n  File "/usr/lib/python3.7/site-packages/bodhi/server/scripts/skopeo_lite.py", line 633, in get_manifest\n   
return get_manifest(self.session, self.repo, self.tag)\n  File "/usr/lib/python3.7/site-packages/bodhi/server/scripts/skopeo_lite.py", line 345, in get_manifest\n    response.raise_for_status()\n  File "/usr/lib
/python3.7/site-packages/requests/models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://candid
ate-registry.stg.fedoraproject.org/v2/f28/origin-base@sha256/manifests/3.9-1\n'
```

Note that it is including ```@sha256``` in the repository name.

**Comment by bowlofeggs** [comment]
CC @owtaylor @cverna

**Comment by bowlofeggs** [comment]
@owtaylor I feel like I remember looking in Koji and agreeing that the patch was correct, including its documentation that the format was like ```candidate-registry.fedoraproject.org/f29/cockpit:176-5.fc28```, but I guess I didn't notice that pesky ```@sha256```. When I look at that [example container](https://koji.fedoraproject.org/koji/buildinfo?buildID=1141835), I see this:

```['candidate-registry.fedoraproject.org/f29/cockpit@sha256:2bd64a888535a6b0428a3cfcaa4aa7cec5dd3e3bbb4ed84e315e985e2d5c6bb5', 'candidate-registry.fedoraproject.org/f29/cockpit:176-5.fc28']```

It seems that the [Bodhi code](https://github.com/fedora-infra/bodhi/blob/719a1458700a4d18085d474228679812b067065c/bodhi/server/util.py#L1429-L1451) just uses the first element of that array:

```
    koji = buildsys.get_session()
    koji_build = koji.getBuild(build.nvr)

    pull_specs = koji_build['extra']['image']['index']['pull']
    # Specs are of the form 'candidate-registry.fedoraproject.org/f29/cockpit:176-5.fc28'
    # All the pull specs should have the same repository, so which one we use is arbitrary
    base, tag = pull_specs[0].split(':', 1)
    server, repository = base.split('/', 1)
```

The problem is that the first one has the ```@sha256``` in it, at least sometimes. Is there any documentation on the format being stored there, or what order the elements are in? It seems we want the second one in this case.

Without knowing whether the order is consistent, I suppose we could try to detect the @ character and also strip off anything to the right of it, or use it to know to try the next element.

**Comment by bowlofeggs** [comment]
The more I think about it, the less sense the first pull URL makes to me. Why is it ```f29cockpit``` instead of ```f29/cockpit```? We really do need to target the second one since the first one is wrong. Do we know what system writes this data into Koji?

**Comment by bowlofeggs** [comment]
Another solution I can think of is that we do know the NVR, so we could loop on the list until we find one that has the expected VR from the NVR in it. Maybe that's not really better than searching for the @ character and killing it, but just another idea.

**Comment by owtaylor** [comment]
`repo@[hash-reference]` is another valid form of docker pull spec - we just need to handle it in the code. I think I misread the koji metadata - I could find no evidence that anything changed in atomic-reactor.
