### ISSUE TITLE
IncompleteRead while Composer polls for repomd files

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2758]
It seems that Python's http library can raise a new Exception in Python 3 that we don't catch:

```
[2018-11-20 14:42:34][fedmsg.consumers    INFO]epel7-testing Polling http://download01.phx2.fedoraproject.org/pub/epel/testing/7/aarch64/repodata/repomd.xml
[2018-11-20 14:42:34][fedmsg.consumers   ERROR]epel7-testing Exception in ComposerThread(epel7-testing)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 410, in work
    self._compose_updates()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 959, in _compose_updates
    self._wait_for_sync()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 1327, in _wait_for_sync
    newsum = hashlib.sha1(masterrepomd.read()).hexdigest()
  File "/usr/lib64/python3.7/http/client.py", line 460, in read
    s = self._safe_read(self.length)
  File "/usr/lib64/python3.7/http/client.py", line 612, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(3295 bytes read, 1 more expected)
```

This one should be pretty easy to fix - we just need to catch this new Exception and retry, similar to what we do if a URLError is raised.

**Comment by bowlofeggs** [comment]
The fix for this issue is now released with Bodhi 3.11.1 and deployed to Fedora's production instance.

**Comment by bowlofeggs** [comment]
The fix I made for this mistakenly handled ```IncompleteRead``` on ```urlopen()``` instead of on ```read()```, so the error still happens.

**Comment by bowlofeggs** [comment]
I once again hotfixed this by moving the ```read()``` statement into the ```Exception``` handler.
