### ISSUE TITLE
HTTP 500 when viewing composes

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2826]
I saw this when visiting https://bodhi.fedoraproject.org/composes/ just now:

```
500 Internal Server Error

Traceback (most recent call last): File "/usr/lib/python3.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python3.7/site-packages/mako/template.py", line 471, in render_unicode as_unicode=True) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 838, in _render **_kwargs_for_callable(callable_, data)) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 873, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 899, in _exec_template callable_(context, *args, **kwargs) File "/usr/lib/python3.7/site-packages/bodhi/server/templates/master.html", line 189, in render_body ${self.body()} File "/usr/lib/python3.7/site-packages/bodhi/server/templates/composes.html", line 19, in render_body ${ self.util.composestate2html(compose.state) | n } File "/usr/lib/python3.7/site-packages/bodhi/server/util.py", line 525, in composestate2html }[state.value] KeyError: 'syncing_repo'
```

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
