### ISSUE TITLE
Command line client 404s for pretty much anything

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/bodhi#284]
Even trivial things like listing updates just 404 for me:

```
bericote [~] % bodhi --mine
Password for tomh: 
ServerError(https://admin.fedoraproject.org/updates/list, 404, Not Found)
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 403, in main
    data = bodhi.query(mine=opts.mine)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 148, in query
    return self.send_request('list', req_params=params, auth=auth)
  File "/usr/lib/python2.7/site-packages/fedora/client/baseclient.py", line 379, in send_request
    auth_params=auth_params, retries=retries, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/fedora/client/proxyclient.py", line 505, in send_request
    raise ServerError(url, http_status, msg)
ServerError: ServerError(https://admin.fedoraproject.org/updates/list, 404, Not Found)
```

**Comment by leigh123linux** [comment]
I believe you need to update  python-fedora bodhi-client

```
$ rpm -q python-fedora bodhi-client
python-fedora-0.5.5-1.fc22.noarch
bodhi-client-0.9.12.2-3.fc22.noarch
```

it works (sort of) here with the new versions

```
$ bodhi --mine -u leigh123linux
 tint2-0.12.2-2.el6                           enhancement  pending   2015-08-20 
 tint2-0.12.2-2.el7                           enhancement  pending   2015-08-20 
 blueman-2.1-0.1.git0a5defd.fc23              enhancement  pending   2015-08-20 
 cinnamon-2.6.13-7.fc23                       bugfix       stable    2015-08-20 
 cinnamon-2.6.13-5.fc23                       bugfix       stable    2015-08-10 
 cinnamon-2.6.13-7.fc22                       bugfix       testing   2015-08-10 
 cinnamon-2.6.13-7.fc21                       bugfix       testing   2015-08-10 
 cinnamon-screensaver-2.6.4-3.fc23            bugfix       stable    2015-08-10 
 tint2-0.12.2-1.fc21                          bugfix       stable    2015-08-20 
 tint2-0.12.2-1.fc23                          bugfix       stable    2015-08-04 
 tint2-0.12.2-1.fc22                          bugfix       stable    2015-08-04 
 tint2-0.12-4.el7                             enhancement  stable    2015-07-27 
 blueman-2.0-11.fc21                          bugfix       stable    2015-07-17 
 zukitwo-20141022-9.fc22                      enhancement  stable    2015-07-17 
 tint2-0.12-4.fc21                            enhancement  stable    2015-07-17 
 tint2-0.12-4.fc22                            enhancement  stable    2015-07-17 
 streamtuner-2.1.9-3.fc22                     bugfix       stable    2015-07-13 
 streamtuner-2.1.9-3.fc21                     bugfix       stable    2015-07-13 
 lightdm-gtk-greeter-settings-1.2.0-1.fc22    new package  stable    2015-07-13 
 lightdm-gtk-greeter-settings-1.2.0-1.fc21    new package  stable    2015-07-13 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 411, in main
    log.info(data['title'])
KeyError: 'title'
```

**Comment by tomhughes** [comment]
Well I'm using whatever was available on the mirrors about 15 hours ago when I last did an update, but a new update shows nothing else available. Versions are:

python-fedora-0.4.0-2.fc22.noarch
bodhi-client-0.9.12.2-1.fc22.noarch

**Comment by tomhughes** [comment]
So python-fedora-0.5.5-1.fc22.noarch is available, but only in testing, and that does seem to fix it. The bodhi-client update doesn't seem to be anywhere but also doesn't seem to be needed...

**Comment by leigh123linux** [comment]
The new bodhi is in pending

https://bodhi.fedoraproject.org/updates/bodhi-0.9.12.2-3.fc22
