### ISSUE TITLE
Frequent koji.AuthError since switching to Python 3

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2870]
I've observed that Koji frequently raises ```koji.AuthError``` since Bodhi switched to Python 3:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 344, in run
    self.work()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 415, in work
    self._compose_updates()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 949, in _compose_updates
    uinfo = self._generate_updateinfo()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 1018, in _generate_updateinfo
    self.db, self.mash_dir)
  File "/usr/lib/python3.7/site-packages/bodhi/server/metadata.py", line 149, in __init__
    self.add_update(update)
  File "/usr/lib/python3.7/site-packages/bodhi/server/metadata.py", line 235, in add_update
    koji = get_session()
  File "/usr/lib/python3.7/site-packages/bodhi/server/buildsys.py", line 639, in get_session
    return _buildsystem()
  File "/usr/lib/python3.7/site-packages/bodhi/server/buildsys.py", line 672, in get_koji_login
    return koji_login(config=settings, authenticate=authenticate)
  File "/usr/lib/python3.7/site-packages/bodhi/server/buildsys.py", line 596, in koji_login
    if authenticate and not koji_client.krb_login(**get_krb_conf(config)):
  File "/usr/lib/python3.7/site-packages/koji/__init__.py", line 2119, in krb_login
    if self.gssapi_login(principal, keytab, ccache, proxyuser=proxyuser):
  File "/usr/lib/python3.7/site-packages/koji/__init__.py", line 2271, in gssapi_login
    raise AuthError('unable to obtain a session')
koji.AuthError: unable to obtain a session
```

We should catch this and retry. Something like https://github.com/litl/backoff/ might be nice to use to do it.

**Comment by bowlofeggs** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1609298 may or may not be related, but it's another Koji connection issue under Python 3.

**Comment by bowlofeggs** [comment]
I reported this to Koji to see if they know anything: https://pagure.io/koji/issue/1191

**Comment by bowlofeggs** [comment]
I observed this in the logs:

```
Dec 20 16:30:44 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub-3[16441]: [2018-12-20 16:30:44][      koji   ERROR]dist-6E-epel gssapi auth failed: requests.exceptions.ConnectionError: ('Connection aborted.',
RemoteDisconnected('Remote end closed connection without response'))
```

That's the same error message as seen in https://bugzilla.redhat.com/show_bug.cgi?id=1609298

**Comment by bowlofeggs** [comment]
There is now an infrastructure ticket about this as well: https://pagure.io/fedora-infrastructure/issue/7458

**Comment by bowlofeggs** [comment]
I think this was fixed in the Koji tracker.
