### ISSUE TITLE
Sometimes the integration tests fail to stop their containers

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2976]
I've been seeing a problem somewhat frequently this week where the integration tests sometimes fail like this:

```
$ bci all
<snip>
     f29-integration                	============================= test session starts ==============================
     f29-integration                	platform linux -- Python 3.7.2, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
     f29-integration                	rootdir: /home/vagrant/bodhi, inifile: setup.cfg
     f29-integration                	plugins: cov-2.5.1
     f29-integration                	collected 7 items
     f29-integration                	
     f29-integration                	devel/ci/integration/tests/test_bodhi.py .                               [ 14%]
     f29-integration                	devel/ci/integration/tests/test_bodhi_cli.py ....F/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
     f29-integration                	  import imp
     f29-integration                	/usr/lib/python3.7/site-packages/more_itertools/more.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
     f29-integration                	  from collections import Counter, defaultdict, deque, Sequence
     f29-integration                	Traceback (most recent call last):
     f29-integration                	  File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 229, in _raise_for_status
     f29-integration                	    response.raise_for_status()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
     f29-integration                	    raise HTTPError(http_error_msg, response=self)
     f29-integration                	requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.26/containers/a5a9661e72978b42826076e61f85f44f7cedff32e8a79e5b51be1eb1fdf34151/kill
     f29-integration                	
     f29-integration                	During handling of the above exception, another exception occurred:
     f29-integration                	
     f29-integration                	Traceback (most recent call last):
     f29-integration                	  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
     f29-integration                	    "__main__", mod_spec)
     f29-integration                	  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
     f29-integration                	    exec(code, run_globals)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pytest.py", line 67, in <module>
     f29-integration                	    raise SystemExit(pytest.main())
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 64, in main
     f29-integration                	    return config.hook.pytest_cmdline_main(config=config)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
     f29-integration                	    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
     f29-integration                	    return self._inner_hookexec(hook, methods, kwargs)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
     f29-integration                	    firstresult=hook.spec_opts.get('firstresult'),
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
     f29-integration                	    return outcome.get_result()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
     f29-integration                	    raise ex[1].with_traceback(ex[2])
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
     f29-integration                	    res = hook_impl.function(*args)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/main.py", line 208, in pytest_cmdline_main
     f29-integration                	    return wrap_session(config, _main)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/main.py", line 201, in wrap_session
     f29-integration                	    session=session, exitstatus=session.exitstatus
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
     f29-integration                	    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
     f29-integration                	    return self._inner_hookexec(hook, methods, kwargs)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
     f29-integration                	    firstresult=hook.spec_opts.get('firstresult'),
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 196, in _multicall
     f29-integration                	    gen.send(outcome)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/terminal.py", line 583, in pytest_sessionfinish
     f29-integration                	    outcome.get_result()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
     f29-integration                	    raise ex[1].with_traceback(ex[2])
     f29-integration                	  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
     f29-integration                	    res = hook_impl.function(*args)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 59, in pytest_sessionfinish
     f29-integration                	    session._setupstate.teardown_all()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 525, in teardown_all
     f29-integration                	    self._pop_and_teardown()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 497, in _pop_and_teardown
     f29-integration                	    self._teardown_with_finalization(colitem)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 515, in _teardown_with_finalization
     f29-integration                	    self._callfinalizers(colitem)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 512, in _callfinalizers
     f29-integration                	    py.builtin._reraise(*exc)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/py/_builtin.py", line 227, in _reraise
     f29-integration                	    raise cls.with_traceback(val, tb)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 505, in _callfinalizers
     f29-integration                	    fin()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 798, in finish
     f29-integration                	    py.builtin._reraise(*e)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/py/_builtin.py", line 227, in _reraise
     f29-integration                	    raise cls.with_traceback(val, tb)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 792, in finish
     f29-integration                	    func()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 740, in teardown
     f29-integration                	    next(it)
     f29-integration                	  File "/home/vagrant/bodhi/devel/ci/integration/tests/fixtures/greenwave.py", line 49, in greenwave_container
     f29-integration                	    container.kill()
     f29-integration                	  File "/usr/lib/python3.7/site-packages/conu/backend/docker/container.py", line 570, in kill
     f29-integration                	    self.d.kill(self.get_id(), signal=signal)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
     f29-integration                	    return f(self, resource_id, *args, **kwargs)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/docker/api/container.py", line 754, in kill
     f29-integration                	    self._raise_for_status(res)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
     f29-integration                	    raise create_api_error_from_http_exception(e)
     f29-integration                	  File "/usr/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
     f29-integration                	    raise cls(e, response=response, explanation=explanation)
     f29-integration                	docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot kill container a5a9661e72978b42826076e61f85f44f7cedff32e8a79e5b51be1eb1fdf34151: Container a5a9661e72978b42826076e61f85f44f7cedff32e8a79e5b51be1eb1fdf34151 is not running")
     f29-integration                	sys:1: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.1', 51950)>
     f29-integration                	ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Unfortunately, it seems that this traceback is causing us not to get the information about the test that was running, as it seems to be a failure in the test cleanup code, or something along those lines.

It does seem to often, or possibly always, be the act of killing the Greenwave container that fails. I will likely wrap that part of the cleanup in a try/except to catch this exception and see if that helps figure out what is going on.

**Comment by bowlofeggs** [comment]
It turns out that Greenwave is failing to start because they refuse to start if a particular config is present. The warning says that the config is "deprecated", but "deprecated" should not mean that it refuses to start. "deprecated" means that it will be removed in a future release. I will file a ticket with them about that.

**Comment by bowlofeggs** [comment]
This is the error from Greenwave:

```
greenwave.safe_yaml.SafeYAMLError: Policy \'atomic_ci_pipeline_results\': Attribute \'rules\': !FedoraAtomicCi is deprecated. Please use the "packages" whitelist instead.\n
```

**Comment by bowlofeggs** [comment]
I reported the misuse of the word deprecated here: https://pagure.io/greenwave/issue/383
