### ISSUE TITLE
AttributeError: Bug object has no attribute 'private'

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3016]
Now that 3.13.0 is in production, I've started to receive tracebacks from bodhi-backend02 related to the patch in #2714. It seems that we either need to ask for the "private" attribute of bugs from Bugzilla, or some other solution if that does not exist:

Message
-------
[2019-02-18 17:04:54][     bodhi   ERROR]
```python
Unable to alter bug #1668946
```

Process Details
---------------
- host:     bodhi-backend02.phx2.fedoraproject.org
- PID:      59293
- name:     fedmsg-hub-3
- command:  /usr/bin/python3 /usr/bin/fedmsg-hub-3
- msg_id:   

Callstack that lead to the logging statement
--------------------------------------------
```python
  File "/usr/lib64/python3.7/threading.py", line 885 in _bootstrap
    
  File "/usr/lib64/python3.7/threading.py", line 917 in _bootstrap_inner
    
  File "/usr/lib64/python3.7/threading.py", line 865 in run
    
  File "/usr/lib64/python3.7/site-packages/twisted/_threads/_threadworker.py", line 46 in work
    
  File "/usr/lib64/python3.7/site-packages/twisted/_threads/_team.py", line 190 in doWork
    
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 250 in inContext
    
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 266 in <lambda>
    
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 122 in callWithContext
    
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 85 in callWithContext
    
  File "/usr/lib/python3.7/site-packages/moksha/hub/api/consumer.py", line 186 in _work_loop
    
  File "/usr/lib/python3.7/site-packages/moksha/hub/api/consumer.py", line 207 in _do_work
    
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/updates.py", line 135 in consume
    
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/updates.py", line 206 in work_on_bugs
    
  File "/usr/lib/python3.7/site-packages/bodhi/server/models.py", line 4284 in modified
    
  File "/usr/lib/python3.7/site-packages/bodhi/server/bugs.py", line 313 in modified
    
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/bugs.py", line 301, in modified
    if bug.private:
  File "/usr/lib/python3.7/site-packages/bugzilla/bug.py", line 115, in __getattr__
    raise AttributeError(msg)
AttributeError: Bug object has no attribute 'private'.
If 'private' is a bugzilla attribute, it may not have been cached when the bug was fetched. You may want to adjust your include_fields for getbug/query.

**Comment by bowlofeggs** [comment]
Hello @mattiaverga!

This patch got deployed to production today, and there seems to be a problem because the Bug object doesn't seem to have a ```private``` attribute.

When I read the Bugzilla docs, I don't see mention of there being such an attribute on bugs (I do see one on comments):

https://www.bugzilla.org/docs/4.4/en/html/api/Bugzilla/WebService/Bug.html#get

I did try adding an ```include_fields=['private']``` to the ```getbug()``` call, but that did not work. Do you remember where you learned about that field name from? Is it something particular to the Red Hat Bugzilla instance?

I'm unsure of how best to proceed, other than to revert the commit for now. It's blocking us from running a compose, so I may need to take that step since it seems more complex than I thought it'd be at first.

**Comment by bowlofeggs** [comment]
It seems that if we access a private bug, we get an Exception (and not a ```private``` attribute):

```
$ python3
Python 3.7.2 (default, Jan 16 2019, 19:49:22) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bodhi.server import bugs
>>> bz = bugs.Bugzilla()
>>> bz.getbug(1342858)
<Bug #1342858 on https://bugzilla.redhat.com/xmlrpc.cgi at 0x7f6265b45ac8>
>>> b = bz.getbug(1563797)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/bodhi/bodhi/server/bugs.py", line 127, in getbug
    return self.bz.getbug(bug_id, include_fields=['private'])
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/base.py", line 1072, in getbug
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/base.py", line 1062, in _getbug
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/base.py", line 1030, in _getbugs
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/transport.py", line 104, in _ServerProxy__request
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/transport.py", line 201, in request
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/transport.py", line 179, in _request_helper
  File "/usr/local/lib/python3.7/site-packages/python_bugzilla-2.2.0-py3.7.egg/bugzilla/transport.py", line 154, in parse_response
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 102: 'You are not authorized to access bug #1563797. To see this bug, you must first log in to an account with the appropriate permissions.'>
```

I think the fix here is probably to refactor to catch the ```xmlrpc.client.Fault``` and use that as the indicator that the bug is private, rather than the attribute used now.

**Comment by bowlofeggs** [comment]
Ah, I think I see what is going on. There are two models involved for a ```Bug```: one from Bodhi's own database, and one from the ```python-bugzilla``` API. The one from Bodhi's database *does* have a ```private``` attribute, added in #2714, but the one from bugzilla does not. One line in ```bugs.py``` that uses the ```private``` attribute is interacting with the Bodhi database model and the others are all dealing with the Bugzilla model, and those are the ones that experience this problem.

There are a few ways we could fix this. The quick fix would be to revert the patch from #2714 and re-open the issue and take another swing at it later. Since this is blocking composes, I may take that step for the short term.

For the longer term, it might be reasonable to just wrap all the API calls in ```bugs.py``` with exception handlers to catch this ```Fault 102``` error and deal with it gracefully. There are a few ways that I might consider "graceful":

* Remove any bug from an update when it raises this error, perhaps adding a comment on the update from Bodhi to this effect so the user is informed. We can't reasonably use the caveats API to inform the user as suggested in #344 for three reasons: we don't want the create web request to depend on Bugzilla being online; we don't want the extra API lag due to web requests to Bugzilla in that create web request; and lastly, a bug's private state can be altered at any time (just because it was not private when it was created doesn't mean it won't be private later).
* Any time we hit this error, simply log it and move on.

The first suggestion would probably be more user friendly, but there are various places in the code that touch BZ and we'd have to make sure they all handle this scenario (i.e., it might be a little invasive and a little copy/pasty.) The second would be quick but then users won't know why certain bugs don't get updated by Bodhi.

We've essentially been living with the second solution from the users' perspectives for years, since they don't get the error e-mails I get and we don't update bugs.

Thus, I think I will opt for reverting the commit from #2714 and the second solution I mention above (catching the 102 Fault, log, and move on).

**Comment by mattiaverga** [comment]
AH, sorry for that, indeed I confused the two bug models. 
In fact, I managed the 102 Fault only in bugs.update_details(), while in the other functions I thought to act on Bodhi bug model. I should have managed all those with the same try/except clause...

**Comment by bowlofeggs** [comment]
On Tue, 2019-02-19 at 00:40 -0800, Mattia Verga wrote:
> AH, sorry for that, indeed I confused the two bug models.
> In fact, I managed the 102 Fault only in bugs.update_details(), while
> in the other functions I thought to act on Bodhi bug model. I should
> have managed all those with the same try/except clause...

It's OK - I also confused them when I reviewed the patch, so it wasn't
just you ☺

**Comment by bowlofeggs** [comment]
This field is removed in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
