### ISSUE TITLE
Submitting a new update dies: (psycopg2.IntegrityError) null value in column "private" violates not-null constraint

### ISSUE THREAD

**Issue by ppisar** [fedora-infra/bodhi#3022]
When submitting an update for a new RPM build using a bodhi client, the request dies with an psycopg2 error message sent as an HTML document:

~~~~
$ bodhi updates new --type bugfix --bugs  1678447 --close-bugs --notes 'This release fixes truncating nanoseconds in utime() function. It also corrects tests.' perl-Time-HiRes-1.9760-1.fc29
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fedora/client/openidbaseclient.py", line 249, in send_request
    data = output.json()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 6 column 1 (char 5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 386, in new
    resp = client.save(**update)
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 116, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 267, in save
    data=kwargs)
  File "/usr/lib/python3.7/site-packages/fedora/client/openidbaseclient.py", line 258, in send_request
    'output': to_bytes(output.text),
fedora.client.ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 400, Error returned from json module while processing b'https://bodhi.fedoraproject.org/updates/': b'Expecting value: line 6 column 1 (char 5)'
b'\n\n\n\n\n<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <meta name="description" content="management of Fedora Project updates" />\n    <meta name="author" content="Luke Macken" />\n    <meta name="author" content="Ralph Bean" />\n    <meta name="author" content="Randy Barlow" />\n\n    <!-- Only allow websockets connections to fedoraproject.org. -->\n    <meta http-equiv="Content-Security-Policy" content="connect-src https://*.fedoraproject.org/ wss://hub.fedoraproject.org:9939/">\n\n    <link rel="shortcut icon" href="https://bodhi.fedoraproject.org/static/ico/favicon.ico">\n\n    <base href="https://bodhi.fedoraproject.org/"/>\n    <title>\n      \n      Fedora Updates System\n      \n    </title>\n    <link href="https://bodhi.fedoraproject.org/static/fedora-bootstrap-1.0.1/fedora-bootstrap.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/fonts/open-sans.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/fonts/hack.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/fonts/font-awesome.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/css/text.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/css/navbar.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/css/footer.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/css/site.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/css/datagrepper-feed.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/css/panel.css" rel="stylesheet" />\n    <script src="https://bodhi.fedoraproject.org/static/js/jquery-1.10.2.min.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/Chart-0.2.0.min.js"></script>\n  </head>\n\n  <body>\n      <div class="searchbar" style="display:none;">\n        <div class="container">\n          <div class="row">\n            <div class="col-xs-12">\n              <form id="search" role="search" class="nav navbar-form navbar-left">\n                <div id="bloodhound" class="form-group m-b-0">\n                  <input class="typeahead form-control" name="term" type="text" placeholder="Search..." style="height:50px;background:rgba(0,0,0,0);border:0;color:white;line-height:50px;">\n                </div>\n              </form>\n            </div>\n          </div>\n        </div>\n      </div>\n      <div class="masthead">\n      <div class="container">\n        <div class="row">\n          <div class="col-sm-6">\n            <a href="https://bodhi.fedoraproject.org/">\n              <img src="https://bodhi.fedoraproject.org/static/img/bodhi-logo.png" alt="Fedora Update System" id="kojiLogo" height="40px">\n            </a>\n          </div>\n          <div class="col-sm-6">\n            <div class="row">\n              <nav class="navbar navbar-light p-t-0 p-b-0">\n                  <div class="container">\n                    <ul class="nav navbar-nav nav-pill pull-xs-right">\n                        <li class="nav-item dropdown">\n                          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">\n                            <span class="glyphicon glyphicon-plus"></span>\n                            Create\n                          </a>\n                          <div class="dropdown-menu">\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/updates/new">\n                                New Update\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/overrides/new">\n                                New Override\n                            </a>\n                          </div>\n                        </li>\n\n                        <li class="nav-item dropdown">\n                          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">\n                            <span class="glyphicon glyphicon-tags"></span>\n                            Stats\n                          </a>\n                          <div class="dropdown-menu">\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/metrics">\n                              Overall Metrics\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/masher/">\n                              Masher Status\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/composes/">\n                              Composes\n                            </a>\n                            <div class="dropdown-divider"></div>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F29M">\n                              Fedora 29 Modular\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F29F">\n                              Fedora 29 Flatpaks\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F29C">\n                              Fedora 29 Containers\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F29">\n                              Fedora 29\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F28M">\n                              Fedora 28 Modular\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F28C">\n                              Fedora 28 Containers\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F28">\n                              Fedora 28\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/EPEL-7">\n                              Fedora EPEL 7\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/EL-6">\n                              Fedora EPEL 6\n                            </a>\n                            <div class="dropdown-divider"></div>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F27M">\n                              Fedora 27 Server Edition\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F27">\n                              Fedora 27\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F26">\n                              Fedora 26\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F25">\n                              Fedora 25\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F24">\n                              Fedora 24\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F23">\n                              Fedora 23\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F22">\n                              Fedora 22\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F21">\n                              Fedora 21\n                            </a>\n                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/EL-5">\n                              Fedora EPEL 5\n                            </a>\n                            <div class="dropdown-divider"></div>\n                          </div>\n                        </li>\n\n                        <li class="nav-item dropdown">\n                          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">\n                            <span class="glyphicon glyphicon-user"></span>\n                            <img src="https://seccdn.libravatar.org/avatar/12f13283140a3e56271e48fbe0cdccc1fd09b0859759f11ac65baf89dae48515?s=24&d=retro"/>\n                          </a>\n                          <div class="dropdown-menu">\n                              <a class="dropdown-item" href="https://bodhi.fedoraproject.org/users/ppisar">\n                                Your Profile\n                              </a>\n                              <a class="dropdown-item" href="https://apps.fedoraproject.org/notifications/ppisar.id.fedoraproject.org/">\n                                Manage Alerts\n                              </a>\n                              <form id="popup_toggle" action="https://bodhi.fedoraproject.org/popup_toggle" method="POST">\n                                <input type="hidden" name="next" value="https://bodhi.fedoraproject.org/updates/">\n                              </form>\n                              <a class="dropdown-item" href="javascript:$(\'#popup_toggle\').submit();">\n                                Disable popups\n                              </a>\n                              <a class="dropdown-item" href="https://bodhi.fedoraproject.org/logout">\n                                Log out</a>\n                          </div>\n                        </li>\n\n                        <li class="nav-item">\n                          <a class="nav-link" href="javascript:void(0);" id="search-toggle">\n                            <span class="fa fa-search"></span>\n                          </a>\n                        </li>\n                    </ul>\n                  </div>\n                </nav>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n    <div class="bodycontent p-b-3">\n        \n\n<div class="row">\n  <div class="col-md-offset-3 col-md-6">\n    <div class="panel error-page-panel">\n      <h1>400 <small>Bad Request</small></h1>\n      <p class="lead">Unable to create update.  (psycopg2.IntegrityError) null value in column "private" violates not-null constraint\nDETAIL:  Failing row contains (52814, 1678447, null, f, f, null).\n [SQL: \'INSERT INTO bugs (bug_id, title, security, parent) VALUES (%(bug_id)s, %(title)s, %(security)s, %(parent)s) RETURNING bugs.id\'] [parameters: {\'bug_id\': 1678447, \'title\': None, \'security\': False, \'parent\': False}] (Background on this error at: http://sqlalche.me/e/gkpj)</p>\n    </div>\n  </div>\n</div>\n\n    </div> <!-- /bodycontent -->\n\n    <div class="footer p-y-3">\n      <div class="container">\n        <p class="text-muted text-xs-center">\n          Copyright &copy; 2007-2018 Red Hat, Inc. and\n          <a href="https://github.com/fedora-infra/bodhi/graphs/contributors">\n          others</a>.\n        </p>\n        <p class="text-muted text-xs-center">\n          Running\n          <strong>bodhi-3.13.1</strong> on\n          <strong>bodhi-web-40-n5shn</strong>.\n        </p>\n        <p class="text-muted text-xs-center">\n          <a href="https://github.com/fedora-infra/bodhi">\n          bodhi</a> is Free Software.\n          Please <a href="https://github.com/fedora-infra/bodhi/issues">\n          file issues</a>\n          if you have any problems. Read the <a href="https://bodhi.fedoraproject.org/docs">documentation</a>.\n        </p>\n        <p class="text-muted text-xs-center">\n            <a href="https://fedoraproject.org/wiki/Legal:Main">Legal</a>\n            |\n            <a href="https://fedoraproject.org/wiki/Legal:PrivacyPolicy">Privacy policy</a>\n        </p>\n      </div>\n    </div>\n\n    <!-- Placed at the end of the document so the pages load faster -->\n    <script src="https://bodhi.fedoraproject.org/static/jquery.flot.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/jquery.flot.stack.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/fedora-bootstrap-1.0.1/fedora-bootstrap.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/moment/moment.min.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/cabbage.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/forms.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/site.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/live.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/messenger/js/messenger.min.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/messenger/js/messenger-theme-flat.js"></script>\n    <link href="https://bodhi.fedoraproject.org/static/messenger/css/messenger.css" rel="stylesheet" />\n    <link href="https://bodhi.fedoraproject.org/static/messenger/css/messenger-theme-flat.css" rel="stylesheet" />\n    <script src="https://bodhi.fedoraproject.org/static/js/typeahead.bundle.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/search.js"></script>\n    <script src="https://bodhi.fedoraproject.org/static/js/konami.js"></script>\n\n    <script src="https://apps.fedoraproject.org/fedmenu/js/fedora-libravatar.js"></script>\n    <script src="https://apps.fedoraproject.org/fedmenu/js/fedmenu.js"></script>\n    <script>\n      fedmenu({\n          \'url\': \'https://apps.fedoraproject.org/js/data.js\',\n          \'mimeType\': \'application/javascript\',\n          \'position\': \'bottom-right\',\n      });\n    </script>\n\n  </body>\n</html>\n')
~~~~

Performing the same operation from a web interface results in no response after pressing the "Submit" button.

**Comment by bowlofeggs** [comment]
Hey @ppisar!

This was fixed in https://github.com/fedora-infra/bodhi/pull/3028. Thanks for the report!
