### ISSUE TITLE
Unable to install bodhi-client from PyPI

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-infra/bodhi#3058]
We are using tox for testing hence we need to install everything from PyPI. Unfortunately one cannot install `bodhi-client`:
```
$ podman run -ti fedora:29 bash
[root@4226ed52e67e /]# pip3 install bodhi-client
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting bodhi-client
  Downloading https://files.pythonhosted.org/packages/dd/d9/b4bc9dcfe14a233a125affacd7f5bb5af18474eee44867f30586ec31a47e/bodhi-client-3.13.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/bodhi.egg-info
    writing pip-egg-info/bodhi.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/bodhi.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/bodhi.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    package init file 'bodhi/__init__.py' not found (or not a regular file)
    reading manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    running egg_info
    creating pip-egg-info/bodhi_client.egg-info
    writing pip-egg-info/bodhi_client.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/bodhi_client.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/bodhi_client.egg-info/entry_points.txt
    writing requirements to pip-egg-info/bodhi_client.egg-info/requires.txt
    writing top-level names to pip-egg-info/bodhi_client.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    reading manifest template 'CLIENT_MANIFEST.in'
    writing manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6xld6k4u/bodhi-client/setup.py", line 131, in <module>
        server_packages.remove('bodhi')
    ValueError: list.remove(x): x not in list
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6xld6k4u/bodhi-client/

```

**Comment by TomasTomecek** [comment]
Okay, this is a dupe of https://github.com/fedora-infra/bodhi/issues/2401, feel free to close.

**Comment by bowlofeggs** [comment]
Yeah, let's track this in #2401. Sorry for the troubles!
