### ISSUE TITLE
Gracefully handle releases that don't exist.

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#307]
```
 Unable to determine release from tags      
Traceback (most recent call last):                                                           
  File "/usr/lib/python2.7/site-packages/bodhi/validators.py", line 234, in validate_acls    
    release = Release.from_tags(tags, db)                                                    
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 336, in from_tags     
KeyError: 'f24'                                                                              
```

**Comment by ralphbean** [comment]
Fixed in 9da58bc374
