### ISSUE TITLE
UnboundLocalError: local variable 'key' referenced before assignment in RSS handler

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3227]
Our RSS feed will crash if the requestor sends an invalid query:

```
2019-05-14 14:58:49,638 ERROR [bodhi.server][Dummy-3] Error caught.  Handling HTML response.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/lib/python3.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/viewderivers.py", line 462, in rendered_view
    request, result, view_inst, context)
  File "/usr/lib/python3.7/site-packages/pyramid/renderers.py", line 435, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/lib/python3.7/site-packages/pyramid/renderers.py", line 458, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/lib/python3.7/site-packages/pyramid/renderers.py", line 454, in render
    result = renderer(value, system_values)
  File "/usr/lib/python3.7/site-packages/bodhi/server/renderers.py", line 74, in render
    feed_description = "All %s" % (key)
UnboundLocalError: local variable 'key' referenced before assignment
```

It would be better for it to return a 4xx response instead of a 5xx response when getting invalid RSS requests. In this case, the issue is that the request doesn't contain one of the keys in the big if/else block here:

https://github.com/fedora-infra/bodhi/blob/846bc15a53122908d7bd38c0d2230b7f17d53674/bodhi/server/renderers.py#L55-L66

It might be better to refactor this code to use a dictionary instead of a big if/else, but that's not necessary to solve this issue.

**Comment by bowlofeggs** [comment]
Suggestion: This could be a good opportunity to add mypy/type annotation to this module - mypy catches problems like this.

**Comment by bowlofeggs** [comment]
The fix for this issue is planned for inclusion in Bodhi 4.0.0.
