### ISSUE TITLE
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3235]
The updates handler crashes in staging with this traceback:

```
[INFO fedora_messaging.twisted.protocol] Consuming message from topic org.fedoraproject.stg.bodhi.update.request.testing (message id 3a6faa45-4a80-4cc5-8604-979008f4df03)
[INFO bodhi] Received message from fedora-messaging with topic: org.fedoraproject.stg.bodhi.update.request.testing
[INFO bodhi] Updates Handler handling  FEDORA-2019-f79bd591e7, org.fedoraproject.stg.bodhi.update.request.testing
[INFO bodhi] Got 0 bugs to sync for 'FEDORA-2019-f79bd591e7'
[ERROR fedora_messaging.twisted.protocol] Received unexpected exception from consumer Consumer(queue=bodhi.stg, callback=<bodhi.server.consumers.Consumer object at 0x7f907e9e7da0>)
Traceback (most recent call last):
  File "/usr/lib64/python3.7/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fedora_messaging/twisted/protocol.py", line 239, in _read
    yield threads.deferToThread(consumer.callback, message)
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/__init__.py", line 90, in __call__
    self.updates_handler(msg)
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/updates.py", line 118, in __call__
    self.fetch_test_cases(session, update)
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/updates.py", line 137, in fetch_test_cases
    build.package.fetch_test_cases(session)
  File "/usr/lib/python3.7/site-packages/bodhi/server/models.py", line 1051, in fetch_test_cases
    for test in set(list_categorymembers(wiki, cat_page)):
  File "/usr/lib/python3.7/site-packages/bodhi/server/models.py", line 1031, in list_categorymembers
    response = wiki.call(query)
  File "/usr/lib/python3.7/site-packages/simplemediawiki.py", line 184, in call
    return json.loads(self._fetch_http(self._api_url, params))
  File "/usr/lib/python3.7/site-packages/simplemediawiki.py", line 156, in _fetch_http
    response = self._opener.open(request)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/lib64/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[ERROR fedora_messaging.cli] Unexpected error occurred in consumer Consumer(queue=bodhi.stg, callback=<bodhi.server.consumers.Consumer object at 0x7f907e9e7da0>): <twisted.python.failure.Failure builtins.UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)>
[INFO fedora_messaging.twisted.protocol] Waiting for 0 consumer(s) to finish processing before halting
[INFO fedora_messaging.twisted.protocol] Finished canceling 0 consumers
[INFO twisted] Stopping factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.stg.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
[INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
[INFO twisted] Main loop terminated.
```

We should do two things here:

1. Investigate the cause of the problem. This is likely a bug in the wiki or in the wiki client code.
2. Bodhi should catch this Exception, log, and ignore it.

**Comment by bowlofeggs** [comment]
I think this might actually be a configuration issue. It looks like the wiki_url is invalid in staging. It's unfortunate that an invalid URL raises a UnicodeError…

**Comment by bowlofeggs** [comment]
This ended up being a misconfiguration in Fedora's playbook, and was fixed by https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=eb3be51b785f4a81fbcc9a58707b4e7a4e689b81
