### ISSUE TITLE
Critical path karma threshold/time in testing issue

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#325]
Most likely critical path related
```
[2015-08-22 16:33:17][     bodhi    INFO] Automatically marking 0ad-0.0.18-6.fc23 CGAL-4.6.1-3.fc23 Coin3-3.1.3-11.fc23 Field3D-1.6.1-7.fc23 FlightCrew-0.7.2-18.fc23 FlightGear-3.4.0-6.fc23 FlightGear-Atlas-0.5.0-0.13.cvs20141002.fc23 Maca
ulay2-1.6-15.fc23 MyPasswordSafe-0.6.7-27.20061216.fc23 OpenImageIO-1.5.18-2.fc23 QuantLib-1.6-4.fc23 SimGear-3.4.0-5.fc23 SkyX-0.4-12.fc23 airinv-1.00.1-4.fc23 airrac-1.00.1-3.fc23 airtsp-1.01.2-3.fc23 akonadi-1.13.0-20.fc23 anyterm-1.1.2
9-32.fc23 apt-cacher-ng-0.8.3-4.fc23 aqsis-1.8.2-20.fc23 ardour2-2.8.16-17.fc23 ardour4-4.1.0-3.fc23 asc-2.6.0.0-11.fc23 asio-1.10.6-2.fc23 assimp-3.1.1-3.fc23 autowrap-0.6.1-6.20150209gitd0e9a5.fc23 avogadro-1.1.1-14.fc23 barry-0.18.4-11.
fc23 bastet-0.43.1-8.fc23 bibletime-2.10.1-10.fc23 blender-2.75-4.fc23 blobby-1.0-8.svn1541.fc23 bookkeeper-4.2.1-18.fc23 boost-1.58.0-4.fc23 boost-gdb-printers-5-2.fc23 botan-1.10.9-7.fc23 calamares-1.0.1-6.20150502gita70306e54f505.fc23 c
alligra-2.9.6-4.fc23 cclive-0.9.3-10.fc23 cegui-0.8.4-11.fc23 ceph-0.94.2-4.fc23 clementine-1.2.3-12.fc23 clucene-2.3.3.4-21.20130812.e8e3d20git.fc23 codeblocks-13.12-19.fc23 collada-dom-2.4.3-10.fc23 compat-qpid-cpp-0.24-24.fc23 condor-8.
3.6-2.fc23 console-bridge-0.2.7-6.fc23 crrcsim-0.9.12-17.fc23 csdiff-1.2.3-4.fc23 csound-6.03.2-7.fc23 cups-filters-1.0.71-3.fc23 as stable
[2015-08-22 16:33:17][    fedmsg   ERROR] Problem checking karma thresholds
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 394, in check_karma_thresholds
update.check_karma_thresholds(username=u'bodhi')
File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1560, in check_karma_thresholds
self.set_request(UpdateRequest.stable, username)
File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1000, in set_request
raise BodhiException('. '.join(notes))
BodhiException: This critical path update has not yet been approved for pushing to the stable repository.  It must first reach a karma of 2, consisting of 0 positive karma from proventesters, along with 2 additional karma from the communit
y. Or, it must spend 14 days in testing without any negative feedback

```

**Comment by kalev** [comment]
A lot of F23 critical path updates are currently stuck in updates-testing, probably due to this bug here. When they reach their karma threshold, bodhi prints out the same
```
This critical path update has not yet been approved for pushing to the stable repository.  It must first reach a karma of 2, consisting of 0 positive karma from proventesters, along with 2 additional karma from the community. Or, it must spend 14 days in testing without any negative feedback
```
error and they don't get queued to stable. Manually pressing "Push to Stable" gets this too.

https://lists.fedoraproject.org/pipermail/devel/2015-August/213424.html lists some updates that are currently stuck like this.
