### ISSUE TITLE
KeyError: 'anonymous' - bodhi 3 clients are not compatible with the bodhi 4 server

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#3257]
```
$ bodhi updates query --builds magic-8.2.113-1.fc30
Traceback (most recent call last):
  File "/bin/bodhi", line 11, in <module>
    load_entry_point('bodhi-client==3.14.0', 'console_scripts', 'bodhi')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 234, in wrapper
    method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 582, in query
    print_resp(resp, client)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 1015, in print_resp
    click.echo(client.update_str(resp.updates[0]))
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 892, in update_str
    anonymous = " (unauthenticated)" if comment['anonymous'] else ''
KeyError: 'anonymous'
```

**Comment by mtasaka** [comment]
Working on Fedora 30.

**Comment by bowlofeggs** [comment]
This is due to the Bodhi 3 client not being compatible with the Bodhi 4 server, which is what Fedora Infrastructure is currently hosting.

You can follow [this FESCo ticket](https://pagure.io/fesco/issue/2137) to see what Fedora will do about it (we haven't decided on a plan yet).

**Comment by bowlofeggs** [comment]
You can work around this by using Bodhi from my Copr, or by using Bodhi 4 from Rawhide.

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi
