### ISSUE TITLE
bodhi updates new causes error (F-30)

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#3259]
```
$ bodhi updates new --user mtasaka --request testing --autokarma --stable-karma 2 --unstable-karma -30 --notes "New version 8.2.115 is released" magic-8.2.115-1.fc30
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 413, in new
    print_resp(resp, client)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 1025, in print_resp
    click.echo(client.update_str(resp))
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 892, in update_str
    anonymous = " (unauthenticated)" if comment['anonymous'] else ''
KeyError: 'anonymous'
```

**Comment by bowlofeggs** [comment]
This is the same as #3257.
