### ISSUE TITLE
The update handler should retry when Bugzilla says that another POST changed a bug

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3292]
Bugzilla does not do well when two separate POST requests alter the same bug at the same time. This can happen with Bodhi when users create two updates at once that reference the same bug, which happens often since users can make a single update creation request that makes n updates across different releases.

This is the traceback we get when this happens:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/bugs.py", line 299, in modified
    bug.setstatus('MODIFIED', comment=comment)
  File "/usr/lib/python3.7/site-packages/bugzilla/bug.py", line 197, in setstatus
    return self.bugzilla.update_bugs(self.bug_id, vals)
  File "/usr/lib/python3.7/site-packages/bugzilla/base.py", line 1321, in update_bugs
    return self._proxy.Bug.update(tmp)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
    self)._ServerProxy__request(methodname, params)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 201, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 179, in _request_helper
    return self.parse_response(response)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 154, in parse_response
    return unmarshaller.close()
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 32000: "Red Hat Bugzilla's database reported a query serialization error. Most likely this occurred because another user or process attempted to change the same data that you were attempting to change. Please press Back and retry the transaction. <pre> UPDATE bugs SET lastdiffed = ? WHERE bug_id = ? at /var/www/html/bugzilla/Bugzilla/BugMail.pm line 377. 
```

We should alter our code in ```bugs.py``` so that it retries with ```backoff``` when we receive this error.

**Comment by mattiaverga** [comment]
#3989 should have fixed this
