### ISSUE TITLE
Vagrant box log is filled up by fedora-messaging failure messages

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3312]
When I run bodhi in development mode in its vagrant box, the bodhi log is filled up by the failure of fm-consumer@config.service, thus it's impossible to read:
```
Jun 14 05:50:38 bodhi-dev.example.com systemd[1]: Started Fedora Messaging consumer.
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]: [fedora_messaging.cli INFO] Starting consumer with bodhi.server.consumers:Consumer callback
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]: Traceback (most recent call last):
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/local/bin/fedora-messaging", line 11, in <module>
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     load_entry_point('fedora-messaging', 'console_scripts', 'fedora-messaging')()
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     return self.main(*args, **kwargs)
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 696, in main
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     rv = self.invoke(ctx)
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     return ctx.invoke(self.callback, **ctx.params)
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     return callback(*args, **kwargs)
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/cli.py", line 144, in consume
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     callback, bindings=bindings, queues=queues
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 108, in twisted_consume
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     callback = _check_callback(callback)
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 51, in _check_callback
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     callback_object = callback()
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/home/vagrant/bodhi/bodhi/server/consumers/__init__.py", line 57, in __init__
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     self.composer_handler = ComposerHandler()
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/home/vagrant/bodhi/bodhi/server/consumers/composer.py", line 164, in __init__
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     validate_path(config[setting])
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/home/vagrant/bodhi/bodhi/server/config.py", line 158, in validate_path
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     if not os.path.exists(value):
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:   File "/usr/lib64/python3.7/genericpath.py", line 19, in exists
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]:     os.stat(path)
Jun 14 05:50:40 bodhi-dev.example.com fedora-messaging[11226]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Jun 14 05:50:40 bodhi-dev.example.com systemd[1]: fm-consumer@config.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 05:50:40 bodhi-dev.example.com systemd[1]: fm-consumer@config.service: Failed with result 'exit-code'.
Jun 14 05:50:40 bodhi-dev.example.com systemd[1]: fm-consumer@config.service: Service RestartSec=100ms expired, scheduling restart.
Jun 14 05:50:40 bodhi-dev.example.com systemd[1]: fm-consumer@config.service: Scheduled restart job, restart counter is at 34.
Jun 14 05:50:40 bodhi-dev.example.com systemd[1]: Stopped Fedora Messaging consumer.
```
Is there any setting missing in the example development.ini file that needs to be set? Or is there any setting that will set a maximum number of retry to start fedora-messaging?

**Comment by bowlofeggs** [comment]
On Thu, 2019-06-13 at 22:57 -0700, Mattia Verga wrote:
> Is there any setting missing in the example development.ini file that
> needs to be set? Or is there any setting that will set a maximum
> number of retry to start fedora-messaging?

Ah yes, I bet we are missing a few settings that the composer looks for
upon startup. If you look at the composer's __init__(), there should be
some code that is trying to verify a few settings. We probably just
need to set those in development.ini.example and also have the Ansible
playbook make sure those paths exist in the Vagrant box.

**Comment by mattiaverga** [comment]
I think we could just put
```
compose_dir = %(here)s
compose_stage_dir = %(here)s
```
in development.ini.example, that will fix the issue.

But I'm wondering if the use of `_validate_none_or(str)` as validator in
https://github.com/fedora-infra/bodhi/blob/9be769b4dc53e3bd65d0beb94d6708f97c49e52d/bodhi/server/config.py#L403-L408
is an error, since the None type causes an exception in the code. Should we provide a default in bodhi.server.config and validate a plain string?

**Comment by bowlofeggs** [comment]
On Thu, 2019-06-20 at 09:38 -0700, Mattia Verga wrote:
> But I'm wondering if the use of _validate_none_or(str) as validator
> in
> https://github.com/fedora-infra/bodhi/blob/9be769b4dc53e3bd65d0beb94d6708f97c49e52d/bodhi/server/config.py#L403-L408
> is an error, since the None type causes an exception in the code.
> Should we provide a default in bodhi.server.config and validate a
> plain string?

This is because there isn't a compose path for all of Bodhi's other
server processes (web server, other consumers, and various CLI tools).
All of those can configure these settings to be None. It's only
required to be set for the composer process.

**Comment by nphilipp** [comment]
This one should be fixed in the following commit which is a part of #3246:

https://github.com/fedora-infra/bodhi/pull/3246/commits/b04fe72ea5766e982f06fb9d9a3e8cc8450faf47
