### ISSUE TITLE
fm-consumer starts failing after a few days uptime

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#3365]
After 3 days uptime a updates push fails with: 

```
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:52,999 ERROR [pika.adapters.utils.io_services_utils][f29-updates-testing] _AsyncBaseTransport._consume() failed, aborting connection: error=SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2488)'); sock=<ssl.SSLSocket fd=26, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.5.125.135', 51578)>; Caller's stack:
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: Traceback (most recent call last):
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1222, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     super(_AsyncSSLTransport, self)._consume()
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 791, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return func(*args, **kwargs)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 846, in _sigint_safe_recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return sock.recv(max_bytes)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 1037, in recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self.read(buflen)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 913, in read
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self._sslobj.read(len)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2488)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: Traceback (most recent call last):
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1222, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     super(_AsyncSSLTransport, self)._consume()
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 791, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return func(*args, **kwargs)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 846, in _sigint_safe_recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return sock.recv(max_bytes)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 1037, in recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self.read(buflen)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 913, in read
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self._sslobj.read(len)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2488)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,000 ERROR [pika.adapters.utils.io_services_utils][f29-updates-testing] Wrapped func exited with exception. Caller's stack:
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: Traceback (most recent call last):
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return func(*args, **kwargs)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1222, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     super(_AsyncSSLTransport, self)._consume()
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 791, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return func(*args, **kwargs)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 846, in _sigint_safe_recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return sock.recv(max_bytes)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 1037, in recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self.read(buflen)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 913, in read
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self._sslobj.read(len)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2488)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: Traceback (most recent call last):
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return func(*args, **kwargs)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1222, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     super(_AsyncSSLTransport, self)._consume()
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 791, in _consume
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return func(*args, **kwargs)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 846, in _sigint_safe_recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return sock.recv(max_bytes)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 1037, in recv
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self.read(buflen)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/ssl.py", line 913, in read
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     return self._sslobj.read(len)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2488)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,001 ERROR [pika.adapters.base_connection][f29-updates-testing] connection_lost: StreamLostError: ("Stream connection lost: SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2488)')",)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,006 ERROR [pika.adapters.blocking_connection][f29-updates-testing] Unexpected connection close detected: StreamLostError: ("Stream connection lost: SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2488)')",)
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,006 INFO  [fedora_messaging._session][f29-updates-testing] Resetting connection to rabbitmq.fedoraproject.org
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,098 INFO  [bodhi][f29-updates-testing] Not waiting for a repo signature
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,100 INFO  [bodhi][f29-updates-testing] Creating symlink: /mnt/koji/compose/updates/f29-updates-testing => /mnt/koji/compose/updates/Fedora-29-updates-testing-20190701.0
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,174 INFO  [bodhi][f29-updates-testing] Compose object updated.
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,175 INFO  [bodhi][f29-updates-testing] Waiting for updates to hit the master mirror
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,239 INFO  [bodhi][f29-updates-testing] Compose object updated.
Jul 01 10:45:53 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:45:53,251 INFO  [bodhi][f29-updates-testing] Polling http://download01.phx2.fedoraproject.org/pub/fedora/linux/updates/testing/29/Everything/aarch64/repodata/repomd.xml
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:49:13,377 INFO  [bodhi][f29-updates-testing] Polling http://download01.phx2.fedoraproject.org/pub/fedora/linux/updates/testing/29/Everything/aarch64/repodata/repomd.xml
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: 2019-07-01 10:49:13,387 ERROR [bodhi][f29-updates-testing] Error fetching repomd.xml
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: Traceback (most recent call last):
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/composer.py", line 1305, in _wait_for_sync
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     newsum = hashlib.sha1(masterrepomd.read()).hexdigest()
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/http/client.py", line 470, in read
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     s = self._safe_read(self.length)
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:   File "/usr/lib64/python3.7/http/client.py", line 622, in _safe_read
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]:     raise IncompleteRead(b''.join(s), amt)
Jul 01 10:49:13 bodhi-backend01.phx2.fedoraproject.org fedora-messaging[105797]: http.client.IncompleteRead: IncompleteRead(5464 bytes read, 3 more expected)
```

simply resuming seems to result in the same error, but restarting and then resuming works... so I think there's some kind of state here that gets stuck.

**Comment by cverna** [comment]
I think this has been solved with the latest fedora-messaging release
