### ISSUE TITLE
Gracefully private bugs using the new caveats API.

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#344]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/services/updates.py", line 340, in new_update
    result, _caveats = Update.edit(request, data)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 767, in edit
    new_bugs = up.update_bugs(data['bugs'])
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1277, in update_bugs
    newbug = bugtracker.getbug(bug_id)
  File "/usr/lib/python2.7/site-packages/bodhi/bugs.py", line 61, in getbug
    return self.bz.getbug(bug_id)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1042, in getbug
    exclude_fields=exclude_fields, extra_fields=extra_fields)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1035, in _getbug
    extra_fields=extra_fields)[0]
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1007, in _getbugs
    r = self._proxy.Bug.get(getbugdata)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 263, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 245, in _request_helper
    raise sys.exc_info()[1]
Fault: <Fault 102: 'You are not authorized to access bug #1253789. Most likely the bug has been restricted for internal
 development processes and we cannot grant access. If you are a Red Hat customer with an active subscription, please vi
sit the Red Hat Customer Portal for assistance with your issue If you are a Fedora Project user and require assistance,
 please consider using one of the mailing lists we host for the Fedora Project.'>

```

**Comment by ralphbean** [comment]
:+1:

**Comment by ralphbean** [comment]
Question for you @lmacken.  When handling these, what's the appropriate course of action?  Should we allow the bug to be associated in bodhi at all?  If its private, bodhi will never be able to comment on it.. so we could just leave it off.

On the other hand, someone might want bodhi to know about the bug even if it cannot modify it so there's that record there.  That's more of a PITA for us since now we have to handle those failures all over the place (everywhere bodhi tries to go back and update the bug).

**Comment by jasontibbitts** [comment]
Really bodhi shouldn't even let you enter a private bug.  I know it doesn't show them in the completion list (because it can't see them) but if you add them manually, you get an announcement, sent out to however many thousands of people, with a link they can't view.  Take FEDORA-2016-b4b42c9157, for example, which references https://bugzilla.redhat.com/show_bug.cgi?id=1262954.

**Comment by nirik** [comment]
I agree, we should try and have bodhi reject private bugs from being attached at all IMHO.

**Comment by ralphbean** [comment]
A point of information:

In order to make things faster, at one point we disconnected "querying bugzilla for info about a bug" and "the initial request made to bodhi".  So, when you punch in a bug number, the bodhi webapp just says "OK, whatever".  It then publishes a fedmsg message saying that you've created a new update.  We have a fedmsg listener on `bodhi-backend02` that receives that message and says: "ok, for each of these bug numbers, I'll go out to bugzilla.rh.com and get more info on each bug, like the summary, etc."  It then stores those in the DB so that people looking at the frontend get more info on each bug.

So, given that arrangement.. where should we perform "rejection" of private bugs?  It seems to me the only place to do it is on `bodhi-backend02`.  When it tries to get more info, it could check and see that the bug is private and then it could _detach_ the bug from the update at that point.  The only issue with that is that there would be no trace that it was removed.. and no notification to the updater submitter to tell them that they erroneously tried to attach a private bug.

**Comment by nirik** [comment]
Well, dropping a private bug then would be the same as if they input a non existent bug right? 
So i'd be fine just dropping it on bodhi-backend02 when it looks, but I suppose we could try and get more complex/clever and somehow notify the submitter. Perhaps just drop short term and come up with a better way to notify later?

**Comment by bowlofeggs** [comment]
Another option could be to mark the bug as being private in Bodhi's database, and then we can render the bug with a label that indicates that it is private.

**Comment by mattiaverga** [comment]
The commit I referenced above will be part of a PR which should implement some checks when a user manually add bug IDs in the new update form from the GUI. Unfortunately bugzilla doesn't send `Access-Control-Allow-Headers: *` header, so the jquery call to it actually fails (it can however be tested by using a browser addon like CorsE for Firefox which fakes CORS headers).
I've opened a request to bugzilla guys, but it seems it will not be fixed so early: https://bugzilla.redhat.com/show_bug.cgi?id=1641232
Alternatives could be implement our own script which uses python-bugzilla to get bug details and then provide them to the ajax query, or modify the bugzilla connector in fedora-packages to accept filtering not only for packages, but also for bug ID.

I will try to work on something for managing the handling of private bugs in backend to have this fixed also for CLI.

**Comment by mattiaverga** [comment]
@bowlofeggs following your suggestion, I created a commit at https://github.com/mattiaverga/bodhi/commit/773ef7323a44fdf3764787470293c9ab54b96ff1 which adds a column to the bugs table and sets the bug to be private.
While creating the new column, I've set all the existing bugs to "private=FALSE"... but assuming all the existing bugs with title "Invalid bug number" are private, should I set the flag to TRUE for those?

I'm not able to fully test it locally in my vagrant box because every time I try to create a new update bodhi says I don't have commit rights to do so. Is there any setting that can enable me to test that?

How do you suggest to render those private bugs on web GUI? What about this mockup:
![immagine](https://user-images.githubusercontent.com/17218209/47967837-22333c00-e062-11e8-84f4-bf154c8ff3e6.png)
I think we can maintain karma buttons and URL link because they can be useful to the bug submitter and to the package maintainer.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in Bodhi 3.13: #2917.
