### ISSUE TITLE
override request with multiple package makes client crash

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#3534]
```
[mtasaka@localhost ~]$ rpm -q bodhi-client
bodhi-client-4.1.0-3.fc31.noarch
[mtasaka@localhost ~]$ bodhi overrides save --user mtasaka --duration 4 --notes "ruby-gnome suite 3.3.8 stage 2" "rubygem-gobject-introspection-3.3.8-1.fc30 rubygem-cairo-gobject-3.3.8-1.fc30"
mtasaka's rubygem-gobject-introspection-3.3.8-1.fc30 override (expires 2019-10-08 02:32:48)
mtasaka's rubygem-cairo-gobject-3.3.8-1.fc30 override (expires 2019-10-08 02:32:48)
Caveats:
Your override submission was split into 2.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/munch/__init__.py", line 102, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Munch' object has no attribute 'build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/munch/__init__.py", line 105, in __getattr__
    return self[k]
KeyError: 'build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/bodhi", line 11, in <module>
    load_entry_point('bodhi-client==4.1.0', 'console_scripts', 'bodhi')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 257, in wrapper
    method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 969, in save_buildroot_overrides
    **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 290, in _save_override
    command = _generate_wait_repo_command(resp, client)
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 1013, in _generate_wait_repo_command
    if 'release_id' in override.build:
  File "/usr/lib/python3.7/site-packages/munch/__init__.py", line 107, in __getattr__
    raise AttributeError(k)
AttributeError: build
```

**Comment by richardgreg** [comment]
@cverna Or this issue since it's got the `outreachy` label on it.

**Comment by richardgreg** [comment]
@cverna I'm wondering how one goes about recreating this error in the development environment.

Is there any toy username and password that can be used in the dev environment?

**Comment by AnchalJain** [comment]
@cverna I started working on this issue

**Comment by richardgreg** [comment]
@AnchalJain if you could pick another issue I've started working on this :)

**Comment by AnchalJain** [comment]
@richardgreg actually, I am working on this issue from the start. I requested @cverna to open a new issue. If you want, you can ask him. I am sure there is another beginner issues present. hope you understand :)

**Comment by richardgreg** [comment]
Okay @AnchalJain. Next time you can request Clement to assign you to the issue you're interested in so we all know you're on it. :)
