### ISSUE TITLE
Trying to edit an update that was created before the 5.0 release makes bodhi crash.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3576]
In staging while trying to edit an old update via the UI, bodhi returns a 500.

```
500 Internal Server Error

Traceback (most recent call last): File "/usr/lib/python3.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python3.7/site-packages/mako/template.py", line 482, in render_unicode self, self.callable_, args, data, as_unicode=True File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render **_kwargs_for_callable(callable_, data) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 125, in render_body File "/usr/local/lib/python3.7/site-packages/bodhi/server/templates/new_update.html", line 193, in render_body
AttributeError: 'NoneType' object has no attribute 'long_name' 
```

**Comment by ryanlerch** [comment]
It looks like (for some reason), this build does not have a release object associated with it -- which is causing the crash here.

Looks like the config not being setup properly in staging for f32 may have caused this. Is this something i should account for in the template? or just put it down to staging somehow getting into this weird state.
