### ISSUE TITLE
Push to Stable: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#3646]
1. go to https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-9ae6540f19 (and log in if you aren't)
 2. in the top rigth corner, roll down the menu that says "testing -> stable"
 3. click "Push to Stable" (why is that option even present?)
 4. error popup rolls from the lower right corner, saying: 'NoneType' object is not subscriptable

![_](https://user-images.githubusercontent.com/2401856/67501777-23031a80-f685-11e9-85ec-9b8353f87095.png)

**Comment by hroncok** [comment]
Also

https://bodhi.stg.fedoraproject.org/updates/FEDORA-EPEL-2019-641c235213 -> click edit ->

```
500 Internal Server Error
Traceback (most recent call last): File "/usr/lib/python3.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python3.7/site-packages/mako/template.py", line 482, in render_unicode self, self.callable_, args, data, as_unicode=True File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render **_kwargs_for_callable(callable_, data) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 125, in render_body File "/usr/local/lib/python3.7/site-packages/bodhi/server/templates/new_update.html", line 193, in render_body${build.nvr}File "/usr/local/lib/python3.7/site-packages/bodhi/server/models.py", line 1459, in get_build_id return self._get_kojiinfo()['id'] TypeError: 'NoneType' object is not subscriptable
```

![_](https://user-images.githubusercontent.com/2401856/67555777-3f00cd80-f712-11e9-9b8a-a9909673812e.png)

**Comment by ryanlerch** [comment]
> Also
> 
> https://bodhi.stg.fedoraproject.org/updates/FEDORA-EPEL-2019-641c235213 -> click edit ->
> 
> ```
> 500 Internal Server Error
> Traceback (most recent call last): File "/usr/lib/python3.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python3.7/site-packages/mako/template.py", line 482, in render_unicode self, self.callable_, args, data, as_unicode=True File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render **_kwargs_for_callable(callable_, data) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 125, in render_body File "/usr/local/lib/python3.7/site-packages/bodhi/server/templates/new_update.html", line 193, in render_body${build.nvr}File "/usr/local/lib/python3.7/site-packages/bodhi/server/models.py", line 1459, in get_build_id return self._get_kojiinfo()['id'] TypeError: 'NoneType' object is not subscriptable
> ```
> 
> ![_](https://user-images.githubusercontent.com/2401856/67555777-3f00cd80-f712-11e9-9b8a-a9909673812e.png)

I think this one may be a different issue...

**Comment by mattiaverga** [comment]
The errors on the epel-rpm-macros packages are due to the missing `.el7` in the release field:
```
>>> bb = m.Build.query.filter_by(nvr='epel-rpm-macros-7-21').all()
>>> bu = bb[0]
>>> bu.get_n_v_r()
('epel-rpm-macros', '7', '21')
>>> bu.get_build_id()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/bodhi/bodhi/server/models.py", line 1459, in get_build_id
    return self._get_kojiinfo()['id']
  File "/home/vagrant/bodhi/bodhi/server/models.py", line 1376, in _get_kojiinfo
    self._kojiinfo = koji_session.getBuild(self.nvr)
  File "/home/vagrant/bodhi/bodhi/server/buildsys.py", line 60, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vagrant/bodhi/bodhi/server/buildsys.py", line 271, in getBuild
    raise ValueError("Couldn't determine dist for build '%s'" % build)
ValueError: Couldn't determine dist for build 'epel-rpm-macros-7-21'
```
https://github.com/fedora-infra/bodhi/blob/2a7b5a8c7c08b0107b7d413809459b4f0bf8ec85/bodhi/server/buildsys.py#L209-L271


The error in the original report must have a different cause:
```
>>> bb = m.Build.query.filter_by(nvr='python38-3.8.0~b3-1.fc29').all()
>>> bu = bb[0]
>>> bu.get_n_v_r()
('python38', '3.8.0~b3', '1.fc29')
>>> bu.get_build_id()
16058
```

**Comment by mattiaverga** [comment]
https://github.com/fedora-infra/bodhi/blob/2a7b5a8c7c08b0107b7d413809459b4f0bf8ec85/bodhi/server/models.py#L1376
Using `koji_session.getBuild(self.nvr, strict=True`) may give us more evidence of what's going on, otherwise Koji just returns `None`.

**Comment by cverna** [comment]
This can actually be close, the problem is that bodhi in staging is using a db dump of the production database. Meaning that updates have links to builds that have been built in koji production but not in koji staging.

The link to the build in the staging update is https://koji.stg.fedoraproject.org/koji/search?terms=python38-3.8.0~b3-1.fc29&type=build&match=glob which returns no build.

**Comment by mattiaverga** [comment]
@cverna note that there could be also a problem with our dummy buildsystem we use in dev, some builds like epel-rpm-macros-7-21 have a release that is not correctly recognized because it lacks the `.el7` or something similar at the end:
```
>>> bb = m.Build.query.filter_by(nvr='epel-rpm-macros-7-21').all()
>>> bu = bb[0]
>>> bu.get_n_v_r()
('epel-rpm-macros', '7', '21')
>>> bu.get_build_id()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/bodhi/bodhi/server/models.py", line 1459, in get_build_id
    return self._get_kojiinfo()['id']
  File "/home/vagrant/bodhi/bodhi/server/models.py", line 1376, in _get_kojiinfo
    self._kojiinfo = koji_session.getBuild(self.nvr)
  File "/home/vagrant/bodhi/bodhi/server/buildsys.py", line 60, in wrapper
    return func(self, *args, **kwargs)
  File "/home/vagrant/bodhi/bodhi/server/buildsys.py", line 271, in getBuild
    raise ValueError("Couldn't determine dist for build '%s'" % build)
ValueError: Couldn't determine dist for build 'epel-rpm-macros-7-21'
```
https://github.com/fedora-infra/bodhi/blob/2a7b5a8c7c08b0107b7d413809459b4f0bf8ec85/bodhi/server/buildsys.py#L209-L271
