### ISSUE TITLE
500 error when editing some updates

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#3661]
Also

https://bodhi.stg.fedoraproject.org/updates/FEDORA-EPEL-2019-641c235213 -> click edit ->

```
500 Internal Server Error
Traceback (most recent call last): File "/usr/lib/python3.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python3.7/site-packages/mako/template.py", line 482, in render_unicode self, self.callable_, args, data, as_unicode=True File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render **_kwargs_for_callable(callable_, data) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 125, in render_body File "/usr/local/lib/python3.7/site-packages/bodhi/server/templates/new_update.html", line 193, in render_body${build.nvr}File "/usr/local/lib/python3.7/site-packages/bodhi/server/models.py", line 1459, in get_build_id return self._get_kojiinfo()['id'] TypeError: 'NoneType' object is not subscriptable
```

![_](https://user-images.githubusercontent.com/2401856/67555777-3f00cd80-f712-11e9-9b8a-a9909673812e.png)

_Originally posted by @hroncok in https://github.com/fedora-infra/bodhi/issues/3646#issuecomment-546257339_

**Comment by ryanlerch** [comment]
Just out of interest, what kind of build is attached to that update? It is listed as an RPM, but does not have a proper NVR...

**Comment by hroncok** [comment]
It does. It just doesn't have %dist. Like fedora-release or fedora-obsolete-packages.

**Comment by cverna** [comment]
Ok so I think this is due to stg, the build referenced in the update is not available in stg koji.

https://koji.stg.fedoraproject.org/koji/search?terms=epel-rpm-macros-7-21&type=build&match=glob

Let's close this
