### ISSUE TITLE
Gracefully handle attempts to resume a push when one doesn't exist

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#37]
```python
[bodhi.masher] ERROR 2014-03-11 20:12:20,694 Trying to resume a push, yet /mnt/koji/mash/updates/MASHING-FEDORA doesn't exist!
[cherrypy.msg] INFO 2014-03-11 20:12:20,766 HTTP: Page handler: <function _wrapper at 0x7f1c07078320>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/CherryPy-2.3.0-py2.6.egg/cherrypy/_cphttptools.py", line 121, in _run
    self.main()
  File "/usr/lib/python2.6/site-packages/CherryPy-2.3.0-py2.6.egg/cherrypy/_cphttptools.py", line 264, in main
    body = page_handler(*virtual_path, **self.params)
  File "/usr/lib/python2.6/site-packages/turbogears/identity/conditions.py", line 262, in _wrapper
    return fn(*args, **kw)
  File "<string>", line 3, in mash
  File "/usr/lib/python2.6/site-packages/turbogears/controllers.py", line 361, in expose
    *args, **kw)
  File "<generated code>", line 0, in run_with_transaction
  File "/usr/lib/python2.6/site-packages/peak/rules/core.py", line 153, in __call__
    return self.body(*args, **kw)
  File "/usr/lib/python2.6/site-packages/turbogears/database.py", line 410, in so_rwt
    retval = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/turbogears/controllers.py", line 244, in _expose
    @abstract()
  File "<generated code>", line 0, in _expose
  File "/usr/lib/python2.6/site-packages/peak/rules/core.py", line 153, in __call__
    return self.body(*args, **kw)
  File "/usr/lib/python2.6/site-packages/turbogears/controllers.py", line 255, in <lambda>
    False, {}, args, kw))
  File "/usr/lib/python2.6/site-packages/turbogears/controllers.py", line 425, in _execute_func
    output = errorhandling.try_call(func, *args, **kw)
  File "/usr/lib/python2.6/site-packages/turbogears/errorhandling.py", line 77, in try_call
    return func(self, *args, **kw)
  File "<string>", line 3, in mash
  File "/usr/lib/python2.6/site-packages/turbogears/controllers.py", line 207, in validate
    return errorhandling.run_with_errors(errors, func, *args, **kw)
  File "/usr/lib/python2.6/site-packages/turbogears/errorhandling.py", line 118, in run_with_errors
    return func(self, *args, **kw)
  File "/usr/lib/python2.6/site-packages/bodhi/admin.py", line 165, in mash
    resume=resume)
  File "/usr/lib/python2.6/site-packages/bodhi/util.py", line 154, in new
    return f(*args, **kw)
  File "/usr/lib/python2.6/site-packages/bodhi/masher.py", line 88, in queue
    self._mash(self._queue.pop())
  File "/usr/lib/python2.6/site-packages/bodhi/masher.py", line 110, in _mash
    thread = MashTask(task[0], task[1], task[2], task[3])
  File "/usr/lib/python2.6/site-packages/bodhi/masher.py", line 216, in __init__
    self._lock()
  File "/usr/lib/python2.6/site-packages/bodhi/masher.py", line 271, in _lock
    raise MashTaskException(msg)
MashTaskException: Trying to resume a push, yet /mnt/koji/mash/updates/MASHING-FEDORA doesn't exist!

[turbogears.access] INFO 2014-03-11 20:12:20,768 ::1 - parasense [11/Mar/2014:20:12:20 +0000] "POST /updates/admin/mash HTTP/1.1" 500 791 "" "Fedora Bodhi Client/0.5.1"
```

**Comment by ralphbean** [comment]
@lmacken, it seems like a lot of progress was made on this.  Can it be called "done"?

**Comment by lmacken** [comment]
Yep, when we run `bodhi-push --resume`, it iterates over all of the `/mnt/koji/mash/updates/MASHING-*` state files.
