### ISSUE TITLE
fedpkg update failed

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#376]
```
$ fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  rubygem-apipie-bindings-0.0.14-1.fc23
Password for vondruch:
Creating a new update for  rubygem-apipie-bindings-0.0.14-1.fc23
/usr/lib/python2.7/site-packages/fedora/client/bodhi.py:139: UserWarning: Parameter "type_" is deprecated. Please use "type" instead.
  warnings.warn('Parameter "type_" is deprecated. Please use "type" instead.')
ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 142, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 374, in send_request
    {'url': to_bytes(method), 'err': to_bytes(e)})
ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Could not generate update request: Command 'bodhi --new --release f23 --file bodhi.template rubygem-apipie-bindings-0.0.14-1.fc23 --username vondruch' returned non-zero exit status 255
```

**Comment by voxik** [comment]
I was using python-fedora-0.5.3-1.fc22.noarch at that time if that makes any difference. I updated to 0.5.5 but create the update via web interface in the mean time, so dunno if that could make any difference

**Comment by lmacken** [comment]
Yeah, you needed `python-fedora-0.5.5` for `fedpkg update` to work.

**Comment by ralphbean** [comment]
This is almost certainly fixed by python-fedora-0.5.5.  Please re-open if you hit it again.

**Comment by voxik** [comment]
So no ... update to python-fedora-0.5.5 did not help:

~~~
$ fedpkg update 
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  rubygem-pg-0.18.2-1.fc23 
Password for vondruch: 
Creating a new update for  rubygem-pg-0.18.2-1.fc23 
ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 96, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 170, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 374, in send_request
    {'url': to_bytes(method), 'err': to_bytes(e)})
ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Could not generate update request: Command 'bodhi --new --release f23 --file bodhi.template rubygem-pg-0.18.2-1.fc23 --username vondruch' returned non-zero exit status 255
[vondruch@unused-4-232 rubygem-pg (f23 %)]$ rpm -q python-fedora
python-fedora-0.5.5-1.fc22.noarch
~~~

**Comment by voxik** [comment]
I have not filled any bz ticket number ... might that be the case for example? Otherwise I can't see anything specific about this update.

**Comment by voxik** [comment]
I have tried once again with BZ ticket number and it passed. So my conclusion is that if some information is missing from the template, the Bodhi will reject the submission, although update without BZ ticket should be perfectly valid.

**Comment by ryanlerch** [comment]
This issue seems to be filed against the old version of Bodhi CLI. Are you still encountering this issue with the new bodhi2 CLI -- i.e. the command is now `bodhi updates new`.
