### ISSUE TITLE
The signed handler can't handle messages about a build not linked to an update

### ISSUE THREAD

**Issue by abompard** [fedora-infra/bodhi#3777]
I'm getting a lot of these errors by email:
```
2019-11-18 10:08:12,382 ERROR [bodhi][PoolThread-twisted.internet.reactor-0] 'NoneType' object has no attribute 'from_tag': Unable to handle message in Signed handler: Id: c8282975-ddb9-4b91-a2fe-ae3e1d851331
Topic: org.fedoraproject.prod.buildsys.tag
Headers: {
    "fedora_messaging_schema": "base.message",
    "fedora_messaging_severity": 20,
    "sent-at": "2019-11-15T19:54:03+00:00"
}
Body: {
    "build_id": 1413272,
    "instance": "primary",
    "name": "erlang-p1_utils",
    "owner": "bowlofeggs",
    "release": "1.fc31",
    "tag": "f31-override",
    "tag_id": 6447,
    "user": "bodhi",
    "version": "1.0.16"

}
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/__init__.py", line 79, in __call__
    handler_info.handler(msg)
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/signed.py", line 92, in __call__
    if build.update.from_tag:
AttributeError: 'NoneType' object has no attribute 'from_tag'
```

**Comment by cverna** [comment]
Fixed by https://github.com/fedora-infra/bodhi/pull/3720
