### ISSUE TITLE
Updates submitted in rawhide from side tags do not close bug

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#3832]
https://bodhi.fedoraproject.org/updates/FEDORA-2019-f1bbf03a7c

I am pretty sure I have set "close bugs on stable", but the bugs were not closed and I had to close them manually.

**Comment by cverna** [comment]
Might be related but we have some traceback in the celery worker. This needs more investigation.

```
[2019-12-06 11:25:02,404: ERROR/ForkPoolWorker-1] Got fault from Bugzilla on #1749399: fault code: 32000, fault string: Red Hat Bugzilla's database reported a query serialization error. Most likely this occurred because another user or process attempted to change the same data that you were attempting to change. Please press Back and retry the transaction. <pre> UPDATE bugs SET lastdiffed = ? WHERE bug_id = ? at /var/www/html/bugzilla/Bugzilla/BugMail.pm line 377. Bugzilla::BugMail::Send(1749399, 'HASH(0x55eec1cabed0)', 'HASH(0x55eed06cfdd8)') called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1822 Bugzilla::Bug::_send_bugmail('HASH(0x55eed06cfdd8)', undef) called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1730 Bugzilla::Bug::send_changes('Bugzilla::Bug=HASH(0x55eed01744e8)', 'HASH(0x55eecfedaa08)', undef, 0) called at /var/www/html/bugzilla/Bugzilla/WebService/Bug.pm line 852 Bugzilla::WebService::Bug::update('Bugzilla::WebService::Bug', 'HASH(0x55eecf616d68)') called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2875 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2860 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2826 SOAP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x55eecfb21290)', '<?xml version=\'1.0\'?>\x{a}<methodCall>\x{a}<methodName>Bug.update</...') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 438 SOAP::Transport::HTTP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x55eecfb21290)') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 831 SOAP::Transport::HTTP::Apache::handler('Bugzilla::WebService::Server::XMLRPC=HASH(0x55eecfb21290)') called at /var/www/html/bugzilla/xmlrpc.cgi line 44 ModPerl::ROOT::Bugzilla::ModPerl::ResponseHandler::var_www_html_bugzilla_xmlrpc_2ecgi::handler('Apache2::RequestRec=SCALAR(0x55eed0209fc0)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 eval {...} called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 ModPerl::RegistryCooker::run('Bugzilla::ModPerl::ResponseHandler=HASH(0x55eecfb104d8)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 173 ModPerl::RegistryCooker::default_handler('Bugzilla::ModPerl::ResponseHandler=HASH(0x55eecfb104d8)') called at /usr/lib64/perl5/vendor_perl/ModPerl/Registry.pm line 32 ModPerl::Registry::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x55eed0209fc0)') called at /var/www/html/bugzilla/mod_perl.pl line 139 Bugzilla::ModPerl::ResponseHandler::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x55eed0209fc0)') called at -e line 0 eval {...} called at -e line 0 </pre>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/bugs.py", line 288, in modified
    bug.setstatus('MODIFIED', comment=comment)
  File "/usr/lib/python3.7/site-packages/bugzilla/bug.py", line 197, in setstatus
    return self.bugzilla.update_bugs(self.bug_id, vals)
  File "/usr/lib/python3.7/site-packages/bugzilla/base.py", line 1326, in update_bugs
    return self._proxy.Bug.update(tmp)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
    self)._ServerProxy__request(methodname, params)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 202, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 180, in _request_helper
    return self.parse_response(response)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 154, in parse_response
    return unmarshaller.close()
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 32000: "Red Hat Bugzilla's database reported a query serialization error. Most likely this occurred because another user or process attempted to change the same data that you were attempting to change. Please press Back and retry the transaction. <pre> UPDATE bugs SET lastdiffed = ? WHERE bug_id = ? at /var/www/html/bugzilla/Bugzilla/BugMail.pm line 377. Bugzilla::BugMail::Send(1749399, 'HASH(0x55eec1cabed0)', 'HASH(0x55eed06cfdd8)') called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1822 Bugzilla::Bug::_send_bugmail('HASH(0x55eed06cfdd8)', undef) called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1730 Bugzilla::Bug::send_changes('Bugzilla::Bug=HASH(0x55eed01744e8)', 'HASH(0x55eecfedaa08)', undef, 0) called at /var/www/html/bugzilla/Bugzilla/WebService/Bug.pm line 852 Bugzilla::WebService::Bug::update('Bugzilla::WebService::Bug', 'HASH(0x55eecf616d68)') called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2875 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2860 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2826 SOAP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x55eecfb21290)', '<?xml version=\\'1.0\\'?>\\x{a}<methodCall>\\x{a}<methodName>Bug.update</...') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 438 SOAP::Transport::HTTP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x55eecfb21290)') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 831 SOAP::Transport::HTTP::Apache::handler('Bugzilla::WebService::Server::XMLRPC=HASH(0x55eecfb21290)') called at /var/www/html/bugzilla/xmlrpc.cgi line 44 ModPerl::ROOT::Bugzilla::ModPerl::ResponseHandler::var_www_html_bugzilla_xmlrpc_2ecgi::handler('Apache2::RequestRec=SCALAR(0x55eed0209fc0)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 eval {...} called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 ModPerl::RegistryCooker::run('Bugzilla::ModPerl::ResponseHandler=HASH(0x55eecfb104d8)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 173 ModPerl::RegistryCooker::default_handler('Bugzilla::ModPerl::ResponseHandler=HASH(0x55eecfb104d8)') called at /usr/lib64/perl5/vendor_perl/ModPerl/Registry.pm line 32 ModPerl::Registry::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x55eed0209fc0)') called at /var/www/html/bugzilla/mod_perl.pl line 139 Bugzilla::ModPerl::ResponseHandler::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x55eed0209fc0)') called at -e line 0 eval {...} called at -e line 0 </pre>">
```

**Comment by mattiaverga** [comment]
I think this was fixed long ago (at least, it seems to work now), so I'm going to close the ticket. Feel free to reopen if needed.
