### ISSUE TITLE
Modular testing compose are failing

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3852]
The modular composes that pushes updates to testing have been failing with the following trace back.

```
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,123: ERROR/ForkPoolWorker-27] Wrapped func exited with exception. Caller's stack:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return func(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1295, in _produce
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     super(_AsyncSSLTransport, self)._produce()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 820, in _produce
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self._tx_buffers[0])
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return func(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return sock.send(data)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/ssl.py", line 1003, in send
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return self._sslobj.write(data)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: BrokenPipeError: [Errno 32] Broken pipe
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return func(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1295, in _produce
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     super(_AsyncSSLTransport, self)._produce()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 820, in _produce
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self._tx_buffers[0])
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return func(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return sock.send(data)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/ssl.py", line 1003, in send
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     return self._sslobj.write(data)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: BrokenPipeError: [Errno 32] Broken pipe
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,124: INFO/ForkPoolWorker-27] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=BrokenPipeError(32, 'Broken pipe'); <ssl.SSLSocket fd=170, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.5.125.135', 38620)>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,124: INFO/ForkPoolWorker-27] Deactivating transport: state=1; <ssl.SSLSocket fd=170, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.5.125.135', 38620)>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,124: ERROR/ForkPoolWorker-27] connection_lost: StreamLostError: ("Stream connection lost: BrokenPipeError(32, 'Broken pipe')",)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,124: INFO/ForkPoolWorker-27] AMQP stack terminated, failed to connect, or aborted: error-arg=StreamLostError: ("Stream connection lost: BrokenPipeError(32, 'Broken pipe')",); pending-error=None
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,125: INFO/ForkPoolWorker-27] Stack terminated due to StreamLostError: ("Stream connection lost: BrokenPipeError(32, 'Broken pipe')",)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,125: INFO/ForkPoolWorker-27] Closing transport socket and unlinking: state=2; <ssl.SSLSocket fd=170, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.5.125.135', 38620)>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,126: ERROR/ForkPoolWorker-27] Unexpected connection close detected: StreamLostError: ("Stream connection lost: BrokenPipeError(32, 'Broken pipe')",)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,126: INFO/ForkPoolWorker-27] Resetting connection to rabbitmq.fedoraproject.org
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,146: INFO/ForkPoolWorker-27] Pika version 1.0.1 connecting to ('10.5.126.8', 5671)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,151: INFO/ForkPoolWorker-27] Socket connected: <socket.socket fd=166, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.5.125.135', 44090), raddr=('10.5.126.8', 5671)>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,174: INFO/ForkPoolWorker-27] SSL handshake completed successfully: <ssl.SSLSocket fd=166, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.5.125.135', 44090), raddr=('10.5.126.8', 5671)>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,174: INFO/ForkPoolWorker-27] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f0414872c10>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f0414872c10> params=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>>).
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,204: INFO/ForkPoolWorker-27] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f0414872c10> params=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,205: INFO/ForkPoolWorker-27] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f0414872c10> params=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,205: INFO/ForkPoolWorker-27] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f0414872c10> params=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>>
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,205: INFO/ForkPoolWorker-27] Created channel=1
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,245: INFO/ForkPoolWorker-27] Updating update statuses.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,518: ERROR/ForkPoolWorker-27] Exception in ComposerThread(f31-modular-updates-testing)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 397, in work
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.save_state(ComposeState.notifying)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 509, in save_state
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.db.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.transaction.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.session.dispatch.after_commit(self.session)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     fn(*args, **kw)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/notifications.py", line 46, in send_messages_after_commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     _publish_with_retry(m)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/backoff/_sync.py", line 99, in retry
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     ret = target(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/notifications.py", line 86, in _publish_with_retry
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     api.publish(message)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 246, in publish
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     _session_cache.session.publish(message, exchange=exchange)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/_session.py", line 150, in publish
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     message.validate()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/message.py", line 569, in validate
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     jsonschema.validate(self.body, schema)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     raise error
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: jsonschema.exceptions.ValidationError: None is not of type 'integer'
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Failed validating 'type' in schema['properties']['artifact']['properties']['builds']['items']['properties']['task_id']:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     {'description': 'Task ID of the koji build.', 'type': 'integer'}
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: On instance['artifact']['builds'][0]['task_id']:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     None
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,519: INFO/ForkPoolWorker-27] Thread(f31-modular-updates-testing) finished.  Success: False
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,543: ERROR/ForkPoolWorker-27] An Exception was raised while rolling back a transaction.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 397, in work
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.save_state(ComposeState.notifying)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 509, in save_state
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.db.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.transaction.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.session.dispatch.after_commit(self.session)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     fn(*args, **kw)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/notifications.py", line 46, in send_messages_after_commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     _publish_with_retry(m)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/backoff/_sync.py", line 99, in retry
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     ret = target(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/notifications.py", line 86, in _publish_with_retry
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     api.publish(message)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 246, in publish
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     _session_cache.session.publish(message, exchange=exchange)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/_session.py", line 150, in publish
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     message.validate()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/message.py", line 569, in validate
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     jsonschema.validate(self.body, schema)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     raise error
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: jsonschema.exceptions.ValidationError: None is not of type 'integer'
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Failed validating 'type' in schema['properties']['artifact']['properties']['builds']['items']['properties']['task_id']:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     {'description': 'Task ID of the koji build.', 'type': 'integer'}
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: On instance['artifact']['builds'][0]['task_id']:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     None
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: During handling of the above exception, another exception occurred:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/util.py", line 903, in __call__
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     yield session
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 324, in run
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.work()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 429, in work
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.save_state()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 509, in save_state
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.db.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.transaction.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 492, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self._assert_active(prepared_ok=True)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     "This session is in 'committed' state; no further "
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: sqlalchemy.exc.InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: During handling of the above exception, another exception occurred:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/util.py", line 910, in __call__
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     session.rollback()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 991, in rollback
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.transaction.rollback()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 510, in rollback
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self._assert_active(prepared_ok=True, rollback_ok=True)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     "This session is in 'committed' state; no further "
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: sqlalchemy.exc.InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,582: INFO/ForkPoolWorker-27] Compose object updated.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,587: ERROR/ForkPoolWorker-27] ComposerThread failed. Transaction rolled back.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 397, in work
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.save_state(ComposeState.notifying)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 509, in save_state
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.db.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.transaction.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.session.dispatch.after_commit(self.session)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     fn(*args, **kw)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/notifications.py", line 46, in send_messages_after_commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     _publish_with_retry(m)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/backoff/_sync.py", line 99, in retry
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     ret = target(*args, **kwargs)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/notifications.py", line 86, in _publish_with_retry
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     api.publish(message)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 246, in publish
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     _session_cache.session.publish(message, exchange=exchange)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/_session.py", line 150, in publish
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     message.validate()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/message.py", line 569, in validate
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     jsonschema.validate(self.body, schema)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     raise error
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: jsonschema.exceptions.ValidationError: None is not of type 'integer'
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Failed validating 'type' in schema['properties']['artifact']['properties']['builds']['items']['properties']['task_id']:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     {'description': 'Task ID of the koji build.', 'type': 'integer'}
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: On instance['artifact']['builds'][0]['task_id']:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     None
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: During handling of the above exception, another exception occurred:
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: Traceback (most recent call last):
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 324, in run
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.work()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 429, in work
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.save_state()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib/python3.7/site-packages/bodhi/server/tasks/composer.py", line 509, in save_state
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.db.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self.transaction.commit()
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 492, in commit
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     self._assert_active(prepared_ok=True)
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:   File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]:     "This session is in 'committed' state; no further "
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: sqlalchemy.exc.InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,588: INFO/ForkPoolWorker-27] Released semaphore
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,588: INFO/ForkPoolWorker-27] Acquired semaphore, starting
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,618: INFO/ForkPoolWorker-27] Starting composer type <FlatpakComposerThread(Thread-13, started 139657060787968)> for <Compose: F31F stable> with 3 updates
Dec 12 03:12:02 bodhi-backend01.phx2.fedoraproject.org celery-3[63812]: [2019-12-12 03:12:02,635: INFO/ForkPoolWorker-27] Compose object updated.
```

**Comment by cverna** [comment]
Fixed by https://github.com/fedora-infra/bodhi/pull/3853
