### ISSUE TITLE
Bodhi's CLI returns 0 even when it crashed

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3868]
It looks like the bodhi's CLI is returning an exit code of ``0`` even if it crashed

For example:
````
$ bodhi updates new --notes "CI test" --type bugfix --autotime f32-build-side-8323 --from-tag --staging

Warning: openid_api and staging flags are both set. openid_api will be ignored.


Warning: url and staging flags are both set. url will be ignored.

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fedora/client/openidbaseclient.py", line 249, in send_request
    data = output.json()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/client/__init__.py", line 452, in new
    resp = client.save(**update)
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 117, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 281, in save
    data=kwargs)
  File "/usr/lib/python3.7/site-packages/fedora/client/openidbaseclient.py", line 258, in send_request
    'output': to_bytes(output.text),
fedora.client.ServerError: ServerError(https://bodhi.stg.fedoraproject.org/updates/, 504, Error returned from json module while processing b'https://bodhi.stg.fedoraproject.org/updates/': b'Expecting value: line 1 column 1 (char 0)'
b"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n")
$ echo $!                                                                                              
0
````

**Comment by sebwoj** [comment]
Use `echo $?` to check the return value (exit status) of the last executed command

**Comment by rwmjones** [comment]
```
$ bodhi updates edit --removebuilds                                           
brltty-6.0-14.fc33,graphviz-2.42.2-10.fc33 FEDORA-2020-d120de33c5             
Cannot find release associated with build: alt-ergo-2.0.0-12.fc33, tags: ['f33-build-side-20855']                                                      
$ echo $?
0
```
