### ISSUE TITLE
bodhi can't be installed from pypi

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#3919]
This is a big problem now that python-fedora obsoleted internal bodhi client and had a new release, because bodhi can't now be installed from pypi in any way.

```bash
$ pip search bodhi
bodhi (5.1.0)           - bodhi common package
bodhi-server (5.1.0)    - bodhi server
bodhi-client (5.1.0)    - bodhi client
bodhi-messages (5.1.0)  - JSON schema for messages sent by Bodhi

$ pip install bodhi-client
Collecting bodhi-client
  Using cached bodhi-client-5.1.0.tar.gz (33 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/kparal/devel/venv/bodhi-test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l1xmx9dq/bodhi-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l1xmx9dq/bodhi-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-l1xmx9dq/bodhi-client/pip-egg-info
         cwd: /tmp/pip-install-l1xmx9dq/bodhi-client/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l1xmx9dq/bodhi-client/setup.py", line 42, in <module>
        with open(os.path.join(here, "bodhi", "__init__.py")) as fd:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-l1xmx9dq/bodhi-client/bodhi/__init__.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

$ pip install bodhi
Collecting bodhi
  Using cached bodhi-5.1.0.tar.gz (192 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/kparal/devel/venv/bodhi-test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v4ddb48p/bodhi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v4ddb48p/bodhi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info
         cwd: /tmp/pip-install-v4ddb48p/bodhi/
    Complete output (18 lines):
    running egg_info
    creating /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info
    writing /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/SOURCES.txt'
    reading manifest template 'BODHI_MANIFEST.in'
    writing manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/SOURCES.txt'
    running egg_info
    creating /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info
    writing /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/entry_points.txt
    writing requirements to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/requires.txt
    writing top-level names to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    error: package directory 'bodhi/client' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nphilipp** [comment]
We just discussed this, @bowlofeggs mentioned that the reason is the one `setup.py` file containing several `setup()` calls for the different components of Bodhi when it should have one script for each. Until this is solved, you could maybe install `bodhi-5.1.1` package which is available as a testing update in Fedora 30, 31 and as usual in Rawhide.

**Comment by kparal** [comment]
Yes, we now have to use system site packages to use Bodhi through rpm. Thanks for working on this.

**Comment by bowlofeggs** [comment]
Another problem is that the client requires Koji, which isn't available in PyPI.

**Comment by cverna** [comment]
> Another problem is that the client requires Koji, which isn't available in PyPI.

It is now :-) --> https://pypi.org/project/koji/

We have another ticket open #3824 to look at packaging each module independently, but that's not a small task.

**Comment by bowlofeggs** [comment]
On Wed, 2020-02-05 at 11:37 -0800, Clement Verna wrote:
> It is now :-) --> https://pypi.org/project/koji/

Oh wow, nice!

**Comment by abompard** [comment]
This is preventing me from building the messaging bridges in OpenShift with S2I. And S2I doesn't let me install RPMs because the assemble script is run without root. Any suggestions?

**Comment by mattiaverga** [comment]
I've modified `setup.py` to produce useful packages to be installed with pip.
You can find the file and produced output (sdist and wheels) on https://mattia.fedorapeople.org/bodhi_pip/

Can you test if they work before I fill a PR?

**Comment by kparal** [comment]
Sorry, we're in a release crunch now. I'll try to get to it in a few days.

**Comment by jskladan** [comment]
> Can you test if they work before I fill a PR?

Would love to, but I'm honestly not sure how. Could you help me out here?
