### ISSUE TITLE
Allow deleting rawhide updates

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3920]
The number of updates in staging that are in pending state is not normal: https://bodhi.stg.fedoraproject.org/updates/?releases=F32

If you check a few of them, due to a bug in greenwave that is being investigated, they are all passing CI, thus there shouldn't be gated and therefore be pushed to stable.
This is not happening.

The cron job has been ported to celery beats, and is thus running in openshift in stg.

Looking at it, we are running into this traceback:
````
[2020-02-05 17:26:38,280: INFO/MainProcess] Received task: approve_testing[5ec9bb08-4166-4bf1-8bad-659a2f28f872]  
[2020-02-05 17:26:38,284: INFO/ForkPoolWorker-2] Received an approve testing order
[2020-02-05 17:26:38,383: INFO/ForkPoolWorker-2] Using python-bugzilla
[2020-02-05 17:26:55,879: INFO/ForkPoolWorker-2] F32 doesn't have mandatory days in testing
[2020-02-05 17:26:55,894: INFO/ForkPoolWorker-2] FEDORA-2020-3e2471994a now meets testing requirements
[2020-02-05 17:26:56,022: INFO/ForkPoolWorker-2] Automatically marking FEDORA-2020-3e2471994a as stable
[2020-02-05 17:26:56,622: ERROR/ForkPoolWorker-2] There was an error approving testing updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bodhi/server/tasks/approve_testing.py", line 44, in main
    approve_update(update, db)
  File "/usr/local/lib/python3.7/site-packages/bodhi/server/tasks/approve_testing.py", line 98, in approve_update
    conflicting_builds = update.find_conflicting_builds()
  File "/usr/local/lib/python3.7/site-packages/bodhi/server/models.py", line 2981, in find_conflicting_builds
    if not build.is_latest():
  File "/usr/local/lib/python3.7/site-packages/bodhi/server/models.py", line 1510, in is_latest
    if self.get_creation_time() < build_creation_time:
  File "/usr/local/lib/python3.7/site-packages/bodhi/server/models.py", line 1472, in get_creation_time
    return datetime.fromisoformat(self._get_kojiinfo()['creation_time'])
TypeError: 'NoneType' object is not subscriptable
[2020-02-05 17:26:56,658: INFO/ForkPoolWorker-2] Task approve_testing[5ec9bb08-4166-4bf1-8bad-659a2f28f872] succeeded in 18.374360917136073s: None
````

Bodhi is not finding a build it knows about in koji.
This is likely a consequence of our recent prod to stg sync.

There are a few options we could do to fix the situation:
- Do another prod to stg sync, hoping that we don't sync updates of builds that are in-flight in prod (and will thus not be known in stg)
- Hack the DB and drop the update
- Allow to delete updates from the UI when they aren't stable.

I'll likely do the option 2 now, but I think 3 would be better in the long term

**Comment by mattiaverga** [comment]
There's also a similar problem in prod (see #3916 ) where updates which fail CI are not obsoleted by newer builds.
