### ISSUE TITLE
Bugs no longer set to MODIFIED when update is submitted

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#3972]
IIRC, it used to be the case that when an update that fixes a bug was submitted, Bodhi would post a comment on the bug and set it to MODIFIED. However, it no longer seems to do this. Bodhi only seems to touch the bug for the first time when the update is pushed to testing, at which point it goes straight to ON_QA. See for e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1817031 (as I write this, an update has been submitted, but there is no comment from Bodhi on the bug) or https://bugzilla.redhat.com/show_bug.cgi?id=1809717 (a case where you can see the bug go straight from NEW to ON_QA).

**Comment by mattiaverga** [comment]
This is done by `bodhi.server.tasks.updates.UpdatesHandler.work_on_bugs()` along with retrieving bugs information.
I can see for some updates this is working (example https://bodhi.fedoraproject.org/updates/FEDORA-2020-ed14cff0d5 ) and for some other not ( https://bodhi.fedoraproject.org/updates/FEDORA-2020-cad4f4fcd0 ).
Would be nice to see the logs to know if the celery worker actually tried to run the task on those bugs...

**Comment by cverna** [comment]
I looked a bit a that today and we seems to have a few exception like these in celery. It seems that we are trying to update the bug at the same time as someone else.
We could maybe use celery retry feature to retry running this task in such case. Ideas ?

```
March 30th 2020, 14:21:14.551[2020-03-30 14:21:14,547: ERROR/ForkPoolWorker-4] Got fault from Bugzilla on #1818814: fault code: 32000, fault string: Red Hat Bugzilla's database reported a query serialization error. Most likely this occurred because another user or process attempted to change the same data that you were attempting to change. Please press Back and retry the transaction. <pre> UPDATE bugs SET lastdiffed = ? WHERE bug_id = ? at /var/www/html/bugzilla/Bugzilla/BugMail.pm line 377. Bugzilla::BugMail::Send(1818814, 'HASH(0x5574c70fe5f0)', 'HASH(0x5574ce22f420)') called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1824 Bugzilla::Bug::_send_bugmail('HASH(0x5574ce22f420)', undef) called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1732 Bugzilla::Bug::send_changes('Bugzilla::Bug=HASH(0x5574ce819098)', 'HASH(0x5574cedf7128)', undef, 0) called at /var/www/html/bugzilla/Bugzilla/WebService/Bug.pm line 852 Bugzilla::WebService::Bug::update('Bugzilla::WebService::Bug', 'HASH(0x5574ce621588)') called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2875 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2860 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2826 SOAP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x5574ceb704f8)', '<?xml version=\'1.0\'?>\x{a}<methodCall>\x{a}<methodName>Bug.update</...') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 438 SOAP::Transport::HTTP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x5574ceb704f8)') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 831 SOAP::Transport::HTTP::Apache::handler('Bugzilla::WebService::Server::XMLRPC=HASH(0x5574ceb704f8)') called at /var/www/html/bugzilla/xmlrpc.cgi line 44 ModPerl::ROOT::Bugzilla::ModPerl::ResponseHandler::var_www_html_bugzilla_xmlrpc_2ecgi::handler('Apache2::RequestRec=SCALAR(0x5574d0776da0)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 eval {...} called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 ModPerl::RegistryCooker::run('Bugzilla::ModPerl::ResponseHandler=HASH(0x5574ce835290)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 173 ModPerl::RegistryCooker::default_handler('Bugzilla::ModPerl::ResponseHandler=HASH(0x5574ce835290)') called at /usr/lib64/perl5/vendor_perl/ModPerl/Registry.pm line 32 ModPerl::Registry::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x5574d0776da0)') called at /var/www/html/bugzilla/mod_perl.pl line 139 Bugzilla::ModPerl::ResponseHandler::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x5574d0776da0)') called at -e line 0 eval {...} called at -e line 0 </pre>
March 30th 2020, 14:21:14.551Traceback (most recent call last):
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bodhi/server/bugs.py", line 288, in modified
March 30th 2020, 14:21:14.551    bug.setstatus('MODIFIED', comment=comment)
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bugzilla/bug.py", line 197, in setstatus
March 30th 2020, 14:21:14.551    return self.bugzilla.update_bugs(self.bug_id, vals)
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bugzilla/base.py", line 1326, in update_bugs
March 30th 2020, 14:21:14.551    return self._proxy.Bug.update(tmp)
March 30th 2020, 14:21:14.551  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
March 30th 2020, 14:21:14.551    return self.__send(self.__name, args)
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
March 30th 2020, 14:21:14.551    self)._ServerProxy__request(methodname, params)
March 30th 2020, 14:21:14.551  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
March 30th 2020, 14:21:14.551    verbose=self.__verbose
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 202, in request
March 30th 2020, 14:21:14.551    return self._request_helper(url, request_body)
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 180, in _request_helper
March 30th 2020, 14:21:14.551    return self.parse_response(response)
March 30th 2020, 14:21:14.551  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 154, in parse_response
March 30th 2020, 14:21:14.551    return unmarshaller.close()
March 30th 2020, 14:21:14.551  File "/usr/lib64/python3.7/xmlrpc/client.py", line 656, in close
March 30th 2020, 14:21:14.551    raise Fault(**self._stack[0])
March 30th 2020, 14:21:14.551xmlrpc.client.Fault: <Fault 32000: "Red Hat Bugzilla's database reported a query serialization error. Most likely this occurred because another user or process attempted to change the same data that you were attempting to change. Please press Back and retry the transaction. <pre> UPDATE bugs SET lastdiffed = ? WHERE bug_id = ? at /var/www/html/bugzilla/Bugzilla/BugMail.pm line 377. Bugzilla::BugMail::Send(1818814, 'HASH(0x5574c70fe5f0)', 'HASH(0x5574ce22f420)') called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1824 Bugzilla::Bug::_send_bugmail('HASH(0x5574ce22f420)', undef) called at /var/www/html/bugzilla/Bugzilla/Bug.pm line 1732 Bugzilla::Bug::send_changes('Bugzilla::Bug=HASH(0x5574ce819098)', 'HASH(0x5574cedf7128)', undef, 0) called at /var/www/html/bugzilla/Bugzilla/WebService/Bug.pm line 852 Bugzilla::WebService::Bug::update('Bugzilla::WebService::Bug', 'HASH(0x5574ce621588)') called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2875 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2860 eval {...} called at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2826 SOAP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x5574ceb704f8)', '<?xml version=\\'1.0\\'?>\\x{a}<methodCall>\\x{a}<methodName>Bug.update</...') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 438 SOAP::Transport::HTTP::Server::handle('Bugzilla::WebService::Server::XMLRPC=HASH(0x5574ceb704f8)') called at /usr/share/perl5/vendor_perl/SOAP/Transport/HTTP.pm line 831 SOAP::Transport::HTTP::Apache::handler('Bugzilla::WebService::Server::XMLRPC=HASH(0x5574ceb704f8)') called at /var/www/html/bugzilla/xmlrpc.cgi line 44 ModPerl::ROOT::Bugzilla::ModPerl::ResponseHandler::var_www_html_bugzilla_xmlrpc_2ecgi::handler('Apache2::RequestRec=SCALAR(0x5574d0776da0)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 eval {...} called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 207 ModPerl::RegistryCooker::run('Bugzilla::ModPerl::ResponseHandler=HASH(0x5574ce835290)') called at /usr/lib64/perl5/vendor_perl/ModPerl/RegistryCooker.pm line 173 ModPerl::RegistryCooker::default_handler('Bugzilla::ModPerl::ResponseHandler=HASH(0x5574ce835290)') called at /usr/lib64/perl5/vendor_perl/ModPerl/Registry.pm line 32 ModPerl::Registry::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x5574d0776da0)') called at /var/www/html/bugzilla/mod_perl.pl line 139 Bugzilla::ModPerl::ResponseHandler::handler('Bugzilla::ModPerl::ResponseHandler', 'Apache2::RequestRec=SCALAR(0x5574d0776da0)') called at -e line 0 eval {...} called at -e line 0 </pre>">
```

**Comment by mattiaverga** [comment]
From a quick look, it seems in the last few days all bugs associated with updates had their status modified and the bug information is present in Bodhi... I will make some other tests locally with the latest changes pushed in master ASAP.
