### ISSUE TITLE
https://bodhi.fedoraproject.org/updates/, 504, Error returned from json module ...

### ISSUE THREAD

**Issue by jpopelka** [fedora-infra/bodhi#3974]
Hi,
not sure whether this is a problem in your code or infrastructure or our side,
but when we are creating a Bodhi update with [packit](https://github.com/packit-service/packit), we [do](https://github.com/packit-service/packit/blob/master/packit/distgit.py#L360):
```python
b = BodhiClient()
b.save(builds=koji_builds, notes=rendered_note, type=update_type)
```
and even the update is created just fine, the call to `save()` timeouts with:
```
ERROR    ServerError(https://bodhi.fedoraproject.org/updates/, 504, Error returned from json module while processing b'https://bodhi.fedoraproject.org/updates/': b'Expecting value: line 1 column 1 (char 0)'
b"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n")
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fedora/client/openidbaseclient.py", line 249, in send_request
    data = output.json()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpopelka/git/packit-service/packit/packit/cli/utils.py", line 61, in covered_func
    func(config=config, *args, **kwargs)
  File "/home/jpopelka/git/packit-service/packit/packit/cli/create_update.py", line 86, in create_update
    update_type=update_type,
  File "/home/jpopelka/git/packit-service/packit/packit/api.py", line 455, in create_update
    update_type=update_type,
  File "/home/jpopelka/git/packit-service/packit/packit/distgit.py", line 358, in create_bodhi_update
    result = b.save(builds=koji_builds, notes=rendered_note, type=update_type)
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 117, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bodhi/client/bindings.py", line 279, in save
    data=kwargs)
  File "/usr/lib/python3.7/site-packages/fedora/client/openidbaseclient.py", line 258, in send_request
    'output': to_bytes(output.text),
fedora.client.ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 504, Error returned from json module while processing b'https://bodhi.fedoraproject.org/updates/': b'Expecting value: line 1 column 1 (char 0)'
b"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"
```

Thanks

**Comment by mattiaverga** [comment]
@cverna  this could be the same issue that randomly hits users while creating new updates in UI.

I have been able to reproduce this a couple of times in the local test environment and looking at bodhi log it seems to stop just after queing the first notification message:
```
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,473 DEBUG [bodhi.server][waitress] Creating new Update(**data) object.
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,571 DEBUG [bodhi.server][waitress] Set alias for ris-0.2.2-1.fc31 to FEDORA-2020-8b6a5967bb
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,572 DEBUG [bodhi.server][waitress] Adding new update to the db.
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,573 DEBUG [bodhi.server][waitress] Triggering db commit for new update.
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,579 DEBUG [bodhi.server][waitress] Setting request for new update.
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,579 DEBUG [bodhi.server][waitress] Attempting to set request testing
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,598 DEBUG [bodhi.server][waitress] Adding tag f31-signing-pending to ris-0.2.2-1.fc31
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,600 DEBUG [bodhi][waitress] tagBuild(f31-signing-pending, ris-0.2.2-1.fc31)
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,601 DEBUG [bodhi.server][waitress] FEDORA-2020-8b6a5967bb has been submitted for testing.
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,688 INFO  [bodhi.server][waitress] Sending mail to mattia.verga@protonmail.com: [Fedora Update] [comment] ris-0.2.2-1.fc31
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,688 INFO  [bodhi.server][waitress] Not sending email: No smtp_server defined
Mar 27 17:30:14 bodhi-dev.example.com pserve-3[18362]: 2020-03-27 17:30:14,977 DEBUG [bodhi.server.notifications][waitress] Queuing message 'e6c32d5f-d1fb-4ede-adb5-ceb491ab9904' for delivery on session commit
```

I wonder if this can be due to the fact that `bodhi.server.notifications.publish()` creates its own Session() object, adds the message "to be delivered on session commit", but the commit action is performed outside of this method...
I've noticed that usually `b.save()` gets stuck after many minutes of inactivity. For example, in bodhi-shell run:
```
from bodhi.client.bindings import BodhiClient
b = BodhiClient(base_url='http://localhost:6543', username='mattia', password='xxx')
b.save(builds=['ris-1.1.1-1.fc31'], notes="new", type="newpackage")
```
and it works.
Then, if you run
`b.save(builds=['ris-1.1.2-1.fc31'], notes="newer", type="newpackage")`
after some seconds, it still works.
But if you wait several minutes (five or ten, I didn't time it) and run
`b.save(builds=['ris-1.1.3-1.fc31'], notes="newer", type="newpackage")`
it gets stuck (usually...).

**Comment by mattiaverga** [comment]
I have pushed some changes in #3977 to find the reason of the above behavior.
Even if we pass the current active session object to `publish()` Bodhi still hangs. The added debug messages show that it hangs on `handle_update.delay()`, but I can't find any reason why it should behave this way.

**Comment by cverna** [comment]
> I have pushed some changes in #3977 to find the reason of the above behavior.
> Even if we pass the current active session object to `publish()` Bodhi still hangs. The added debug messages show that it hangs on `handle_update.delay()`, but I can't find any reason why it should behave this way.

Yeah this is similar to what I have observed in the production log, it just hangs on handle_update.delay(). In production we have quite a few unexpected connection closure from the rabbitmq broker so I have added some parameter to retry the task in such case, but that should not really happen in the vagrant box so I wonder if there is something else going on.

**Comment by mattiaverga** [comment]
> 
> Yeah this is similar to what I have observed in the production log, it just hangs on handle_update.delay(). In production we have quite a few unexpected connection closure from the rabbitmq broker so I have added some parameter to retry the task in such case, but that should not really happen in the vagrant box so I wonder if there is something else going on.

BTW, in the vagrant box the celery workers are not working at all... they don't receive any message from the local rabbitmq broker.
