### ISSUE TITLE
koji 1.22 doesn't support krb_login, it supports gssapi_login

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/bodhi#4029]
Please make the changes needed to support gssapi_login.

**Comment by mattiaverga** [comment]
Does this need anything special other than change krb_login() call to gssapi_login()?
I can't see any docstring under gssapi_login().

**Comment by cverna** [comment]
> Does this need anything special other than change krb_login() call to gssapi_login()?
> I can't see any docstring under gssapi_login().

I am trying that currently in staging and it seems to fail with 
```
from bodhi.server.config import config
from bodhi.server import bugs, buildsys
config.load_config()
buildsys.setup_buildsystem(config)
kc = buildsys.get_session()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/bodhi/server/buildsys.py", line 694, in get_session
    return _buildsystem()
  File "/usr/lib/python3.8/site-packages/bodhi/server/buildsys.py", line 726, in get_koji_login
    return koji_login(config=settings, authenticate=authenticate)
  File "/usr/lib/python3.8/site-packages/bodhi/server/buildsys.py", line 650, in koji_login
    if authenticate and not koji_client.gssapi_login(**get_krb_conf(config)):
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2572, in gssapi_login
    raise AuthError('unable to obtain a session')
koji.AuthError: unable to obtain a session
>>> 
```

So that will need a bit more investigation

**Comment by cverna** [comment]
Ok seems to have been a issue with the hosts I was using, just replacing with gssapi_login seems to work fine.
