### ISSUE TITLE
bodhi not approving rawhide updates to stable

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#4055]
Bodhi seems to not be approving rawhide updates to stable. 

The logs have: 

```
2020-06-14 17:43:01,831: ERROR/ForkPoolWorker-1] There was an error approving testing updates.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2785, in _callMethod
    return self._sendCall(handler, headers, request)
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2703, in _sendCall
    return self._sendOneCall(handler, headers, request)
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2749, in _sendOneCall
    ret = self._read_xmlrpc_response(r)
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2761, in _read_xmlrpc_response
    result = u.close()
  File "/usr/lib64/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1000: "Invalid tagInfo: 'f33-build-side-24506-signing-pending'">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bodhi/server/tasks/approve_testing.py", line 46, in main
    approve_update(update, db)
  File "/usr/lib/python3.8/site-packages/bodhi/server/tasks/approve_testing.py", line 137, in approve_update
    koji.deleteTag(pending_signing_tag)
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2263, in __call__
    return self.__func(self.__name, args, opts)
  File "/usr/lib/python3.8/site-packages/koji/__init__.py", line 2804, in _callMethod
    raise err
koji.GenericError: Invalid tagInfo: 'f33-build-side-24506-signing-pending'
[2020-06-14 17:43:01,858: INFO/ForkPoolWorker-1] Task approve_testing[198076d8-2b59-4424-afc3-d291a090bad8] succeeded in 19.52551427000435s: None
```

And even tho it has 'Task...succeeded' it doesn't actually approve any.

**Comment by pypingou** [comment]
Some thoughts about this when I briefly looked into it:
````
  pingou | so the builds in https://bodhi.fedoraproject.org/updates/FEDORA-2020-11078fbad3 made it to F33                                                
  pingou | but the update wasn't marked as stable because koji said that f33-build-side-24510-signing-pending is invalid                                 
  pingou | I wonder if this error ^ isn't what blocks other updates from being created                                                                   
ignatenkobrain | pingou: I've actually had some packages being pushed through few hours ago                                                                    
ignatenkobrain | so it should not be related to my issue with btrfs-progs                                                                                      
  pingou | ignatenkobrain: it could be that at the next run of monitor-gating, a new update is created which obsolete the old one that is then ignored   
  pingou | allowing other updates to be processed in the mean while                                                                                      
  pingou | this also explains why I keep receiving emails from bodhi about my updates :(   
````

What I don't understand is why f33-build-side-24510-signing-pending no longer exists:
https://koji.fedoraproject.org/koji/search?match=glob&type=tag&terms=f33-build-side-24510-signing-pending
while f33-build-side-24510 still does:
https://koji.fedoraproject.org/koji/search?match=glob&type=tag&terms=f33-build-side-24510
(at the time of this writing)

**Comment by cverna** [comment]
So it looks like koji is deleting tags when the last build in the tag was untagged. That makes bodhi unhappy when it is trying to delete the tag since this tag does not exists anymore.

I think we should let koji manage the deletion of tags and side tags (https://pagure.io/fedora-infra/ansible/pull-request/137). I ll open a PR to remove the tag deletion code we have in bodhi.

**Comment by cverna** [comment]
So in fact it looks like bodhi is deleting the signing-pending and testing-pending tags 
```
 [cverna@localhost]  [fix_editing_updates] $ koji list-history --tag=f33-build-side-24581-signing-pending
Wed Jun 17 11:23:22 2020 new tag: f33-build-side-24581-signing-pending by bodhi
Wed Jun 17 11:23:22 2020 inheritance line f33-build-side-24581-signing-pending->f33-build-side-24581 added by bodhi
Wed Jun 17 11:23:23 2020 dummy-test-package-crested-0-670.fc33 tagged into f33-build-side-24581-signing-pending by bodhi
Wed Jun 17 11:23:23 2020 dummy-test-package-rubino-0-670.fc33 tagged into f33-build-side-24581-signing-pending by bodhi
Wed Jun 17 11:23:26 2020 dummy-test-package-crested-0-670.fc33 untagged from f33-build-side-24581-signing-pending by autopen
Wed Jun 17 11:23:28 2020 dummy-test-package-rubino-0-670.fc33 untagged from f33-build-side-24581-signing-pending by autopen
Wed Jun 17 12:11:34 2020 tag deleted: f33-build-side-24581-signing-pending by bodhi
Wed Jun 17 12:11:34 2020 inheritance line f33-build-side-24581-signing-pending->f33-build-side-24581 removed by bodhi

```

**Comment by cverna** [comment]
OK I got to the bottom of it, the problem comes from https://pagure.io/koji/issue/2321, Bodhi is not allowed to delete side-tag anymore which makes the approve_testing tasks crash. But before crashing Bodhi manages to delete the signing-pending and testing-pending tags. So the next time the task runs we try to push the update to stable again but when bodhi tries to delete these 2 tags they don't exist anymore.

I think the solution is adding a db commit after updating the status of the update so that if there is a failure in koji deleting tag, the update will not be stuck in testing for ever.

I also think that we should take advantage of koji to delete the sidetags (https://pagure.io/fedora-infra/ansible/pull-request/137)

**Comment by cverna** [comment]
Hotfixed production with https://github.com/cverna/bodhi/commit/c8866578cd3f46e06bac3d842864e02706b79aaf
