### ISSUE TITLE
Can't change build in EL6 update

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#411]
I just wanted to edit all my fedfind updates from fedfind-1.4.2-1.(dist) to fedfind-1.5-1.(dist). I was able to edit the updates for EL7, F21, F22 and F23, but I just can't edit the [update for EL6](https://bodhi.fedoraproject.org/updates/fedfind-1.4.2-1.el6). However I try, it fails with "Unable to create update. Invalid taginfo: "

**Comment by ralphbean** [comment]
Found the traceback:

```python
2015-08-28 00:43:55,127 ERROR [bodhi][Dummy-2] Failed to create update
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/services/updates.py", line 340, in new_update
    result, _caveats = Update.edit(request, data)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 738, in edit
    koji.tagBuild(up.release.pending_testing_tag, build)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1556, in __call__
    return self.__func(self.__name,args,opts)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1918, in _callMethod
    raise err
GenericError: Invalid tagInfo: ''
```

**Comment by ralphbean** [comment]
And.... this is a problem with our DB release configuration.  From production ``pshell``:

```python
>>> thing = m.Release.get('EL-6', db)
>>> thing
<Release {'dist_tag': u'dist-6E-epel', 'name': u'EL-6', 'testing_tag': u'dist-6E-epel-testing', 'pending_stable_tag': u'', 'long_name': u'Fedora EPEL 6', 'state': u'current', 'version': u'6', 'override_tag': u'dist-6E-epel-override', 'branch': u'el6', 'id_prefix': u'FEDORA-EPEL', 'pending_testing_tag': u'', 'stable_tag': u'dist-6E-epel', 'candidate_tag': u'dist-6E-epel-testing-candidate'}>
>>> print thing.pending_testing_tag

>>> 
```
