### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mgrabovsky** [fedora-infra/bodhi#4114]
I keep encountering 500 errors when browsing updates pages in recent minutes, e.g. this one is from <https://bodhi.fedoraproject.org/updates/FEDORA-2020-59e144acee>:

```
500 Internal Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/usr/lib/python3.8/site-packages/mako/template.py", line 481, in render_unicode
    return runtime._render(
  File "/usr/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/usr/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "master_html", line 132, in render_body
    
  File "/usr/local/lib/python3.8/site-packages/bodhi/server/templates/update.html", line 131, in render_body
    % if update.test_cases:
  File "/usr/local/lib/python3.8/site-packages/bodhi/server/models.py", line 3853, in test_cases
    for test in build.testcases:
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
    value = self.callable_(state, passive)
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state
    return self._emit_lazyload(
  File "<string>", line 1, in <lambda>
    
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 900, in _emit_lazyload
    q(session)
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/ext/baked.py", line 545, in all
    return list(self)
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/loading.py", line 525, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/orm/loading.py", line 525, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/engine/result.py", line 681, in _key_fallback
    util.raise_(
  File "/usr/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
NoSuchColumnError: "Could not locate column in row for column 'testcases.id'"
```

Usually the error goes away after a refresh or two.

**Comment by mattiaverga** [comment]
Same as #4105
