### ISSUE TITLE
bodhi client traceback in rawhide (packaging issues?)

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#4161]
This may well be a packaging issue, but I can't see to figure it out. ;( 

I got bodhi building in rawhide by applying a few patches: 

* remove WebOb-GraphQL from requirements.txt (it's not yet packaged)
* adjust the version... the current bodhi release has "__version__ = "5.5"" but the release/version is really 5.5.0, and that causes some confusion. 
* Disable docs (because of graphql)
* Disable tests (because of graphql)

After that however, trying to run the client results in: 

```
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 33, in <module>
    sys.exit(load_entry_point('bodhi-client==5.5.0', 'console_scripts', 'bodhi')())
  File "/usr/bin/bodhi", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/bodhi/client/__init__.py", line 30, in <module>
    from fedora.client import AuthError, openidproxyclient
  File "/usr/lib/python3.9/site-packages/fedora/client/__init__.py", line 35, in <module>
    from munch import Munch
  File "/usr/lib/python3.9/site-packages/munch/__init__.py", line 24, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'koji' distribution was not found and is required by bodhi-client
```

Ideally we would get the rest of things packaged, fix the version, get the docs and tests building and sort out the traceback. :)

**Comment by mattiaverga** [comment]
About the Koji issue, we should find why installing koji from Fedora package it is not found: https://github.com/fedora-infra/bodhi/commit/ff5cc1d6e097acb96ea0ea9132bcd68d9c8caeea

About WebOb-GraphQL, I've started packaging it, but then I aborted. WebOb-GrapQL requires graphql-server-core (v2) which is becoming graphql-server (v3) that has its own webob interface.
I will try packaging graphql-server, meanwhile I propose to drop WebOb-GrapQL and move to graphql-server[webob].
The other two Bodhi graphql dependencies are graphene (already packaged as python-graphene) and graphene-sqlalchemy (just packaged, I will import and build in Koji in the next few days).

**Comment by cverna** [comment]
> About the Koji issue, we should find why installing koji from Fedora package it is not found: [ff5cc1d](https://github.com/fedora-infra/bodhi/commit/ff5cc1d6e097acb96ea0ea9132bcd68d9c8caeea)

I am sure I saw an official issue about this in the koji tracker but I can find it any more :( 

> 
> About WebOb-GraphQL, I've started packaging it, but then I aborted. WebOb-GrapQL requires graphql-server-core (v2) which is becoming graphql-server (v3) that has its own webob interface.
> I will try packaging graphql-server, meanwhile I propose to drop WebOb-GrapQL and move to graphql-server[webob].
> The other two Bodhi graphql dependencies are graphene (already packaged as python-graphene) and graphene-sqlalchemy (just packaged, I will import and build in Koji in the next few days).

Yeah I was waiting on graphql-server v3 to come but it is taking forever for upstream to release this version :( .

**Comment by mattiaverga** [comment]
> > About the Koji issue, we should find why installing koji from Fedora package it is not found: [ff5cc1d](https://github.com/fedora-infra/bodhi/commit/ff5cc1d6e097acb96ea0ea9132bcd68d9c8caeea)
> 
> I am sure I saw an official issue about this in the koji tracker but I can find it any more :(

For reference: https://pagure.io/koji/issue/912

**Comment by mattiaverga** [comment]
Cleaning old tickets, I think this is now all fixed.
