### ISSUE TITLE
traceback when determining tag actions

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#418]
We hit this traceback in a mash today.

```                                                                      
[2015-08-28 17:41:52][    fedmsg    INFO] Updating comps                                                            
[2015-08-28 17:41:52][     bodhi    INFO] Running ['git', 'pull']
[2015-08-28 17:41:52][     bodhi    INFO] Running ['make']
[2015-08-28 17:41:52][    fedmsg    INFO] Mashing f21-updates-testing
[2015-08-28 17:41:52][    fedmsg    INFO] Running post-request actions on updates
[2015-08-28 17:41:52][     bodhi    INFO] Running ['mash', '-o', '/mnt/koji/mash/updates/f21-updates-testing-150828.
[2015-08-28 17:41:52][    fedmsg    INFO] Generating testing digest for F21
[2015-08-28 17:42:20][    fedmsg   ERROR] Cannot find relevant tag for python-affinity-0.1.0-5.fc23: ['f23', 'f23-up
[2015-08-28 17:42:20][    fedmsg   ERROR] Exception in MasherThread(f23-updates-testing)
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 298, in work
self.determine_tag_actions()
File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 513, in determine_tag_actions
raise Exception
Exception
```                                                                      

So, we raise that exception there.  Perhaps instead we could try to gracefully recover by just ejecting whichever updates fail at that point.

The sticking point there is that ``determine_tag_actions`` currently happens *after* we try to update the security bugs.  So, maybe we want to reverse the order there if we can.. and do the tag actions first, and then the security bugs.  Possible?

**Comment by kalev** [comment]
Looks like the update in question had already been pushed to stable, but then a few days later it was submitted for testing again: https://bodhi.fedoraproject.org/updates/python-affinity-0.1.0-5.fc23

**Comment by ralphbean** [comment]
#456 helps patch up the other side of this.
