### ISSUE TITLE
client fails to authenticate user on staging instance

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4212]
While investigating for https://github.com/fedora-infra/bodhi/issues/4209#issuecomment-826563668 I was trying to edit some updates in staging Bodhi from CLI, but the authentication fails:
```
$ bodhi updates edit FEDORA-EPEL-2021-8960f38366 --type bugfix --staging --debug

Warning: openid_api and staging flags are both set. openid_api will be ignored.


Warning: url and staging flags are both set. url will be ignored.

Username: mattia
Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/fedora/client/openidbaseclient.py", line 260, in send_request
    output = func(method, **kwargs)
  File "/usr/lib/python3.9/site-packages/fedora/client/openidbaseclient.py", line 88, in _decorator
    raise LoginRequiredError(
fedora.client.LoginRequiredError: https://bodhi.stg.fedoraproject.org/updates/ requires a logged in user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/bodhi/client/bindings.py", line 117, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/bodhi/client/bindings.py", line 280, in save
    return self.send_request('updates/', verb='POST', auth=True,
  File "/usr/lib/python3.9/site-packages/fedora/client/openidbaseclient.py", line 262, in send_request
    raise AuthError()
fedora.client.AuthError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bodhi", line 33, in <module>
    sys.exit(load_entry_point('bodhi-client==5.6.1', 'console_scripts', 'bodhi')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/bodhi/client/__init__.py", line 263, in wrapper
    method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/bodhi/client/__init__.py", line 567, in edit
    resp = client.save(**kwargs)
  File "/usr/lib/python3.9/site-packages/bodhi/client/bindings.py", line 142, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/bodhi/client/bindings.py", line 276, in save
    kwargs['csrf_token'] = self.csrf()
  File "/usr/lib/python3.9/site-packages/bodhi/client/bindings.py", line 117, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/bodhi/client/bindings.py", line 616, in csrf
    self.login(self.username, self.password)
  File "/usr/lib/python3.9/site-packages/fedora/client/openidbaseclient.py", line 303, in login
    response = openid_login(
  File "/usr/lib/python3.9/site-packages/fedora/client/openidproxyclient.py", line 132, in openid_login
    raise ServerError(FEDORA_OPENID_API, response.status_code,
fedora.client.ServerError: ServerError(https://id.stg.fedoraproject.org/api/v1/, 500, Error returned from our POST to ipsilon.)
```
Is this a staging only problem, or is the client unusable also on prod?

**Comment by cverna** [comment]
`fedora.client.ServerError: ServerError(https://id.stg.fedoraproject.org/api/v1/, 500, Error returned from our POST to ipsilon.)`

Looks like an infra issue, might want to create a fedora-infra ticket for someone to go an look at ipsilon logs in stg

**Comment by ryanlerch** [comment]
Tracking this in the infra ticket:

https://pagure.io/fedora-infrastructure/issue/9927
