### ISSUE TITLE
Expat error in making testing digest

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#426]
Hitting this trying to push f23-updates-testing:

```
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: [2015-08-29 19:32:05][    fedmsg   ERROR] Exception in MasherThread(f23-updates-testing)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: Traceback (most recent call last):
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 318, in work
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: self.generate_testing_digest()
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 627, in generate_testing_digest
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: self.add_to_digest(update)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 620, in add_to_digest
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: update, use_template='maillist_template')):
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/bodhi/mail.py", line 315, in get_template
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: h = get_rpm_header(build.nvr)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/bodhi/util.py", line 72, in get_rpm_header
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: result = koji_session.getRPMHeaders(rpmID=rpmID, headers=headers)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1577, in __call__
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: return self.__func(self.__name,args,opts)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1920, in _callMethod
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: return self._sendCall(handler, headers, request)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1831, in _sendCall
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: return self._sendOneCall(handler, headers, request)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1853, in _sendOneCall
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: ret = self._read_xmlrpc_response(response, handler)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1893, in _read_xmlrpc_response
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: p.feed(chunk)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: File "/usr/lib64/python2.7/xmlrpclib.py", line 557, in feed
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: self._parser.Parse(data, 0)
Aug 29 19:32:05 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[2521]: ExpatError: not well-formed (invalid token): line 96, column 22
```

**Comment by ralphbean** [comment]
Noting here that there was an underlying koji bug:  https://lists.fedorahosted.org/pipermail/koji-devel/2015-August/000059.html
