### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by syaifurrizal** [fedora-infra/bodhi#4276]
When accessing [https://bodhi.fedoraproject.org/updates/FEDORA-2021-fdef34e26f](https://bodhi.fedoraproject.org/updates/FEDORA-2021-fdef34e26f) found this messages:

```bash
500 Internal Server Error
Traceback (most recent call last): File "/usr/lib/python3.9/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python3.9/site-packages/mako/template.py", line 478, in render_unicode return runtime._render( File "/usr/lib/python3.9/site-packages/mako/runtime.py", line 878, in _render _render_context( File "/usr/lib/python3.9/site-packages/mako/runtime.py", line 920, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs) File "/usr/lib/python3.9/site-packages/mako/runtime.py", line 947, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 132, in render_body File "/usr/lib/python3.9/site-packages/bodhi/server/templates/update.html", line 206, in render_body ${self.fragments.comment(comment, display_update=False)} File "fragments_html", line 192, in render_comment File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__ return self.impl.get(instance_state(instance), dict_) File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 730, in get value = self.callable_(state, passive) File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state return self._emit_lazyload( File "<string>", line 1, in <lambda> File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 900, in _emit_lazyload q(session) File "/usr/lib64/python3.9/site-packages/sqlalchemy/ext/baked.py", line 544, in all return list(self) File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/loading.py", line 100, in instances cursor.close() File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__ compat.raise_( File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_ raise exception File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/loading.py", line 80, in instances rows = [proc(row) for row in fetch] File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp> rows = [proc(row) for row in fetch] File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/loading.py", line 524, in _instance tuple([row[column] for column in pk_cols]), File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/loading.py", line 524, in <listcomp> tuple([row[column] for column in pk_cols]), File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/result.py", line 681, in _key_fallback util.raise_( File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_ raise exception NoSuchColumnError: "Could not locate column in row for column 'comment_bug_assoc.id'"
```

**Comment by kparal** [comment]
I saw the same error after submitting feedback to https://bodhi.fedoraproject.org/updates/FEDORA-2021-b80a55ffe4 (the feedback was submitted OK, it seems).
