### ISSUE TITLE
Broken CI tests

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4282]
CI tests constantly fail, it seems there's some problem on the Jenkins instance we're using.

Integration builds fail with:
```
curl: (6) getaddrinfo() thread failed to start
The command '/bin/sh -c curl -o /etc/yum.repos.d/infra-tags.repo https://pagure.io/fedora-infra/ansible/raw/master/f/files/common/fedora-infra-tags.repo' returned a non-zero code: 6
```

A more general problem is also detected in the general node startup:
```
15:22:58      Complete output from command python setup.py egg_info:
15:22:58      
15:22:58              =============================DEBUG ASSISTANCE==========================
15:22:58              If you are seeing an error here please try the following to
15:22:58              successfully install cryptography:
15:22:58      
15:22:58              Upgrade to the latest pip and try again. This will fix errors for most
15:22:58              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
15:22:58              =============================DEBUG ASSISTANCE==========================
15:22:58      
15:22:58      Traceback (most recent call last):
15:22:58        File "<string>", line 1, in <module>
15:22:58        File "/tmp/pip-build-xgrnd_84/cryptography/setup.py", line 14, in <module>
15:22:58          from setuptools_rust import RustExtension
15:22:58      ModuleNotFoundError: No module named 'setuptools_rust'
15:22:58      
15:22:58      ----------------------------------------
15:22:58  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xgrnd_84/cryptography/
```

Maybe related: in the Jenkins dashboard there's a message saying:
```
THIS JENKINS INSTANCE WILL DISAPPEAR SOON ! 
You should open a Infra Ticket to migrate to the new openshift CI cluster
```

**Comment by mattiaverga** [comment]
Closing duplicate of #4248
