### ISSUE TITLE
Move away from `pyramid_fas_openid` and `python-openid`

### ISSUE THREAD

**Issue by abompard** [fedora-infra/bodhi#4356]
When running the integration tests on pip, we get the following error:
```
mod_wsgi (pid=19): Exception occurred processing WSGI script '/etc/bodhi/bodhi.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/whitenoise/base.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.9/site-packages/pyramid/router.py", line 248, in invoke_request
    request._process_response_callbacks(response)
  File "/usr/local/lib/python3.9/site-packages/pyramid/request.py", line 85, in _process_response_callbacks
    callback(self, response)
  File "/usr/local/lib/python3.9/site-packages/pyramid/session.py", line 258, in set_cookie_callback
    self._set_cookie(response)
  File "/usr/local/lib/python3.9/site-packages/pyramid/session.py", line 325, in _set_cookie
    serializer.dumps((self.accessed, self.created, dict(self)))
  File "/usr/local/lib/python3.9/site-packages/webob/cookies.py", line 659, in dumps
    cstruct = self.serializer.dumps(appstruct) # will be bytes
  File "/usr/local/lib/python3.9/site-packages/webob/cookies.py", line 560, in dumps
    return bytes_(json.dumps(appstruct), encoding='utf-8')
  File "/usr/lib64/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type YadisServiceManager is not JSON serializable
```

After some investigation, it turns out that recent Pyramid versions [have moved away from pickle-based sessions to JSON-based sessions](https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-2.0.html#upgrading-session-20). But the `python-openid` library still wants to store a couple python object instances in the session without proper serialization, and this is causing the crash. It has been reported [in a python-openid issue](https://github.com/openid/python-openid/issues/17) but that was in 2011 and the last comment is from 2014, stating that the library is pretty much unmaintained.

I think we should revisit our plans to move to [authlib](https://authlib.org/), which is maintained, but also means a switch to OIDC instead of plain OpenID. It has been our plan for a while, but we never got around to doing it. It looks like we'll have to bump it in our priorities, because updates will eventually be integrated in current Fedora releases and things will break.

Another option would be to patch up `python-openid`, but I think that would not be the best use of our workforce.

**Comment by mattiaverga** [comment]
I'll just link #4264 here, as this effort sounds like it can also help there.

**Comment by abompard** [comment]
Also linked to #1180
