### ISSUE TITLE
500 Error on staging while trying to login

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4410]
The latest changes have been deployed on Bodhi staging instance. Authentication is broken, when trying to login it returns a 500 Server Error:
```


2022-03-07 17:41:33,164 DEBUG [authlib.integrations.base_client.base_app][ThreadPoolExecutor-0_0] Saving authorize data: {'redirect_uri': 'https://bodhi.stg.fedoraproject.org/oidc/authorize' , 'nonce': 'Q1X5vbvvbYe1gIXXGzok', 'url': 'https://id.fedoraproject.org/openidc/Authorization?response_type=code&client_id=&redirect_uri=https%3A%2F%2Fbodhi.stg.fedoraproject.org%2Foidc%2Fauthorize&scope=openid+email+profile+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fgroups+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fagreements&state=RPXVpc4F4qo9Ij7fygok6sBvYQjTzt&nonce=Q1X5vbvvbYe1gIXXGzok' , 'state': 'RPXVpc4F4qo9Ij7fygok6sBvYQjTzt'}
--


authlib.integrations.base_client.errors.OAuthError: invalid_request: missing required argument client_id2022-03-07 17:41:33,164 DEBUG [authlib.integrations.base_client.base_app][ThreadPoolExecutor-0_0] Saving authorize data: {'redirect_uri': '[https://bodhi.stg.fedoraproject.org/oidc/authorize' ](https://bodhi.stg.fedoraproject.org/oidc/authorize'), 'nonce': 'Q1X5vbvvbYe1gIXXGzok', 'url': '[https://id.fedoraproject.org/openidc/Authorization?response_type=code&client_id=&redirect_uri=https%3A%2F%2Fbodhi.stg.fedoraproject.org%2Foidc%2Fauthorize&scope=openid+email+profile+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fgroups+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fagreements&state=RPXVpc4F4qo9Ij7fygok6sBvYQjTzt&nonce=Q1X5vbvvbYe1gIXXGzok' ](https://id.fedoraproject.org/openidc/Authorization?response_type=code&client_id=&redirect_uri=https%3A%2F%2Fbodhi.stg.fedoraproject.org%2Foidc%2Fauthorize&scope=openid+email+profile+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fgroups+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fagreements&state=RPXVpc4F4qo9Ij7fygok6sBvYQjTzt&nonce=Q1X5vbvvbYe1gIXXGzok%27), 'state': 'RPXVpc4F4qo9Ij7fygok6sBvYQjTzt'}
2022-03-07 17:41:33,724 ERROR [bodhi.server][ThreadPoolExecutor-0_0] Error caught.  Handling HTML response.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/lib/python3.9/site-packages/pyramid/router.py", line 147, in handle_request
    response = _call_view(
  File "/usr/lib/python3.9/site-packages/pyramid/view.py", line 683, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.9/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/lib/python3.9/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/usr/lib/python3.9/site-packages/bodhi/server/auth/views.py", line 85, in authorize_oidc
    token = request.registry.oidc.fedora.authorize_access_token(request)
  File "/usr/lib/python3.9/site-packages/bodhi/server/auth/oauth_015.py", line 61, in authorize_access_token
    params = self.retrieve_access_token_params(request)
  File "/usr/lib/python3.9/site-packages/authlib/integrations/base_client/base_app.py", line 139, in retrieve_access_token_params
    params = self.framework.generate_access_token_params(self.request_token_url, request)
  File "/usr/lib/python3.9/site-packages/bodhi/server/auth/oauth_015.py", line 38, in generate_access_token_params
    raise OAuthError(error=error, description=description)
authlib.integrations.base_client.errors.OAuthError: invalid_request: missing required argument client_id
```

**Comment by ryanlerch** [comment]
Sorry about that! the bodhi config on staging is just missing a handful of items to make the OIDC work, specifically these items (with correct values):

https://github.com/fedora-infra/bodhi/pull/4387/files#diff-674a2f014a8ec84b3bb9fffe33e6588cfd176e68efc640732700f7bbbf77e21bR63

need to be added to:

https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/base/templates/production.ini.j2
