### ISSUE TITLE
Login to Bodhi 6 fails with HTTP 500 'email'

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#4522]
When I try to log in to https://bodhi.stg.fedoraproject.org (running `bodhi-server 6.0.0^202204150949gitd412e93`), I see this error:

![bodhi](https://user-images.githubusercontent.com/755451/170066737-7aaa7bdc-c999-409f-874b-a845bdb7206e.png)

I haven't been able to find a workaround.

**Comment by mattiaverga** [comment]
```
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
response = handler(request)
File "/usr/lib/python3.10/site-packages/pyramid/router.py", line 147, in handle_request
response = _call_view(
File "/usr/lib/python3.10/site-packages/pyramid/view.py", line 683, in _call_view
response = view_callable(context, request)
File "/usr/lib/python3.10/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
result = view(context, request)
File "/usr/lib/python3.10/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
response = view(request)
File "/usr/lib/python3.10/site-packages/bodhi/server/auth/views.py", line 94, in authorize_oidc
get_and_store_user(request, token["access_token"], response)
File "/usr/lib/python3.10/site-packages/bodhi/server/auth/utils.py", line 45, in get_and_store_user
userinfo['email'],
KeyError: 'email'
```

cc @abompard 
Maybe some change in the returned fields from staging Ipsilon?

**Comment by abompard** [comment]
Yeah that was me making mistakes upgrading ipsilon this morning. Sorry about that. It should be fixed now.

**Comment by kparal** [comment]
I can log in now. Thanks.
