### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://bodhi.fedoraproject.org/oidc/login-token

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#4569]
```
$ ./fedora-easy-karma.py 
Logging into Bodhi...
Traceback (most recent call last):
  File "/home/kparal/devel/qa/fedora-easy-karma/./fedora-easy-karma.py", line 805, in <module>
    fek = FedoraEasyKarma()
  File "/home/kparal/devel/qa/fedora-easy-karma/./fedora-easy-karma.py", line 469, in __init__
    self.bc.ensure_auth()
  File "/usr/lib/python3.10/site-packages/bodhi/client/bindings.py", line 246, in ensure_auth
    resp.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://bodhi.fedoraproject.org/oidc/login-token
```

I can do this repeatedly over and over again. The relevant code inside is this:
```
from bodhi.client.bindings import BodhiClient
self.bc = BodhiClient()
self.bc.ensure_auth()
```

I saw this once already yesterday, and it happened to me again today. I **think** it might've happened because I visited the authorization URL twice, but I'm not sure which one. This is the request URL:
```
Authenticating... Please open your browser to:
https://id.fedoraproject.org/openidc/Authorization?response_type=code&client_id=bodhi-client&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=openid+email+profile+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fgroups+https%3A%2F%2Fid.fedoraproject.org%2Fscope%2Fagreements&state=xgxhm4JrmFQFE5REKYARCgWHeyx32y
Paste here the code that you got after logging in: 
```
And that request URL redirected me to this response URL:
https://id.fedoraproject.org/openidc/Continue?ipsilon_transaction_id=2a814e61-cdf7-4349-87e1-268200fac1d9

I provided the code, it worked, and then, after some time, I opened the response URL again in a different tab. It told me that I don't have an authorization header or something like that. And since then, I'm getting HTTP 500 from bodhi-client.

I'm not completely sure what exact steps I performed, and I don't want to try immediately again, because perhaps you can find the problem in server logs when I can easily reproduce it right now. I can share `~/.config/bodhi/client.json` with you privately if that helps.

I'm quite certain that if I remove `~/.config/bodhi/client.json` and try again, it will work correctly (ask for a new token).

Version:
```
bodhi-client-6.0.0-2.fc36.noarch
```

**Comment by abompard** [comment]
For reference the server-side traceback is:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/lib/python3.10/site-packages/pyramid/router.py", line 147, in handle_request
    response = _call_view(
  File "/usr/lib/python3.10/site-packages/pyramid/view.py", line 683, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.10/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/lib/python3.10/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/usr/lib/python3.10/site-packages/bodhi/server/auth/views.py", line 114, in login_with_token
    get_and_store_user(request, token["access_token"], response)
  File "/usr/lib/python3.10/site-packages/bodhi/server/auth/utils.py", line 39, in get_and_store_user
    username = userinfo['nickname']
KeyError: 'nickname'
```

Let's try to handle that better.

**Comment by abompard** [comment]
Hmm I'm not finding a way to reproduce it right now, can you please send me you bodhi client config file at my @ fedoraproject email address? My GPG key is on [my noggin profile](https://accounts.fedoraproject.org/user/abompard/). Thanks!
