### ISSUE TITLE
setup.py test doesn't include extra_requires from fedmsg deps

### ISSUE THREAD

**Issue by decause** [fedora-infra/bodhi#506]
```
======================================================================
ERROR: Failure: ImportError (No module named psutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/decause/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/decause/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/decause/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/decause/code/bodhi/bodhi/tests/test_masher.py", line 27, in <module>
    from bodhi.consumers.masher import Masher, MasherThread
  File "/home/decause/code/bodhi/bodhi/consumers/masher.py", line 30, in <module>
    import fedmsg.consumers
  File "/home/decause/code/bodhi/.eggs/fedmsg-0.16.0-py2.7.egg/fedmsg/consumers/__init__.py", line 25, in <module>
    import psutil
ImportError: No module named psutil

----------------------------------------------------------------------
Ran 335 tests in 138.787s

FAILED (errors=1)
```

**Comment by ralphbean** [comment]
Yup, those bits were split out into extras just a week or so ago.
