### ISSUE TITLE
ValueError: Cookie value is too long to store (4658 bytes)

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#5103]
Seeing this in both production and stg. Here's the stg one: 

```
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=2023-02-27 21:14:13,278 ERROR [bodhi.server][ThreadPoolExecutor-0_0] Error caught.  Handling HTML response.
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=Traceback (most recent call last):
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=  File "/usr/lib/python3.11/site-packages/pyramid/router.py", line 277, in default_execution_policy
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=    return router.invoke_request(request)
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=  File "/usr/lib/python3.11/site-packages/pyramid/router.py", line 252, in invoke_request
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=    request._process_response_callbacks(response)
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=  File "/usr/lib/python3.11/site-packages/pyramid/request.py", line 83, in _process_response_callbacks
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=    callback(self, response)
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=  File "/usr/lib/python3.11/site-packages/pyramid/session.py", line 337, in set_cookie_callback
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=    self._set_cookie(response)
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=  File "/usr/lib/python3.11/site-packages/pyramid/session.py", line 413, in _set_cookie
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=    raise ValueError(
Feb 27 21:14:14 worker01.ocp.stg.iad2.fedoraproject.org fluentd: namespace_name=bodhi, container_name=bodhi-web, pod_name=bodhi-web-80-zr4ph, message=ValueError: Cookie value is too long to store (4658 bytes)
```

I am not sure whats triggering it. Perhaps we could dump more information to logs?

**Comment by mattiaverga** [comment]
I see a lot of those errors in logs, but I have no idea what's going on. They started without any change on Bodhi side and Pyramid is still at 1.10 both on stg and prod.
I've also tried to search about "python pyramid Cookie value is too long to store" without finding anything related. At least, there dosn't seem to be users complaining about being unable to authenticate...

**Comment by nirik** [comment]
Yeah, it's puzzling. I think this might be because there is too much information it's trying to stick into the cookie. We had this happen before for people who were in a ton of groups and we put that group info in there. But that was changed a long time ago... 

and yeah, I have not seen any complaints or myself had any auth issues. ;(

**Comment by mattiaverga** [comment]
I haven't seen this specific error in bodhi logs, so I'm going to close this ticket. Please reopen if it's still actual.
