### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#514]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-12838 gives

500 Server Error

```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system)
File "/usr/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode as_unicode=True)
File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render **_kwargs_for_callable(callable_, data))
File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template callable_(context, *args, **kwargs) File "master_html", line 200, in render_body
File "/usr/lib/python2.7/site-packages/bodhi/templates/update.html", line 506, in render_body % elif update.pushed and (update.status.description != 'stable' or (update.status.description == 'stable' and 'releng' in [group.name for group in request.user.groups])):
File "/usr/lib/python2.7/site-packages/munch/__init__.py", line 128, in __getattr__ raise AttributeError(k) AttributeError: groups
```

**Comment by ralphbean** [comment]
Confirmed.  Will fix ASAP.

**Comment by ralphbean** [comment]
Hotfixed in production for now.  Will submit a patch shortly.
