### ISSUE TITLE
Json serialization crashes

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#5471]
Bodhi logs are borked with 

```
2023-08-24 19:10:30,619 ERROR [bodhi.server][ThreadPoolExecutor-0_1] Unhandled exception raised:  <JSONError at 0x7f789820ac80 500 Internal Server Error>
NoneType: None
2023-08-24 19:10:41,801 ERROR [bodhi.server][ThreadPoolExecutor-0_0] Error caught.  Handling JSON response.
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 965, in get
    return dict_[key]
           ~~~~~^^^^^
KeyError: 'epoch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
               ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/config/views.py", line 151, in __call__
    return view(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/viewderivers.py", line 450, in rendered_view
    response = view_renderer.render_view(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/renderers.py", line 443, in render_view
    return self.render_to_response(response, system, request=request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/renderers.py", line 466, in render_to_response
    result = self.render(value, system_values, request=request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/renderers.py", line 462, in render
    result = renderer(value, system_values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/renderers.py", line 276, in _render
    return self.serializer(value, default=default, **self.kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyramid/renderers.py", line 283, in default
    return obj.__json__(request)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 4153, in __json__
    result = super(Update, self).__json__(request=request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 406, in __json__
    return self._to_json(self, request=request, exclude=exclude, include=include)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 455, in _to_json
    d[attr] = cls._expand(obj, getattr(obj, attr), seen, request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 484, in _expand
    return [cls._expand(obj, item, seen, req) for item in relation]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 484, in <listcomp>
    return [cls._expand(obj, item, seen, req) for item in relation]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 486, in _expand
    return cls._to_json(relation, seen + [type(obj)], req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 437, in _to_json
    d = dict([(attr, getattr(obj, attr)) for attr in attrs
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 437, in <listcomp>
    d = dict([(attr, getattr(obj, attr)) for attr in attrs
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
    return self.impl.get(state, dict_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 968, in get
    util.raise_(
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
KeyError: "Deferred loader for attribute 'epoch' failed to populate correctly"
```

Can't understand where it comes from. The closest thing I've found is
https://github.com/sqlalchemy/sqlalchemy/issues/7304

No such error reported on staging instance.

**Comment by decathorpe** [comment]
I've been seeing this error when submitting updates via the web interface, and when querying updates via the API. Retrying usually makes it work, but it's really annoying when things like "Submit a new update" aren't reliable.

**Comment by mattiaverga** [comment]
Yesterday I saw the pod was restarted and now I can't see anymore this error in the logs... 🤫

**Comment by decathorpe** [comment]
Yeah, I haven't seen it happen yesterday ... maybe it was a transient issue that was resolved by the restart?

**Comment by mattiaverga** [comment]
Haven't seen this in a while, closing for now...
