### ISSUE TITLE
"cannot access local variable 'tags'" error when editing flatpak updates

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#5503]
When editing builds in a flatpak update, e.g. https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2023-38c6f050df/edit Bodhi seems to always show the following error and the update ends up in an "unpushed" state:

```
Builds : Unable to create update. cannot access local variable 'tags' where it is not associated with a value
```

**Comment by nirik** [comment]
FWIW, traceback is: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/bodhi/server/services/updates.py", line 574, in new_update
    result, _caveats = Update.edit(request, data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bodhi/server/models.py", line 2692, in edit
    for tag in tags:
               ^^^^
UnboundLocalError: cannot access local variable 'tags' where it is not associated with a value
```
