### ISSUE TITLE
fedpkg update ends with exception with naked sql query

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#575]
When running fedpkg update, I got an exception with sql query naked.

``` python
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 107, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: Unable to create update. (IntegrityError) duplicate key value violates unique constraint "builds_nvr_key"
DETAIL:  Key (nvr)=(golang-github-go-fsnotify-fsnotify-1.2.0-0.1.git96c060f.el6) already exists.
 'INSERT INTO builds (nvr, inherited, package_id, release_id, update_id) VALUES (%(nvr)s, %(inherited)s, %(package_id)s, %(release_id)s, %(update_id)s) RETURNING builds.id' {'package_id': 10748, 'release_id': None, 'update_id': None, 'nvr': u'golang-github-go-fsnotify-fsnotify-1.2.0-0.1.git96c060f.el6', 'inherited': False}
Could not generate update request: Command 'bodhi --new --release el6 --file bodhi.template golang-github-go-fsnotify-fsnotify-1.2.0-0.1.git96c060f.el6 --username jchaloup' returned non-zero exit status 1
```

**Comment by ralphbean** [comment]
Hm, some more data:

- There is an update for that build:  https://bodhi.fedoraproject.org/updates/golang-github-go-fsnotify-fsnotify-1.2.0-0.1.git96c060f.el6

Did you run the command twice?  Did it work the first time but fail on the second?  or vice versa?

**Comment by ingvagabund** [comment]
It occurred for the first time. The second time it was fine.

**Comment by ralphbean** [comment]
> It occurred for the first time. The second time it was fine.

That is very strange.  :p

**Comment by bowlofeggs** [comment]
I have not observed this problem during my tenure on Bodhi, so I will close this for now. Feel free to reopen if you think it is still an issue.
