### ISSUE TITLE
Bodhi2 crashes at startup when bugzilla is down

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#589]
We should probably patch it to allow the app to start up, but then only fail when we try to perform some bugzilla action.  (that way people can view the page to get info, even if they can't perform certain edits).

Here's the traceback from the logs:

``` python
Traceback (most recent call last):
  File "/usr/share/bodhi/bodhi.wsgi", line 15, in <module>
    application = get_app(ini_path, 'main')
  File "/usr/lib/python2.7/site-packages/pyramid/paster.py", line 31, in get_app
    global_conf=options)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 229, in invoke
    filtered = context.next_context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "/usr/lib/python2.7/site-packages/bodhi/__init__.py", line 106, in main
    from bodhi.models import DBSession, Base
  File "/usr/lib/python2.7/site-packages/bodhi/models/__init__.py", line 15, in <module>
    from models import *
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 55, in <module>
    from bodhi.bugs import bugtracker
  File "/usr/lib/python2.7/site-packages/bodhi/bugs.py", line 142, in <module>
    bugtracker = Bugzilla()
  File "/usr/lib/python2.7/site-packages/bodhi/bugs.py", line 61, in __init__
    cookiefile=None, tokenfile=None)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 394, in __init__
    self.__class__.__init__(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/bugzilla/rhbugzilla.py", line 55, in __init__
    _parent.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 448, in __init__
    self.connect(url)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 601, in connect
    self.login()
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 644, in login
    ret = self._login(self.user, self.password)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 613, in _login
    return self._proxy.User.login({'login': user, 'password': password})
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 263, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 236, in _request_helper
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: Service unavailable. This service is presently offline for maintenance commencing 2015-09-19 20:04:51 EDT, the duration of maintenance is expected to be 10-14 hours.
```

**Comment by ralphbean** [comment]
FYI, Bugzilla outage scheduled for tomorrow, March 29th.

**Comment by bowlofeggs** [comment]
I don't believe this happens anymore.
