### ISSUE TITLE
Bodhi does not expire buildroot overrides

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#616]
See: https://bodhi.fedoraproject.org/overrides/eclipse-remote-2.0.0-0.1.git76ac23a.fc22

Expiration date is in the past, yet this override is still "active" and the build is tagged in koji: https://koji.fedoraproject.org/koji/buildinfo?buildID=680588

Clicking the "Expire" button in bodhi results in an error "Expiration date in the past"

Performing "koji untag-build" results in an error "ActionNotAllowed: tag requires fedora-override permission"

How do I untag this build?

**Comment by mbooth101** [comment]
The polluted build root is preventing some other builds, so this is blocking other work.

**Comment by tyll** [comment]
I untagged it manually for you.

**Comment by mbooth101** [comment]
Thanks -- I appear to have two other buildroot overrides with the same problem, for three in total:

https://bodhi.fedoraproject.org/overrides/eclipse-remote-2.0.0-0.1.git76ac23a.fc22
https://bodhi.fedoraproject.org/overrides/eclipse-launchbar-1.0.0-0.3.git01bfa62.fc22
https://bodhi.fedoraproject.org/overrides/eclipse-tm-terminal-4.0.0-3.fc22

These all show "active" in bodhi but the expiry date is long in the past.

**Comment by mbooth101** [comment]
I am also having problems "re-tagging" these builds.... See https://fedorahosted.org/rel-eng/ticket/6270

**Comment by tyll** [comment]
afaics there is something missing (a cronjob?) that runs /usr/bin/bodhi-expire-overrides but it might also be broken -  when I try to run it manually there are several tracebacks and the build is not untagged.

**Comment by tyll** [comment]
Errors:
```
2015-10-07 19:25:46,677 INFO  [bodhi.scripts.expire_overrides][MainThread] Expiring 183 buildroot overrides...
2015-10-07 19:25:46,810 WARNI [bodhi][MainThread] No buildsystem configured; assuming testing
2015-10-07 19:25:46,810 DEBUG [bodhi][MainThread] untagBuild(f23-override, fedmsg-0.15.0-1.fc23)
2015-10-07 19:25:47,926 INFO  [bodhi][MainThread] fedmsg initialized
2015-10-07 19:25:47,926 DEBUG [bodhi][MainThread] fedmsg enqueueing 'buildroot_override.untag'
2015-10-07 19:25:47,926 INFO  [bodhi.scripts.expire_overrides][MainThread] Expired fedmsg-0.15.0-1.fc23
2015-10-07 19:25:47,959 DEBUG [bodhi][MainThread] fedmsg sending 'buildroot_override.untag'
2015-10-07 19:25:47,960 CRITI [txn.139633908451136][MainThread] A storage error occurred during the second phase of the two-phase commit.  Resources may be in an inconsistent state.
2015-10-07 19:25:47,960 ERROR [txn.139633908451136][MainThread] Error in tpc_abort() on manager <zope.sqlalchemy.datamanager.SessionDataManager object at 0x3a8d650>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/transaction/_transaction.py", line 432, in _cleanup
    rm.tpc_abort(self)
  File "/usr/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 110, in tpc_abort
    assert self.state is not 'committed'
AssertionError
Traceback (most recent call last):
  File "/usr/bin/bodhi-expire-overrides", line 9, in <module>
    load_entry_point('bodhi==2.0', 'console_scripts', 'bodhi-expire-overrides')()
  File "/usr/lib/python2.7/site-packages/bodhi/scripts/expire_overrides.py", line 69, in main
    log.info("Expired %s" % override.build.nvr)
  File "/usr/lib/python2.7/site-packages/transaction/_manager.py", line 120, in __exit__
    self.commit()
  File "/usr/lib/python2.7/site-packages/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/usr/lib/python2.7/site-packages/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/usr/lib/python2.7/site-packages/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/usr/lib/python2.7/site-packages/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/usr/lib/python2.7/site-packages/transaction/_transaction.py", line 399, in _commitResources
    rm.tpc_finish(self)
  File "/usr/lib/python2.7/site-packages/bodhi/notifications.py", line 178, in tpc_finish
    fedmsg.publish(topic=topic, msg=msg)
  File "/usr/lib/python2.7/site-packages/fedmsg/__init__.py", line 79, in _wrapper
    return func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/fedmsg/__init__.py", line 94, in publish
    return __local.__context.publish(topic, msg, **kw)
  File "/usr/lib/python2.7/site-packages/fedmsg/core.py", line 289, in publish
    self.c['certname'] = self.c['certnames'][cert_index]
KeyError: 'bodhi.bodhi-backend02'
```

**Comment by ralphbean** [comment]
- That ``No buildsystem configured`` error means that it isn't talking to koji.  It's just talking to an in-memory shim that will end up doing nothing.
- That KeyError I can fix!  The cert just seems to be missing?

**Comment by ralphbean** [comment]
OK, cert should be in place (fixing the second half).

**Comment by tyll** [comment]
I found the koji bug, the buildsystem needs to be setup from the settings afaics, will prepare a PR.

**Comment by tyll** [comment]
There are more issues:
- If I setup the build system similar to #642, then pkgs are untagged, but the overrides are not expired in the db
- When builds are expired when moved to stable in https://github.com/fedora-infra/bodhi/blob/develop/bodhi/consumers/masher.py#L563-L572 then appear to be untagged but not marked as expired in the db
- the expiration_date should probably be set to the expired_date if the move to stable makes a override expired or if a override is manually expired to get consistent in the UI
- if a build is already untagged the koji call in https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/models.py#L2129-L2141 will create a traceback and make the script fail/not process further overrides

**Comment by lmacken** [comment]
In my local testing the expire_overrides.py job does correctly untag and expire them in the db. I'm going to setup the cron job on bodhi-backend02 after fixing the 'build is already untagged' exception.

**Comment by lmacken** [comment]
This has been deployed and run. A ton of overrides have just been expired. Please reopen this issue if you notice anything fishy.
