### ISSUE TITLE
Unable to edit update

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#697]
```python
[Thu Nov 05 20:16:25.857276 2015] [:error] [pid 9186] 2015-11-05 20:16:25,857 DEBUG [bodhi][Dummy-4] validated = {'close_bugs':[46/1874]
table_karma': 2, 'csrf_token': u'3d31ad57bc4873bc09b11cb6aeb438250c5f151e', 'requirements': None, 'builds': [u'angelscript-2.30.2-2.fc23
', u'supertuxkart-0.9.1-2.fc23'], 'autokarma': True, 'edited': u'angelscript-2.30.2-1.fc23 supertuxkart-0.9.1-2.fc23', 'suggest': <unspe
cified>, 'notes': u'supertuxkart-0.9.1-2.fc23\\n\\n- Update to 0.9.1\\n- Rebuild for new angelscript\\n\\n\\nangelscript-2.30.2-1.fc23\\
n\\n- Update to 2.30.2\\n', 'request': <testing>, 'bugs': [1208136, 1275519], 'unstable_karma': -3, 'require_bugs': True, 'require_testc
ases': True, 'type': <bugfix>, 'severity': <medium>}
[Thu Nov 05 20:16:25.877047 2015] [:error] [pid 9186] 2015-11-05 20:16:25,876 DEBUG [bodhi][Dummy-4] Adding nvr angelscript-2.30.2-2.fc2
3
[Thu Nov 05 20:16:25.966125 2015] [:error] [pid 9186] 2015-11-05 20:16:25,965 INFO  [bodhi][Dummy-4] Editing update: angelscript-2.30.2-
1.fc23 supertuxkart-0.9.1-2.fc23
[Thu Nov 05 20:16:26.084624 2015] [:error] [pid 9186] 2015-11-05 20:16:26,084 INFO  [bodhi][Dummy-4] Unpushing angelscript-2.30.2-1.fc23
[Thu Nov 05 20:16:26.289185 2015] [:error] [pid 9186] 2015-11-05 20:16:26,205 ERROR [bodhi][Dummy-4] Failed to create update
[Thu Nov 05 20:16:26.289220 2015] [:error] [pid 9186] Traceback (most recent call last):
[Thu Nov 05 20:16:26.289224 2015] [:error] [pid 9186]   File "/usr/lib/python2.7/site-packages/bodhi/services/updates.py", line 350, in 
new_update
[Thu Nov 05 20:16:26.289226 2015] [:error] [pid 9186]     result, _caveats = Update.edit(request, data)
[Thu Nov 05 20:16:26.289228 2015] [:error] [pid 9186]   File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 803, in edi
t
[Thu Nov 05 20:16:26.289230 2015] [:error] [pid 9186]     up.comment(db, comment, karma=0, author=u'bodhi')
[Thu Nov 05 20:16:26.289232 2015] [:error] [pid 9186]   File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1429, in co
mment
[Thu Nov 05 20:16:26.289234 2015] [:error] [pid 9186]     session.flush()
[Thu Nov 05 20:16:26.289236 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, 
in flush
[Thu Nov 05 20:16:26.289238 2015] [:error] [pid 9186]     self._flush(objects)
[Thu Nov 05 20:16:26.289240 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, 
in _flush
[Thu Nov 05 20:16:26.289242 2015] [:error] [pid 9186]     transaction.rollback(_capture_exception=True)
[Thu Nov 05 20:16:26.289244 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 6
0, in __exit__
[Thu Nov 05 20:16:26.289246 2015] [:error] [pid 9186]     compat.reraise(exc_type, exc_value, exc_tb)
[Thu Nov 05 20:16:26.289254 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, 
in _flush
[Thu Nov 05 20:16:26.289257 2015] [:error] [pid 9186]     flush_context.execute()
[Thu Nov 05 20:16:26.289258 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372
, in execute
[Thu Nov 05 20:16:26.289261 2015] [:error] [pid 9186]     rec.execute(self)
[Thu Nov 05 20:16:26.289264 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526
, in execute
[Thu Nov 05 20:16:26.289266 2015] [:error] [pid 9186]     uow
[Thu Nov 05 20:16:26.289268 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 60
, in save_obj
[Thu Nov 05 20:16:26.289269 2015] [:error] [pid 9186]     mapper, table, update)
[Thu Nov 05 20:16:26.289272 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 51
8, in _emit_update_statements
[Thu Nov 05 20:16:26.289274 2015] [:error] [pid 9186]     execute(statement, params)
[Thu Nov 05 20:16:26.289309 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, i
n execute
[Thu Nov 05 20:16:26.289311 2015] [:error] [pid 9186]     return meth(self, multiparams, params)
[Thu Nov 05 20:16:26.289313 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, 
in _execute_on_connection
[Thu Nov 05 20:16:26.289315 2015] [:error] [pid 9186]     return connection._execute_clauseelement(self, multiparams, params)
[Thu Nov 05 20:16:26.289317 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, i
n _execute_clauseelement
[Thu Nov 05 20:16:26.289319 2015] [:error] [pid 9186]     compiled_sql, distilled_params
[Thu Nov 05 20:16:26.289321 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, i
n _execute_context
[Thu Nov 05 20:16:26.289323 2015] [:error] [pid 9186]     context)
[Thu Nov 05 20:16:26.289325 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, 
in _handle_dbapi_exception
[Thu Nov 05 20:16:26.289327 2015] [:error] [pid 9186]     exc_info
[Thu Nov 05 20:16:26.289343 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, i
n raise_from_cause
[Thu Nov 05 20:16:26.289345 2015] [:error] [pid 9186]     reraise(type(exception), exception, tb=exc_tb)
[Thu Nov 05 20:16:26.289346 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, i
n _execute_context
[Thu Nov 05 20:16:26.289348 2015] [:error] [pid 9186]     context)
[Thu Nov 05 20:16:26.289349 2015] [:error] [pid 9186]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436
, in do_execute
[Thu Nov 05 20:16:26.289351 2015] [:error] [pid 9186]     cursor.execute(statement, parameters)
[Thu Nov 05 20:16:26.289353 2015] [:error] [pid 9186] IntegrityError: (IntegrityError) null value in column "build_id" violates not-null
 constraint
[Thu Nov 05 20:16:26.289355 2015] [:error] [pid 9186] DETAIL:  Failing row contains (778, null, 344, for STK rebuild, 2015-10-27 06:56:4
2.529626, 2015-10-28 00:00:00, 2015-10-28 00:00:05.304179).
[Thu Nov 05 20:16:26.289357 2015] [:error] [pid 9186]  'UPDATE buildroot_overrides SET build_id=%(build_id)s WHERE buildroot_overrides.i
d = %(buildroot_overrides_id)s' {'build_id': None, 'buildroot_overrides_id': 778}

```

\cc @ignatenkobrain

**Comment by lmacken** [comment]
I queued up a patch to fix this bug, and in the mean time added `angelscript-2.30.2-2.fc23` to the update by hand.

**Comment by ignatenkobrain** [comment]
Many thanks! Is it now fixed in primary instance and I can fix other builds?

**Comment by lmacken** [comment]
This issue has been fixed in production. Please re-open if you still experience this problem. Thanks!

**Comment by ignatenkobrain** [comment]
Cool! Thanks!
