### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 95: ordinal not in range(128) 

### ISSUE THREAD

**Issue by mike-fabian** [fedora-infra/bodhi#705]
If I click the following 3 links for the ibus-typing-booster-1.2.15-1
updates on

https://bodhi.fedoraproject.org/users/mfabian

ibus-typing-booster-1.2.15-1.fc23
https://bodhi.fedoraproject.org/updates/FEDORA-2015-c97e8a4bd5

ibus-typing-booster-1.2.15-1.fc22
https://bodhi.fedoraproject.org/updates/FEDORA-2015-ccb91a63a8

ibus-typing-booster-1.2.15-1.fc21
https://bodhi.fedoraproject.org/updates/FEDORA-2015-2c65f7392a

I get a Python backtrace:

500 Server Error

Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system) File "/usr/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode as_unicode=True) File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 784, in _render return context._pop_buffer().getvalue() File "/usr/lib/python2.7/site-packages/mako/util.py", line 150, in getvalue return self.delim.join(self.data) UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 95: ordinal not in range(128)

**Comment by mike-fabian** [comment]
I see the same problem for these ibus-table updates:

https://bodhi.fedoraproject.org/updates/FEDORA-2015-67b99c3223
https://bodhi.fedoraproject.org/updates/FEDORA-2015-300e8d7e09
https://bodhi.fedoraproject.org/updates/FEDORA-2015-3de4709749
