### ISSUE TITLE
Bodhi errors out replacing one build with another

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#706]
I am trying to edit https://bodhi.fedoraproject.org/updates/FEDORA-2015-2e33c48936 and replace gtk3-3.18.5-2.fc23 with gtk3-3.18.5-3.fc23, but it errors out without any details. I asked in #fedora-apps yesterday and threebean found the following in the logs:
```
[Fri Nov 20 19:03:11.578260 2015] [:error] [pid 30001] 2015-11-20 19:03:11,577 INFO  [bodhi][Dummy-2] Unpushing gtk3-3.18.5-2.fc23
[Fri Nov 20 19:03:11.706569 2015] [:error] [pid 30001] 2015-11-20 19:03:11,705 ERROR [bodhi][Dummy-2] Failed to create update
[Fri Nov 20 19:03:11.706601 2015] [:error] [pid 30001] Traceback (most recent call last):
[Fri Nov 20 19:03:11.706606 2015] [:error] [pid 30001]   File "/usr/lib/python2.7/site-packages/bodhi/services/updates.py", line 350, in new_update
[Fri Nov 20 19:03:11.706610 2015] [:error] [pid 30001]     result, _caveats = Update.edit(request, data)
[Fri Nov 20 19:03:11.706614 2015] [:error] [pid 30001]   File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 803, in edit
[Fri Nov 20 19:03:11.706617 2015] [:error] [pid 30001]     up.comment(db, comment, karma=0, author=u'bodhi')
[Fri Nov 20 19:03:11.706621 2015] [:error] [pid 30001]   File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1429, in comment
[Fri Nov 20 19:03:11.706624 2015] [:error] [pid 30001]     session.flush()
[Fri Nov 20 19:03:11.706628 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
[Fri Nov 20 19:03:11.706631 2015] [:error] [pid 30001]     self._flush(objects)
[Fri Nov 20 19:03:11.706635 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
[Fri Nov 20 19:03:11.706638 2015] [:error] [pid 30001]     transaction.rollback(_capture_exception=True)
[Fri Nov 20 19:03:11.706641 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
[Fri Nov 20 19:03:11.706644 2015] [:error] [pid 30001]     compat.reraise(exc_type, exc_value, exc_tb)
[Fri Nov 20 19:03:11.706648 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
[Fri Nov 20 19:03:11.706667 2015] [:error] [pid 30001]     flush_context.execute()
[Fri Nov 20 19:03:11.706671 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
[Fri Nov 20 19:03:11.706675 2015] [:error] [pid 30001]     rec.execute(self)
[Fri Nov 20 19:03:11.706678 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
[Fri Nov 20 19:03:11.706681 2015] [:error] [pid 30001]     uow
[Fri Nov 20 19:03:11.706684 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
[Fri Nov 20 19:03:11.706688 2015] [:error] [pid 30001]     mapper, table, update)
[Fri Nov 20 19:03:11.706691 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 518, in _emit_update_statements
[Fri Nov 20 19:03:11.706695 2015] [:error] [pid 30001]     execute(statement, params)
[Fri Nov 20 19:03:11.706698 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
[Fri Nov 20 19:03:11.706701 2015] [:error] [pid 30001]     return meth(self, multiparams, params)
[Fri Nov 20 19:03:11.706704 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
[Fri Nov 20 19:03:11.706708 2015] [:error] [pid 30001]     return connection._execute_clauseelement(self, multiparams, params)
[Fri Nov 20 19:03:11.706711 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
[Fri Nov 20 19:03:11.706714 2015] [:error] [pid 30001]     compiled_sql, distilled_params
[Fri Nov 20 19:03:11.706717 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
[Fri Nov 20 19:03:11.706720 2015] [:error] [pid 30001]     context)
[Fri Nov 20 19:03:11.706723 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
[Fri Nov 20 19:03:11.706726 2015] [:error] [pid 30001]     exc_info
[Fri Nov 20 19:03:11.706729 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
[Fri Nov 20 19:03:11.706733 2015] [:error] [pid 30001]     reraise(type(exception), exception, tb=exc_tb)
[Fri Nov 20 19:03:11.706736 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
[Fri Nov 20 19:03:11.706739 2015] [:error] [pid 30001]     context)
[Fri Nov 20 19:03:11.706742 2015] [:error] [pid 30001]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
[Fri Nov 20 19:03:11.706745 2015] [:error] [pid 30001]     cursor.execute(statement, parameters)
[Fri Nov 20 19:03:11.706779 2015] [:error] [pid 30001] IntegrityError: (IntegrityError) null value in column "build_id" violates not-null constraint
[Fri Nov 20 19:03:11.706784 2015] [:error] [pid 30001] DETAIL:  Failing row contains (1075, null, 285, For building nautilus, 2015-11-18 14:59:58.970225, 2015-11-19 00:00:00, 2015-11-19 00:00:09.062833).
[Fri Nov 20 19:03:11.706789 2015] [:error] [pid 30001]  'UPDATE buildroot_overrides SET build_id=%(build_id)s WHERE buildroot_overrides.id = %(buildroot_overrides_id)s' {'build_id': None, 'buildroot_overrides_id': 1075}
```

This is likely the same thing as https://github.com/fedora-infra/bodhi/issues/697 , but I am filing it separately to track the fix here as suggested by lmacken -- would it be possible to manually fix up the update for now until the bodhi fix is in place, and replace gtk3-3.18.5-2.fc23 with gtk3-3.18.5-3.fc23 please?

Thanks,
Kalev

**Comment by kalev** [comment]
I put gtk3-3.18.5-3.fc23 in a separate update for now to get it out to testing since everybody who can edit the update seems to have gone to bed already :)

Would still be great to merge these two updates together if possible.

**Comment by kalev** [comment]
Anyway, no more urgency here as I managed to work this around by submitting two separate updates. Thanks for the attention :)

**Comment by lmacken** [comment]
Sorry, I was about to go and manually fix this in the db. I was trying to get a fix deployed to production yesterday, but we're hitting some database upgrade issues in staging that I'm working on now.

**Comment by lmacken** [comment]
This fix has been pushed to production
