### ISSUE TITLE
Exception creating buildroot override

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#714]
```python

[Wed Nov 25 11:32:11.623890 2015] [:error] [pid 22166] 2015-11-25 11:32:11,623 DEBUG [bodhi][Dummy-1] fedmsg sending u'update.request.testing'
[Wed Nov 25 11:32:30.234526 2015] [:error] [pid 22165] 2015-11-25 11:32:30,234 INFO  [bodhi][Dummy-1] Creating a new buildroot override: eclipse-emf-mwe-2.9.0-0.2.gita872c98.fc23
[Wed Nov 25 11:32:30.235871 2015] [:error] [pid 22165] 2015-11-25 11:32:30,235 ERROR [bodhi][Dummy-1] Error caught.  Handling HTML response.
[Wed Nov 25 11:32:30.235891 2015] [:error] [pid 22165] Traceback (most recent call last):
[Wed Nov 25 11:32:30.235894 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
[Wed Nov 25 11:32:30.235896 2015] [:error] [pid 22165]     response = handler(request)
[Wed Nov 25 11:32:30.235898 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
[Wed Nov 25 11:32:30.235899 2015] [:error] [pid 22165]     reraise(*exc_info)
[Wed Nov 25 11:32:30.235902 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
[Wed Nov 25 11:32:30.235904 2015] [:error] [pid 22165]     response = handler(request)
[Wed Nov 25 11:32:30.235906 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
[Wed Nov 25 11:32:30.235908 2015] [:error] [pid 22165]     response = view_callable(context, request)
[Wed Nov 25 11:32:30.235925 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
[Wed Nov 25 11:32:30.235928 2015] [:error] [pid 22165]     return view(context, request)
[Wed Nov 25 11:32:30.235929 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
[Wed Nov 25 11:32:30.235931 2015] [:error] [pid 22165]     return view(context, request)
[Wed Nov 25 11:32:30.235933 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
[Wed Nov 25 11:32:30.235943 2015] [:error] [pid 22165]     return view(context, request)
[Wed Nov 25 11:32:30.235945 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
[Wed Nov 25 11:32:30.235947 2015] [:error] [pid 22165]     result = view(context, request)
[Wed Nov 25 11:32:30.235949 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
[Wed Nov 25 11:32:30.235950 2015] [:error] [pid 22165]     response = view(request)
[Wed Nov 25 11:32:30.235952 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/cornice/service.py", line 569, in wrapper
[Wed Nov 25 11:32:30.235954 2015] [:error] [pid 22165]     response = view_(request)
[Wed Nov 25 11:32:30.235956 2015] [:error] [pid 22165]   File "/usr/lib/python2.7/site-packages/bodhi/services/overrides.py", line 234, in save_override
[Wed Nov 25 11:32:30.235967 2015] [:error] [pid 22165]     result = result.__json__()
[Wed Nov 25 11:32:30.236002 2015] [:error] [pid 22165] AttributeError: 'NoneType' object has no attribute '__json__'
```

**Comment by mbooth101** [comment]
Is this a dupe of #713 ??

eclipse-emf-mwe is exactly the package I experienced a problem with!

**Comment by lmacken** [comment]
Yep, you're right. Working on a fix for this now.
