### ISSUE TITLE
500 error rendering specific update

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#732]
From the production logs:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "master_html", line 238, in render_body
    
  File "/usr/lib/python2.7/site-packages/bodhi/templates/update.html", line 613, in render_body
    ${self.fragments.comment(comment, display_update=False)}
  File "fragments_html", line 123, in render_comment
    
  File "/usr/lib/python2.7/site-packages/bodhi/util.py", line 474, in bug_link
    url = "https://bugzilla.redhat.com/show_bug.cgi?id=" + str(bug.bug_id)
AttributeError: 'NoneType' object has no attribute 'bug_id'


```

**Comment by lmacken** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16259

**Comment by lmacken** [comment]
```
>>> db.query(m.BugKarma).filter_by(bug_id=None).count()
10L
```

**Comment by lmacken** [comment]
I just deleted all BugKarma from the db that doesn't have associated Bugs to clear this up.
