### ISSUE TITLE
Test for obsoletion for edited update failing with error: Submitting earlier build for testing again

### ISSUE THREAD

**Issue by trishnaguha** [fedora-infra/bodhi#855]
Test for obsoletion for edited update is failing with error. 
It is sending the earlier build to testing again ever after it is unpushed whereas we expect only the newer build to be sent for testing after obsoletion.

I think we can relate this issue with https://github.com/fedora-infra/bodhi/issues/845 . 
So both the builds were sent for testing even after unpushing the earlier one for the `grub2` update https://bodhi.fedoraproject.org/updates/FEDORA-2016-c4d43baacc and the results and karma might got mixed up.

The test is here https://paste.fedoraproject.org/386958/ .

Here is the traceback:

```
======================================================================
ERROR: test_obsoletion_on_edit_testing_update (bodhi.tests.functional.test_updates.TestUpdatesService)
Test for obsoletion on edited update
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trishna/.virtualenv/bodhi-python2.7/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/trishna/Workspace/bodhi/bodhi/tests/functional/test_updates.py", line 1878, in test_obsoletion_on_edit_testing_update
    self.assertEquals(up['status'], 'obsolete')
TypeError: 'NoneType' object has no attribute '__getitem__'
-------------------- >> begin captured logging << --------------------
bodhi: DEBUG: Creating all models for Engine(sqlite://)
bodhi: DEBUG: Setting alias for bodhi-2.0-1.fc17 to FEDORA-2016-a3bbe1a8f2
dogpile.core.dogpile: DEBUG: NeedRegenerationException
dogpile.core.dogpile: DEBUG: no value, waiting for create lock
dogpile.core.dogpile: DEBUG: value creation lock <dogpile.cache.region._LockWrapper object at 0x7f81dbb59310> acquired
dogpile.core.dogpile: DEBUG: Calling creation function
dogpile.core.dogpile: DEBUG: Released creation lock
bodhi: DEBUG: validated = {'close_bugs': True, 'stable_karma': 3, 'csrf_token': u'7f8936c5d47dc1e6297f78e7429a50122d017d76', 'requirements': u'rpmlint', 'builds': [u'bodhi-2.0.0-2.fc17'], 'autokarma': True, 'edited': '', 'suggest': <unspecified>, 'notes': u'this is a test update', 'request': <testing>, 'bugs': [], 'unstable_karma': -3, 'require_bugs': False, 'require_testcases': True, 'type': <bugfix>, 'severity': <unspecified>}
bodhi: DEBUG: Adding nvr bodhi-2.0.0-2.fc17
bodhi: INFO: Creating new update: [<Build {'epoch': 0, 'nvr': u'bodhi-2.0.0-2.fc17'}>]
bodhi: DEBUG: Creating new Update(**data) object.
bodhi: DEBUG: Assigning alias for new update..
bodhi: DEBUG: Setting alias for bodhi-2.0.0-2.fc17 to FEDORA-2016-0ee4a77202
bodhi: DEBUG: Setting request for new update.
bodhi: DEBUG: Attempting to set request <testing>
bodhi: DEBUG: Adding tag f17-updates-testing-pending to bodhi-2.0.0-2.fc17
bodhi: DEBUG: tagBuild(f17-updates-testing-pending, bodhi-2.0.0-2.fc17)
bodhi: DEBUG: bodhi-2.0.0-2.fc17 has been submitted for testing. 
bodhi: INFO: Sending mail to guest: [Fedora Update] [comment] bodhi-2.0.0-2.fc17
bodhi: INFO: Not sending email: No smtp_server defined
bodhi: DEBUG: Adding new update to the db.
bodhi: DEBUG: Triggering db flush for new update.
bodhi: DEBUG: Done with Update.new(...)
bodhi: DEBUG: bodhi-2.0.0-2.fc17 update created
dogpile.core.dogpile: DEBUG: NeedRegenerationException
dogpile.core.dogpile: DEBUG: no value, waiting for create lock
dogpile.core.dogpile: DEBUG: value creation lock <dogpile.cache.region._LockWrapper object at 0x7f81db89d1d0> acquired
dogpile.core.dogpile: DEBUG: Calling creation function
dogpile.core.dogpile: DEBUG: Released creation lock
bodhi: DEBUG: validated = {'close_bugs': True, 'stable_karma': 3, 'csrf_token': u'7f8936c5d47dc1e6297f78e7429a50122d017d76', 'requirements': u'rpmlint', 'builds': [u'bodhi-2.0.0-3.fc17'], 'autokarma': True, 'edited': u'bodhi-2.0.0-2.fc17', 'suggest': <unspecified>, 'notes': u'this is a test update', 'request': <testing>, 'bugs': [], 'unstable_karma': -3, 'require_bugs': False, 'require_testcases': True, 'type': <bugfix>, 'severity': <unspecified>}
bodhi: DEBUG: Adding nvr bodhi-2.0.0-3.fc17
bodhi: INFO: Editing update: bodhi-2.0.0-2.fc17
bodhi: INFO: Unpushing bodhi-2.0.0-2.fc17
bodhi: INFO: Moving bodhi-2.0.0-2.fc17 from f17-updates-testing to f17-updates-candidate
bodhi: DEBUG: moveBuild(f17-updates-testing, f17-updates-candidate, bodhi-2.0.0-2.fc17)
bodhi: INFO: Sending mail to guest: [Fedora Update] [comment] bodhi-2.0.0-2.fc17
bodhi: INFO: Not sending email: No smtp_server defined
bodhi: DEBUG: Unpushing bodhi-2.0.0-2.fc17
bodhi: INFO: Untagging bodhi-2.0.0-2.fc17
bodhi: DEBUG: untagBuild(f17-updates-candidate, bodhi-2.0.0-3.fc17)
bodhi: INFO: Skipping tag that we don't know about: f17
bodhi: DEBUG: untagBuild(f17-updates-testing, bodhi-2.0.0-3.fc17)
bodhi: DEBUG: tagBuild(f17-updates-candidate, bodhi-2.0.0-3.fc17)
bodhi: DEBUG: tagBuild(f17-updates-testing-pending, bodhi-2.0.0-3.fc17)
bodhi: DEBUG: Attempting to set request <testing>
bodhi: DEBUG: Adding tag f17-updates-testing-pending to bodhi-2.0.0-2.fc17
bodhi: DEBUG: tagBuild(f17-updates-testing-pending, bodhi-2.0.0-3.fc17)
bodhi: DEBUG: bodhi-2.0.0-2.fc17 has been submitted for testing. 
bodhi: INFO: Sending mail to guest: [Fedora Update] [comment] bodhi-2.0.0-2.fc17
bodhi: INFO: Not sending email: No smtp_server defined
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

**Comment by bowlofeggs** [comment]
The tests all pass now.
