### ISSUE TITLE
bodhi doesn't understand FAS groups as committers

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#872]
I'm in the FAS group [group::qa-tools-sig](https://admin.fedoraproject.org/pkgdb/packager/group::qa-tools-sig/). That group is set as the owner and a committer for [testcloud](https://admin.fedoraproject.org/pkgdb/package/rpms/testcloud/). I can commit to dist-git just fine, build in Koji. But I can't create an update in Bodhi:

```
$ fedpkg update 
No handlers could be found for logger "fedora.client.bodhi"
Creating a new update for  testcloud-0.1.9-1.fc24 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 93, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: kparal does not have commit access to testcloud
Could not generate update request: Command 'bodhi --new --release f24 --file bodhi.template testcloud-0.1.9-1.fc24 --username kparal' returned non-zero exit status 1
```

![bodhi](https://cloud.githubusercontent.com/assets/755451/16950416/71549856-4dc0-11e6-9313-3dc2bd5005ae.png)

Am I doing something wrong or does Bodhi not understand FAS groups correctly?

**Comment by piotr1212** [comment]
I'm running into the same issue. 
I'm member of group::nodejs-sig which is admin and has commit access on package nodejs. I can push git commit's and requests builds on koji but can't create an update in bodhi.

```
fedpkg update
No handlers could be found for logger "fedora.client.bodhi"
Creating a new update for  nodejs-0.10.46-1.el7 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 93, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: piotrp does not have commit access to nodejs
Could not generate update request: Command 'bodhi --new --release epel7 --file bodhi.template nodejs-0.10.46-1.el7 --username piotrp' returned non-zero exit status 1
```

**Comment by lmacken** [comment]
I added the `qa-tools-sig` and `nodejs-sig` groups to the `important_groups` list in ansible for our bodhi deployment.

Here is the patch for future reference. We should figure out a way to do this automatically at some point.

```
--- a/roles/bodhi2/base/templates/production.ini.j2
+++ b/roles/bodhi2/base/templates/production.ini.j2
@@ -371,7 +371,7 @@ buildroot_overrides.expire_after = 1
 # When a user logs in, bodhi will look for any of these groups and associate #
 # them with the user. They will then appear as the users effective principals in
 # the format "group:groupname" and can be used in Pyramid ACE's.
-important_groups = proventesters provenpackager releng security_respons packager bodhiadmin virtmaint-sig kde-sig eclipse-sig infra-sig gnome-sig python-sig robotics-sig qa-tools-sig
+important_groups = proventesters provenpackager releng security_respons packager bodhiadmin virtmaint-sig kde-sig eclipse-sig infra-sig gnome-sig python-sig robotics-sig qa-tools-sig nodejs-sig

 # Groups that can push updates for any package
 admin_packager_groups = provenpackager releng security_respons

```
