### ISSUE TITLE
RepodataException: Checksum mismatch during epel7-testing mash today

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#977]
I don't know much about this, but today's epel7-testing mash failed with this traceback:

```
Sep 24 14:42:07 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:07][bodhi.server.metadata    INFO]epel7-testing Inserting /tmp/tmpOmauFM into /mnt/koji/mash/updates/epel7-testing-160923.0324/epel7-testing/SRPMS/
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][bodhi.server.metadata    INFO]epel7-testing /mnt/koji/mash/updates/epel7-testing-160923.0324/epel7-testing/x86_64/repodata cached to /mnt/koji/
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg    INFO]epel7-testing Running sanity checks on /mnt/koji/mash/updates/epel7-testing-160923.0324/epel7-testing
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg   ERROR]epel7-testing Repodata sanity check failed!
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: Checksum mismatch /mnt/koji/mash/updates/epel7-testing-160923.0324/epel7-testing/x86_64/repodata/4863ca2a398a74f712e823ff82c6a50d575d9511d410acc93fe4f92eac4799c7-upd
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg   ERROR]epel7-testing Exception in MasherThread(epel7-testing)
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: Traceback (most recent call last):
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 359, in work
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.sanity_check_repo()
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 749, in sanity_check_repo
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     sanity_check_repodata(repodata)
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 235, in sanity_check_repodata
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     raise RepodataException(msg)
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: RepodataException: Checksum mismatch /mnt/koji/mash/updates/epel7-testing-160923.0324/epel7-testing/x86_64/repodata/4863ca2a398a74f712e823ff82c6a50d575d9511d410acc93
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg    INFO]epel7-testing Masher lock saved: /mnt/koji/mash/updates/MASHING-epel7-testing
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg    INFO]epel7-testing Thread(epel7-testing) finished.  Success: False
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg   ERROR]epel7-testing MasherThread failed. Transaction rolled back.
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: Traceback (most recent call last):
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 258, in run
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.work()
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 359, in work
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.sanity_check_repo()
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 749, in sanity_check_repo
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     sanity_check_repodata(repodata)
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 235, in sanity_check_repodata
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     raise RepodataException(msg)
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: RepodataException: Checksum mismatch /mnt/koji/mash/updates/epel7-testing-160923.0324/epel7-testing/x86_64/repodata/4863ca2a398a74f712e823ff82c6a50d575d9511d410acc93
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg    INFO]PoolThread-twisted.internet.reactor-0 Push complete!  Summary follows:
Sep 24 14:42:08 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-24 14:42:08][    fedmsg    INFO]PoolThread-twisted.internet.reactor-0   name:  epel7-testing         success:  False
```

**Comment by bowlofeggs** [comment]
The epel5-testing mash failed today, also in the `sanity_check_repo` method, but with a further crash due to too many open files:

```
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-25 03:59:49][    fedmsg    INFO]dist-5E-epel-testing Thread(dist-5E-epel-testing) finished.  Success: False
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: [2016-09-25 03:59:49][    fedmsg   ERROR]dist-5E-epel-testing MasherThread failed. Transaction rolled back.
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: Traceback (most recent call last):
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 258, in run
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.work()
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 359, in work
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.sanity_check_repo()
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 751, in sanity_check_repo
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.log.error("Repodata sanity check failed!\n%s" % str(e))
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/logging/__init__.py", line 1193, in error
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self._log(ERROR, msg, args, **kwargs)
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/logging/__init__.py", line 1286, in _log
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.handle(record)
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/logging/__init__.py", line 1296, in handle
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     self.callHandlers(record)
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/logging/__init__.py", line 1336, in callHandlers
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     hdlr.handle(record)
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/logging/__init__.py", line 755, in handle
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     rv = self.filter(record)
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/logging/__init__.py", line 617, in filter
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     if not f.filter(record):
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/etc/fedmsg.d/logging.py", line 50, in filter
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     current_process = ContextInjector.get_current_process()
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/etc/fedmsg.d/logging.py", line 139, in get_current_process
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     for proc in psutil.process_iter():
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 1231, in process_iter
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     a = set(pids())
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 1185, in pids
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     return _psplatform.pids()
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:   File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 349, in pids
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]:     return [int(x) for x in os.listdir(b'/proc') if x.isdigit()]
Sep 25 03:59:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[2869]: OSError: [Errno 24] Too many open files: '/proc'
```

**Comment by bowlofeggs** [comment]
@puiterwijk fixed this issue with a change in createrepo_c:

https://github.com/rpm-software-management/createrepo_c/pull/64

I'm closing this issue. Thanks @puiterwijk!
