### ISSUE TITLE
error: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#988]
If fedmsg-hub isn't restarted before mashing, Bodhi will run out of file handles eventually. I don't know which files or connections aren't being closed when Bodhi is done with them, so we'll need to do some investigation to figure out how to make the masher more robust.

Here's some logs from today when this happened:

```
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: [2016-09-29 17:29:49][    fedmsg   ERROR]f24-updates Exception in MasherThread(f24-updates)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: Traceback (most recent call last):
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 336, in work
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     uinfo = self.generate_updateinfo()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 707, in generate_updateinfo
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.db, self.path)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 80, in __init__
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self._load_cached_updateinfo()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 145, in _load_cached_updateinfo
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.add_update(update)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 229, in add_update
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     rpms = self.koji.listBuildRPMs(kojiBuild['id'])
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1736, in __call__
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     return self.__func(self.__name,args,opts)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2099, in _callMethod
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     return self._sendCall(handler, headers, request)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2010, in _sendCall
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     return self._sendOneCall(handler, headers, request)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2028, in _sendOneCall
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     cnx.endheaders()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self._send_output(message_body)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.send(msg)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib64/python2.7/httplib.py", line 859, in send
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.connect()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/ssl/SSLCommon.py", line 98, in connect
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     for res in socket.getaddrinfo(self.host, self.port, 0, socket.SOCK_STREAM):
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: error: [Errno 24] Too many open files
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: [2016-09-29 17:29:49][    fedmsg    INFO]f24-updates Masher lock saved: /mnt/koji/mash/updates/MASHING-f24-updates
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: [2016-09-29 17:29:49][    fedmsg    INFO]f24-updates Thread(f24-updates) finished.  Success: False
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: [2016-09-29 17:29:49][    fedmsg   ERROR]f24-updates MasherThread failed. Transaction rolled back.
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: Traceback (most recent call last):
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 257, in run
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.work()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 336, in work
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     uinfo = self.generate_updateinfo()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 707, in generate_updateinfo
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.db, self.path)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 80, in __init__
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self._load_cached_updateinfo()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 145, in _load_cached_updateinfo
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.add_update(update)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/bodhi/server/metadata.py", line 229, in add_update
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     rpms = self.koji.listBuildRPMs(kojiBuild['id'])
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1736, in __call__
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     return self.__func(self.__name,args,opts)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2099, in _callMethod
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     return self._sendCall(handler, headers, request)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2010, in _sendCall
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     return self._sendOneCall(handler, headers, request)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2028, in _sendOneCall
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     cnx.endheaders()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self._send_output(message_body)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.send(msg)
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib64/python2.7/httplib.py", line 859, in send
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     self.connect()
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:   File "/usr/lib/python2.7/site-packages/koji/ssl/SSLCommon.py", line 98, in connect
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]:     for res in socket.getaddrinfo(self.host, self.port, 0, socket.SOCK_STREAM):
Sep 29 17:29:49 bodhi-backend03.phx2.fedoraproject.org fedmsg-hub[66334]: error: [Errno 24] Too many open files
```

**Comment by bowlofeggs** [comment]
I believe that @puiterwijk has fixed this in rpm-ostree and/or createrepo_c.

**Comment by puiterwijk** [comment]
This was a combination of:
- rpm-software-management/createrepo_c#66
- fedora-infra/fedmsg-atomic-composer#9
